Description of addNoiseToSignal
addNoiseToSignal
PURPOSE
adds noise with mean 'mu' and standard deviation 'sigma' to
SYNOPSIS
function [signalN,noise] = addNoiseToSignal(signal,mu,sigma)
DESCRIPTION
addNoiseToSignal adds noise with mean 'mu' and standard deviation 'sigma' to
a synthetic NMR signal
 Syntax:
       addNoiseToSignal(time,signal,varargin)
 Inputs:
       signal - vector or matrix containing the NMR data
       mu - mean of the Gaussian noise (generally 0)
       sigma - standard deviation of the Gaussian noise
 Outputs:
       signalN - NMR signal with noise
       noise - noise vector/matrix
 Example:
       [sN,noise] = addNoiseToSignal(signal,0,0.01)
 Other m-files required:
       none
 Subfunctions:
       none
 MAT-files required:
       none
 See also:
 Author: see AUTHORS.md
 email: see AUTHORS.md
 License: MIT License (at end)
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
LoadNMRData_mouseT1T2 loads T1T2 NMR data from a typical folder structure
Mod2DView is an extra subGUI to calculate 2D forward T1-T2 data
Mod2DView is an extra subGUI to calculate 2D forward T1-T2 data
updateNMRsignals adds noise to the forward NMR signals and scales the
estimateUncertainty calculates pseudo uncertainty estimates for multi
SOURCE CODE
function [signalN,noise] = addNoiseToSignal(signal,mu,sigma)
%addNoiseToSignal adds noise with mean 'mu' and standard deviation 'sigma' to
%a synthetic NMR signal
%
% Syntax:
%       addNoiseToSignal(time,signal,varargin)
%
% Inputs:
%       signal - vector or matrix containing the NMR data
%       mu - mean of the Gaussian noise (generally 0)
%       sigma - standard deviation of the Gaussian noise
%
% Outputs:
%       signalN - NMR signal with noise
%       noise - noise vector/matrix
%
% Example:
%       [sN,noise] = addNoiseToSignal(signal,0,0.01)
%
% Other m-files required:
%       none
%
% Subfunctions:
%       none
%
% MAT-files required:
%       none
%
% See also:
% Author: see AUTHORS.md
% email: see AUTHORS.md
% License: MIT License (at end)
%------------- BEGIN CODE --------------
% generate the noise
noise = mu + (sigma.*randn(size(signal)));
% and the noisy signal
signalN = signal + noise;
return
%------------- END OF CODE --------------
%% License:
% MIT License
%
% Copyright (c) 2018 Thomas Hiller
%
% Permission is hereby granted, free of charge, to any person obtaining a copy
% of this software and associated documentation files (the "Software"), to deal
% in the Software without restriction, including without limitation the rights
% to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
% copies of the Software, and to permit persons to whom the Software is
% furnished to do so, subject to the following conditions:
%
% The above copyright notice and this permission notice shall be included in all
% copies or substantial portions of the Software.
%
% THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
% IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
% FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
% AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
% LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
% OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
% SOFTWARE.