function [gui,myui] = NUCLEUSmod_createPanelNMR(data,gui,myui)
%NUCLEUSmod_createPanelNMR creates NMR panel
%
% Syntax:
%       [gui,myui] = NUCLEUSmod_createPanelNMR(data,gui,myui)
%
% Inputs:
%       data - figure data structure
%       gui - figure gui elements structure
%       myui - individual GUI settings structure
%
% Outputs:
%       gui
%       myui
%
% Example:
%       [gui,myui] = NUCLEUSmod_createPanelNMR(data,gui,myui)
%
% Other m-files required:
%       findjobj.m
% Subfunctions:
%       none
% MAT-files required:
%       none
%
% See also: NUCLEUSmod
% Author: Thomas Hiller
% email: thomas.hiller[at]leibniz-liag.de
% License: MIT License (at end)

%------------- BEGIN CODE --------------

%% create all boxes
gui.panels.nmr.VBox = uix.VBox('Parent',gui.panels.nmr.main,...
    'Spacing',3,'Padding',3);

% Tbulk & surface relaxivity rho
gui.panels.nmr.HBox1 = uix.HBox('Parent',gui.panels.nmr.VBox,...
    'Spacing',3);
% echo time TE & number of echos
gui.panels.nmr.HBox2 = uix.HBox('Parent',gui.panels.nmr.VBox,...
    'Spacing',3);
% RUN button
gui.panels.nmr.HBox3 = uix.HBox('Parent',gui.panels.nmr.VBox,...
    'Spacing',3);
% noise & porosity
gui.panels.nmr.HBox4 = uix.HBox('Parent',gui.panels.nmr.VBox,...
    'Spacing',3);

%% Tbulk & surface relaxivity rho
gui.text_handles.Tbulk = uicontrol('Parent',gui.panels.nmr.HBox1,...
    'Style','text','FontSize',myui.fontsize,'HorizontalAlignment','center',...
    'String','Tbulk [s]');
tstr = ['<HTML>Set relaxation time of bulk water.<br><br>',...
    '<u>Default value:</u><br>',...
    '<b>2 s</b><br>'];
gui.edit_handles.Tbulk = uicontrol('Parent',gui.panels.nmr.HBox1,...
    'Style','edit','String',num2str(data.nmr.Tbulk),'FontSize',myui.fontsize,...
    'UserData',struct('Tooltipstr',tstr,'defaults',[data.nmr.Tbulk 1 1]),...
    'Tag','nmr_Tbulk','Enable','on','Callback',@onEditValue);
gui.text_handles.rho = uicontrol('Parent',gui.panels.nmr.HBox1,...
    'Style','text','FontSize',myui.fontsize,'HorizontalAlignment','center',...
    'String',[char(hex2dec('03C1')),' [µm/s]']);
tstr = ['<HTML>Set surface relaxivity &rho .<br><br>',...
    '<u>Default value:</u><br>',...
    '<b>10 µm/s</b><br>'];
gui.edit_handles.rho = uicontrol('Parent',gui.panels.nmr.HBox1,...
    'Style','edit','String',num2str(data.nmr.rho),'FontSize',myui.fontsize,...
    'UserData',struct('Tooltipstr',tstr,'defaults',[data.nmr.rho 1 1]),...
    'Tag','nmr_rho','Enable','on','Callback',@onEditValue);
set(gui.panels.nmr.HBox1,'Widths',[100 -1 100 -1]);

%% echo time TE & number of echoes
gui.text_handles.TE = uicontrol('Parent',gui.panels.nmr.HBox2,...
    'Style','text','FontSize',myui.fontsize,'HorizontalAlignment','center',...
    'String','echo time [µs]');
tstr = ['<HTML>Set echo time.<br><br>',...
    '<u>Default value:</u><br>',...
    '<b>1000 µs</b><br>'];
gui.edit_handles.TE = uicontrol('Parent',gui.panels.nmr.HBox2,...
    'Style','edit','String',num2str(data.nmr.TE),'FontSize',myui.fontsize,...
    'UserData',struct('Tooltipstr',tstr,'defaults',[data.nmr.TE 1 1]),...
    'Tag','nmr_TE','Enable','on','Callback',@onEditValue);
gui.text_handles.echosN = uicontrol('Parent',gui.panels.nmr.HBox2,...
    'Style','text','FontSize',myui.fontsize,'HorizontalAlignment','center',...
    'String','# echoes');
tstr = ['<HTML>Set number of echoes.<br><br>',...
    '<u>Default value:</u><br>',...
    '<b>1001</b><br>'];
gui.edit_handles.echosN = uicontrol('Parent',gui.panels.nmr.HBox2,...
    'Style','edit','String',num2str(data.nmr.echosN),'FontSize',myui.fontsize,...
    'UserData',struct('Tooltipstr',tstr,'defaults',[data.nmr.echosN 1 1]),...
    'Tag','nmr_echosN','Enable','on','Callback',@onEditValue);
set(gui.panels.nmr.HBox2,'Widths',[100 -1 100 -1]);

%% RUN button
gui.text_handles.nmr_RUN = uicontrol('Parent',gui.panels.nmr.HBox3,...
    'Style','text','FontSize',myui.fontsize,'HorizontalAlignment','center',...
    'String','calculate NMR');
gui.push_handles.nmr_RUN = uicontrol('Parent',gui.panels.nmr.HBox3,...
    'Style','pushbutton','String','RUN','FontSize',myui.fontsize,'Tag','nmr',...
    'BackgroundColor','g','Enable','on','Callback',@onPushRun);
set(gui.panels.nmr.HBox3,'Widths',[200 -1]);

%% noise & porosity
gui.text_handles.noise = uicontrol('Parent',gui.panels.nmr.HBox4,...
    'Style','text','FontSize',myui.fontsize,'HorizontalAlignment','center',...
    'String','add noise');
tstr = ['<HTML>Set NMR data noise.<br><br>',...
    '<u>Hint:</u><br>',...
    'You do not need to press RUN to add noise to the NMR signals.<br>',...
    'The raw NMR signals are stored internally and the noise is<br>',...
    'applied instantaneously.<br><br>',...
    '<u>Default value:</u><br>',...
    '<b>0</b><br>'];
gui.edit_handles.noise = uicontrol('Parent',gui.panels.nmr.HBox4,...
    'Style','edit','String',num2str(data.nmr.noise),'FontSize',myui.fontsize,...
    'UserData',struct('Tooltipstr',tstr,'defaults',[data.nmr.noise 1 1]),...
    'Tag','nmr_noise','Enable','on','Callback',@onEditValue);
gui.text_handles.porosity = uicontrol('Parent',gui.panels.nmr.HBox4,...
    'Style','text','FontSize',myui.fontsize,'HorizontalAlignment','center',...
    'String','porosity');
tstr = ['<HTML>Set porosity value in the range [0, 1].<br><br>',...
    '<u>Note:</u><br>',...
    'This value is applied only as a scaling factor to the NMR amplitudes.<br>',...
    'Hence, saturation becomes water content.'];
gui.edit_handles.porosity = uicontrol('Parent',gui.panels.nmr.HBox4,...
    'Style','edit','String',num2str(data.nmr.porosity),'FontSize',myui.fontsize,...
    'UserData',struct('Tooltipstr',tstr,'defaults',[data.nmr.porosity 1 1]),...
    'Tag','nmr_porosity','Enable','on','Callback',@onEditValue);
set(gui.panels.nmr.HBox4,'Widths',[100 -1 100 -1]);

%% Java Hack to adjust vertical alignment of text fields
jh = findjobj(gui.text_handles.Tbulk);
jh.setVerticalAlignment(javax.swing.JLabel.CENTER);
jh = findjobj(gui.text_handles.rho);
jh.setVerticalAlignment(javax.swing.JLabel.CENTER);
jh = findjobj(gui.text_handles.TE );
jh.setVerticalAlignment(javax.swing.JLabel.CENTER);
jh = findjobj(gui.text_handles.echosN );
jh.setVerticalAlignment(javax.swing.JLabel.CENTER);
jh = findjobj(gui.text_handles.nmr_RUN);
jh.setVerticalAlignment(javax.swing.JLabel.CENTER);
jh = findjobj(gui.text_handles.noise);
jh.setVerticalAlignment(javax.swing.JLabel.CENTER);
jh = findjobj(gui.text_handles.porosity);
jh.setVerticalAlignment(javax.swing.JLabel.CENTER);

return

%------------- END OF CODE --------------

%% License:
% MIT License
%
% Copyright (c) 2018 Thomas Hiller
%
% Permission is hereby granted, free of charge, to any person obtaining a copy
% of this software and associated documentation files (the "Software"), to deal
% in the Software without restriction, including without limitation the rights
% to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
% copies of the Software, and to permit persons to whom the Software is
% furnished to do so, subject to the following conditions:
%
% The above copyright notice and this permission notice shall be included in all
% copies or substantial portions of the Software.
%
% THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
% IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
% FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
% AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
% LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
% OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
% SOFTWARE.