Description of beautifyAxes
beautifyAxes
PURPOSE
can be used to globally change the general appearance of axes
SYNOPSIS
function beautifyAxes(figh)
DESCRIPTION
beautifyAxes can be used to globally change the general appearance of axes
 Syntax:
       beautifyAxes(figh)
 Inputs:
       figh - figure handle
 Outputs:
       none
 Example:
       beautifyAxes(gcf)
 Other m-files required:
       none
 Subfunctions:
       none
 MAT-files required:
       none
 See also: NUCLEUSinv, NUCLEUSmod
 Author: see AUTHORS.md
 email: see AUTHORS.md
 License: MIT License (at end)
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
NUCLEUSinv_createPanelPlots creates graphics panel
NUCLEUSmod_createPanelPlots creates graphics panel
Inv2DView is an extra subGUI to calculate 2D inversion of T1-T2 data
Mod2DView is an extra subGUI to calculate 2D forward T1-T2 data
UncertView is an extra subGUI to show results of the uncertainty
Inv2DView is an extra subGUI to calculate 2D inversion of T1-T2 data
Mod2DView is an extra subGUI to calculate 2D forward T1-T2 data
UncertView is an extra subGUI to show results of the uncertainty
updatePlotsJointInversion plots the joint-inversion results in NUCLEUSinv
updatePlotsLcurve plots the results of the L-curve calculation
updatePlotsNMR plots the forward modeled NMR data in NUCLEUSmod
updatePlotsPSD plots the pore size distribution in NUCLEUSmod
updatePlotsSignal plots the raw and processed NMR signals in NUCLEUSinv
SOURCE CODE
function beautifyAxes(figh)
%beautifyAxes can be used to globally change the general appearance of axes
%
% Syntax:
%       beautifyAxes(figh)
%
% Inputs:
%       figh - figure handle
%
% Outputs:
%       none
%
% Example:
%       beautifyAxes(gcf)
%
% Other m-files required:
%       none
%
% Subfunctions:
%       none
%
% MAT-files required:
%       none
%
% See also: NUCLEUSinv, NUCLEUSmod
% Author: see AUTHORS.md
% email: see AUTHORS.md
% License: MIT License (at end)
%------------- BEGIN CODE --------------
%% find all axes in figure;
ax = findobj(figh,'Type','Axes');
% and adjust their font size
set(ax,'FontSize',10);
end
%------------- END OF CODE --------------
%% License:
% MIT License
%
% Copyright (c) 2018 Thomas Hiller
%
% Permission is hereby granted, free of charge, to any person obtaining a copy
% of this software and associated documentation files (the "Software"), to deal
% in the Software without restriction, including without limitation the rights
% to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
% copies of the Software, and to permit persons to whom the Software is
% furnished to do so, subject to the following conditions:
%
% The above copyright notice and this permission notice shall be included in all
% copies or substantial portions of the Software.
%
% THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
% IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
% FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
% AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
% LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
% OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
% SOFTWARE.