Description of clearSingleAxis
clearSingleAxis
PURPOSE
clears an individual axis
SYNOPSIS
function clearSingleAxis(axh)
DESCRIPTION
clearSingleAxis clears an individual axis
 Syntax:
       clearSingleAxis(axh)
 Inputs:
       axh - axis handle
 Outputs:
       none
 Example:
       clearSingleAxis(gca)
 Other m-files required:
       clearSingleAxis
 Subfunctions:
       none
 MAT-files required:
       none
 See also: NUCLEUSinv
 Author: Thomas Hiller
 email: thomas.hiller[at]leibniz-liag.de
 License: MIT License (at end)
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
onEditValue updates all edit field values, checks for wrong inputs and
onListboxData handles the calls from the context menu of the data
onMenuJointInversion handles the call from the menu that activates / deactivates
onPopupInvjointTypeOptional select regularization option for the joint
onPopupInvstdTypeOptional select regularization option for the standard
onPopupPressureLoglin select if the pressure range values are spaced
onRadioGates selects the re-sampling / gating method ("log", "lin" or "none")
onRadioNormalize selects whether to normalize a NMR signal to 1
onRadioTimescale selects whether the time scale should be "s" or "ms"
caluclatePressureSaturation calculates the geometry dependent pressure
clearAllAxes clears all axes of a given figure
clearInversion removes inversion results from the internal data structure
runInversionJoint controls the joint inversion process to infer a pore size
runInversionStd controls the standard inversion process to invert a
updatePlotsDistribution plots the RTD and PSD curves into NUCLEUSinv
updatePlotsIterChi plots the results of the chi2 iteration
updatePlotsJointInversion plots the joint-inversion results in NUCLEUSinv
updatePlotsLcurve
updatePlotsNMR plots the forward modeled NMR data in NUCLEUSmod
updatePlotsPSD plots the pore size distribution in NUCLEUSmod
updatePlotsSignal plots the raw and processed NMR signals in NUCLEUSinv
SOURCE CODE
function clearSingleAxis(axh)
%clearSingleAxis clears an individual axis
%
% Syntax:
%       clearSingleAxis(axh)
%
% Inputs:
%       axh - axis handle
%
% Outputs:
%       none
%
% Example:
%       clearSingleAxis(gca)
%
% Other m-files required:
%       clearSingleAxis
%
% Subfunctions:
%       none
%
% MAT-files required:
%       none
%
% See also: NUCLEUSinv
% Author: Thomas Hiller
% email: thomas.hiller[at]leibniz-liag.de
% License: MIT License (at end)
%------------- BEGIN CODE --------------
%% get the parent of the axis and find possible legends
parent = get(axh,'Parent');
lgh = findobj('Type','legend','Parent',parent);
if ~isempty(lgh)
    delete(lgh);
end
%% look for specific tags and clear corresponding objects
ph = findall(axh,'Tag','SatPoints');
if ~isempty(ph); set(ph,'HandleVisibility','on'); end
ph = findall(axh,'Tag','fits');
if ~isempty(ph); set(ph,'HandleVisibility','on'); end
%% clear the axis itself
cla(axh);
end
%------------- END OF CODE --------------
%% License:
% MIT License
%
% Copyright (c) 2018 Thomas Hiller
%
% Permission is hereby granted, free of charge, to any person obtaining a copy
% of this software and associated documentation files (the "Software"), to deal
% in the Software without restriction, including without limitation the rights
% to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
% copies of the Software, and to permit persons to whom the Software is
% furnished to do so, subject to the following conditions:
%
% The above copyright notice and this permission notice shall be included in all
% copies or substantial portions of the Software.
%
% THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
% IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
% FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
% AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
% LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
% OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
% SOFTWARE.