Description of clearAllAxes
clearAllAxes
PURPOSE
clears all axes of a given figure
SYNOPSIS
function clearAllAxes(figh)
DESCRIPTION
clearAllAxes clears all axes of a given figure
 Syntax:
       clearAllAxes(figh)
 Inputs:
       figh - figure handle
 Outputs:
       none
 Example:
       clearAllAxes(gcf)
 Other m-files required:
       clearSingleAxis
 Subfunctions:
       none
 MAT-files required:
       none
 See also: NUCLEUSinv, NUCLEUSmod
 Author: Thomas Hiller
 email: thomas.hiller[at]leibniz-liag.de
 License: MIT License (at end)
CROSS-REFERENCE INFORMATION
This function calls:
clearSingleAxis clears an individual axis
This function is called by:
calculateGeometry calculates the shape dependent geometry parameters
clearInversion removes inversion results from the internal data structure
importASCIIdata imports NMR data from ASCII files
importEXCELdata imports NMR data from Excel files
importMOD2INV
importNMRdata is the general import routine for NMR data
removeSignalFromList removes the chosen NMR signal from the GUI
runInversionStd controls the standard inversion process to invert a
showFitStatistics shows an extra fit statistics figure (for T2 data)
SOURCE CODE
function clearAllAxes(figh)
%clearAllAxes clears all axes of a given figure
%
% Syntax:
%       clearAllAxes(figh)
%
% Inputs:
%       figh - figure handle
%
% Outputs:
%       none
%
% Example:
%       clearAllAxes(gcf)
%
% Other m-files required:
%       clearSingleAxis
%
% Subfunctions:
%       none
%
% MAT-files required:
%       none
%
% See also: NUCLEUSinv, NUCLEUSmod
% Author: Thomas Hiller
% email: thomas.hiller[at]leibniz-liag.de
% License: MIT License (at end)
%------------- BEGIN CODE --------------
%% find all aes and clear them
ax = findobj(figh,'Type','Axes');
for i = 1:numel(ax)
    clearSingleAxis(ax(i));
end
end
%------------- END OF CODE --------------
%% License:
% MIT License
%
% Copyright (c) 2018 Thomas Hiller
%
% Permission is hereby granted, free of charge, to any person obtaining a copy
% of this software and associated documentation files (the "Software"), to deal
% in the Software without restriction, including without limitation the rights
% to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
% copies of the Software, and to permit persons to whom the Software is
% furnished to do so, subject to the following conditions:
%
% The above copyright notice and this permission notice shall be included in all
% copies or substantial portions of the Software.
%
% THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
% IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
% FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
% AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
% LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
% OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
% SOFTWARE.