Description of displayStatusText
displayStatusText
PURPOSE
clears all axes of a given figure
SYNOPSIS
function displayStatusText(gui,string)
DESCRIPTION
displayStatusText clears all axes of a given figure
 Syntax:
       displayStatusText(gui,string)
 Inputs:
       gui - figure gui elements structure
       string - string to show in status bar
 Outputs:
       none
 Example:
       displayStatusText(gui,string)
 Other m-files required:
       none
 Subfunctions:
       none
 MAT-files required:
       none
 See also: NUCLEUSinv, NUCLEUSmod
 Author: Thomas Hiller
 email: thomas.hiller[at]leibniz-liag.de
 License: MIT License (at end)
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
NUCLEUSinv_createGUI controls the creation of all GUI elements
NUCLEUSmod_createGUI controls the creation of all GUI elements
calculateNMR calculates the NMR signals for the full and partially saturated
caluclatePressureSaturation calculates the geometry dependent pressure
exportData exports data from both GUIs into various formats
exportGraphics exports graphics from both GUIs into various formats
exportINV exports NUCLEUSinv GUI data to a mat-file
importCalibrationData
importNMRdata is the general import routine for NMR data
runInversionBatch batch processes the inversion using for all NMR signals
runInversionJoint controls the joint inversion process to infer a pore size
runInversionStd controls the standard inversion process to invert a
useSignalAsCalibration uses E0 as porosity calibration factor.
SOURCE CODE
function displayStatusText(gui,string)
%displayStatusText clears all axes of a given figure
%
% Syntax:
%       displayStatusText(gui,string)
%
% Inputs:
%       gui - figure gui elements structure
%       string - string to show in status bar
%
% Outputs:
%       none
%
% Example:
%       displayStatusText(gui,string)
%
% Other m-files required:
%       none
%
% Subfunctions:
%       none
%
% MAT-files required:
%       none
%
% See also: NUCLEUSinv, NUCLEUSmod
% Author: Thomas Hiller
% email: thomas.hiller[at]leibniz-liag.de
% License: MIT License (at end)
%------------- BEGIN CODE --------------
%% display status / info text
set(gui.textStatus,'String',string);
pause(0.001);
end
%------------- END OF CODE --------------
%% License:
% MIT License
%
% Copyright (c) 2018 Thomas Hiller
%
% Permission is hereby granted, free of charge, to any person obtaining a copy
% of this software and associated documentation files (the "Software"), to deal
% in the Software without restriction, including without limitation the rights
% to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
% copies of the Software, and to permit persons to whom the Software is
% furnished to do so, subject to the following conditions:
%
% The above copyright notice and this permission notice shall be included in all
% copies or substantial portions of the Software.
%
% THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
% IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
% FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
% AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
% LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
% OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
% SOFTWARE.