Description of getColorIndex
getColorIndex
PURPOSE
exports graphics from both GUIs into various formats
SYNOPSIS
function index = getColorIndex(sat,N)
DESCRIPTION
getColorIndex exports graphics from both GUIs into various formats
 Syntax:
       index = getColorIndex(sat,N)
 Inputs:
       sat - saturation value(s)
       N - discretization of colormap between [0,1]
 Outputs:
       index - closest index of the current saturation in the color
       vector S of size N
 Example:
       index = getColorIndex(sat,N)
 Other m-files required:
       none
 Subfunctions:
       none
 MAT-files required:
       none
 See also: NUCLEUSinv, NUCLEUSmod
 Author: Thomas Hiller
 email: thomas.hiller[at]leibniz-liag.de
 License: MIT License (at end)
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
updatePlotsCPS plots the CPS curve into the corresponding NUCLEUSmod axis
updatePlotsJointInversion plots the joint-inversion results in NUCLEUSinv
updatePlotsNMR plots the forward modeled NMR data in NUCLEUSmod
updatePlotsSignal plots the raw and processed NMR signals in NUCLEUSinv
SOURCE CODE
function index = getColorIndex(sat,N)
%getColorIndex exports graphics from both GUIs into various formats
%
% Syntax:
%       index = getColorIndex(sat,N)
%
% Inputs:
%       sat - saturation value(s)
%       N - discretization of colormap between [0,1]
%
% Outputs:
%       index - closest index of the current saturation in the color
%       vector S of size N
%
% Example:
%       index = getColorIndex(sat,N)
%
% Other m-files required:
%       none
%
% Subfunctions:
%       none
%
% MAT-files required:
%       none
%
% See also: NUCLEUSinv, NUCLEUSmod
% Author: Thomas Hiller
% email: thomas.hiller[at]leibniz-liag.de
% License: MIT License (at end)
%------------- BEGIN CODE --------------
%% discretization of S between [0,1]
S = linspace(0,1,N);
%% find closest index
index = zeros(size(sat));
for i = 1:numel(sat)
    index(i) = find(abs(S-sat(i)) == min(abs(S-sat(i))),1);
end
end
%------------- END OF CODE --------------
%% License:
% MIT License
%
% Copyright (c) 2018 Thomas Hiller
%
% Permission is hereby granted, free of charge, to any person obtaining a copy
% of this software and associated documentation files (the "Software"), to deal
% in the Software without restriction, including without limitation the rights
% to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
% copies of the Software, and to permit persons to whom the Software is
% furnished to do so, subject to the following conditions:
%
% The above copyright notice and this permission notice shall be included in all
% copies or substantial portions of the Software.
%
% THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
% IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
% FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
% AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
% LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
% OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
% SOFTWARE.