Description of importNMRdata
importNMRdata
PURPOSE
is the general import routine for NMR data
SYNOPSIS
function importNMRdata(src)
DESCRIPTION
importNMRdata is the general import routine for NMR data
 Syntax:
       importNMRdata(src)
 Inputs:
       src - handle of the calling menu
 Outputs:
       none
 Example:
       importNMRdata(src)
 Other m-files required:
       cleanupGUIData
       clearAllAxes
       displayStatusText
       enableGUIelements('NMR');
       LoadNMRData_driver
       NUCLEUSinv_updateInterface
 Subfunctions:
       getNMRPathFile
       importDataBGR
       importDataBGRmat
       importDataDart
       importDataGeneral
       importDataLIAG
       importDataLIAGproject
       importDataMouse
       importDataHelios
       loadGUIParameters
       loadGUIrawdata
 MAT-files required:
       none
 See also: NUCLEUSinv, NUCLEUSmod
 Author: see AUTHORS.md
 email: see AUTHORS.md
 License: MIT License (at end)
CROSS-REFERENCE INFORMATION
This function calls:
NUCLEUSinv_updateInterface updates all GUI elements
LoadNMRData_driver loads NMR raw data from different file formats
fixParameterString cleans parameter file lines when the properties have a
rotateT2phase rotateT2phase rotates the complex NMR T2 signal so that the imaginary
Inv2DView is an extra subGUI to calculate 2D inversion of T1-T2 data
cleanupGUIData removes unnecessary fields from the global "data" struct
clearAllAxes clears all axes of a given figure
displayStatusText shows status information either in the GUI or on the
enableGUIelements activates all necessary GUI elements after successful
makeINIfile creates or updates the ini-File
Inv2DView is an extra subGUI to calculate 2D inversion of T1-T2 data
fitDataFree is a control routine that uses 'lsqcurvefit' to fit NMR data
This function is called by:
onMenuImport handles the import menu entries
SUBFUNCTIONS
function [NMRpath,NMRfile] = getNMRPathFile(label,import)
function [data,gui] = importDataMouseCPMG(data,gui)
function [data,gui] = importDataBGRmat(data,gui)
function [data,gui] = importDataBGRliftSingle(data,gui)
function [data,gui] = importDataBGRlift(data,gui)
function [data,gui] = importDataBGRMouseT1T2(data,gui)
function [data,gui] = importDataHeliosCPMG(data,gui)
function [data,gui] = importDataHeliosSeries(data,gui)
function [data,gui] = importDataDartSeries(data,gui)
function [data,gui] = importDataDart(data,gui)
function [data,gui] = importDataRoCAT1T2(data,gui)
function [data,gui] = importDataGeneral(data,gui)
function [data,gui] = importDataLIAG(data,gui)
function [data,gui] = importDataLIAGcore(data,gui)
function [data,gui] = importDataLIAGproject(data,gui)
function [data,gui] = importDataMouse(data,gui)
function [data,gui] = importDataMRSMatlab(data,gui)
function [data,gui] = importDataIBAC(data,gui)
function data = loadGUIParameters(datapath,fname)
function data = loadGUIrawdata(data,NMRpath,NMRfile)
SOURCE CODE
function importNMRdata(src)
%importNMRdata is the general import routine for NMR data
%
% Syntax:
%       importNMRdata(src)
%
% Inputs:
%       src - handle of the calling menu
%
% Outputs:
%       none
%
% Example:
%       importNMRdata(src)
%
% Other m-files required:
%       cleanupGUIData
%       clearAllAxes
%       displayStatusText
%       enableGUIelements('NMR');
%       LoadNMRData_driver
%       NUCLEUSinv_updateInterface
%
% Subfunctions:
%       getNMRPathFile
%       importDataBGR
%       importDataBGRmat
%       importDataDart
%       importDataGeneral
%       importDataLIAG
%       importDataLIAGproject
%       importDataMouse
%       importDataHelios
%       loadGUIParameters
%       loadGUIrawdata
%
% MAT-files required:
%       none
%
% See also: NUCLEUSinv, NUCLEUSmod
% Author: see AUTHORS.md
% email: see AUTHORS.md
% License: MIT License (at end)
%------------- BEGIN CODE --------------
%% get GUI handle and data
fig = findobj('Tag','INV');
gui = getappdata(fig,'gui');
data = getappdata(fig,'data');
% try is used to catch any import error
% often the wrong input file format is the case
try
    % check what import format is chosen
    label = get(src,'Label');
    % set file format for later use
    if strcmp(label,'Dart (jrd)')
        data.import.fileformat = 'dartjrd';
    elseif strcmp(label,'BAM TOM')
        data.import.fileformat = 'bamtom';
    elseif strcmp(label,'BGR mat')
        data.import.fileformat = 'bgrmat';
    elseif strcmp(label,'BGR std')
        data.import.fileformat = 'bgr';
    elseif strcmp(label,'CoreLab ascii')
        data.import.fileformat = 'corelab';
    elseif strcmp(label,'DART')
        data.import.fileformat = 'dart';
    elseif strcmp(label,'GGE ascii')
        data.import.fileformat = 'rwth';
    elseif strcmp(label,'GGE field')
        data.import.fileformat = 'field';
    elseif strcmp(label,'GGE Dart')
        data.import.fileformat = 'dart';
    elseif strcmp(label,'HeliosCPMG')
        data.import.fileformat = 'heliosCPMG';
    elseif strcmp(label,'HeliosSeries')
        data.import.fileformat = 'heliosSeries';
    elseif strcmp(label,'LIAG core')
        data.import.fileformat = 'liag';
    elseif strcmp(label,'LIAG from project')
        data.import.fileformat = 'liag';
    elseif strcmp(label,'LIAG last project')
        data.import.fileformat = 'liag';
    elseif strcmp(label,'LIAG single')
        data.import.fileformat = 'liag';
    elseif strcmp(label,'MOUSE')
        data.import.fileformat = 'mouse';
    elseif strcmp(label,'MouseCPMG')
        data.import.fileformat = 'MouseCPMG';
    elseif strcmp(label,'MouseLift')
        data.import.fileformat = 'MouseLift';
    elseif strcmp(label,'MouseT1T2')
        data.import.fileformat = 'MouseT1T2';
    elseif strcmp(label,'MRSMatlab (FIT)')
        data.import.fileformat = 'mrsd';
    elseif strcmp(label,'PM5')
        data.import.fileformat = 'pm5';
    elseif strcmp(label,'PM25')
        data.import.fileformat = 'pm25';
    elseif strcmp(label,'RoCA T1T2')
        data.import.fileformat = 'rocaT1T2';
    else
        helpdlg('Something is utterly wrong.','onMenuImport: Choose again.');
    end
    % remove info field if any
    ih = findobj('Tag','inv_info');
    if ~isempty(ih); delete(ih); end
    % depending on the import format get the corresponding path / file
    [NMRpath,NMRfile] = getNMRPathFile(label,data.import);
    % only continue if user didn't cancel
    if sum([NMRpath NMRfile]) > 0
        %  remove old fields and data
        data = cleanupGUIData(data);
        % check for mat-file with GUI rawdata and import data
        isfile = dir(fullfile(NMRpath,'NUCLEUSinv_raw.mat'));
        % if there is no raw-file import from folder/file
        if isempty(isfile)
            % import data
            data.import.path = NMRpath;
            data.import.file = -1;
            displayStatusText(gui,'Reading NMR Data ...');
            % call the corresponding subroutines
            switch label
                case {'BAM TOM','BGR std','CoreLab ascii','GGE ascii',...
                        'GGE field'}
                    [data,gui] = importDataGeneral(data,gui);
                case 'GGE Dart'
                    data.import.file = NMRfile;
                    % the data in the example folder is an older type
                    if contains(NMRpath,'nucleus\example_data\dart')
                        data.import.version = 1;
                    else
                        data.import.version = 2;
                    end
                    [data,gui] = importDataDart(data,gui);
                case 'DART'
                    data.import.file = NMRfile;
                    data.import.version = 3;
                    [data,gui] = importDataDart(data,gui);
                case 'MOUSE'
                    [data,gui] = importDataMouse(data,gui);
                case 'LIAG single'
                    [data,gui] = importDataLIAG(data,gui);
                case 'LIAG core'
                    [data,gui] = importDataLIAGcore(data,gui);
                case {'LIAG from project','LIAG last project'}
                    [data,gui] = importDataLIAGproject(data,gui);
                    % make the Petro Panel visible as default
                    tmp_h = gui.myui.heights(2,:);
                    tmp_h(3) = gui.myui.heights(2,3);
                    % but the CPS panel stays minimized
                    tmp_h(5) = gui.myui.heights(1,3);
                    set(gui.panels.main,'Heights',tmp_h);
                    set(gui.panels.petro.main,'Minimized',false);
                case 'BGR mat'
                    data.import.file = NMRfile;
                    [data,gui] = importDataBGRmat(data,gui);
                case 'MouseCPMG'
                    [data,gui] = importDataMouseCPMG(data,gui);
                case 'MouseLift'
                    [data,gui] = importDataBGRlift(data,gui);
                case 'MouseT1T2'
                    [data,gui] = importDataBGRMouseT1T2(data,gui);
                case 'HeliosCPMG'
                    data.import.file = NMRfile;
                    [data,gui] = importDataHeliosCPMG(data,gui);
                case 'HeliosSeries'
                    data.import.file = NMRfile;
                    [data,gui] = importDataHeliosSeries(data,gui);
                case {'PM5','PM25'}
                    data.import.file = NMRfile;
                    [data,gui] = importDataIBAC(data,gui);
                case 'Dart (jrd)'
                    data.import.file = NMRfile;
                    [data,gui] = importDataDartSeries(data,gui);
                case 'RoCA T1T2'
                    data.import.file = NMRfile;
                    [data,gui] = importDataRoCAT1T2(data,gui);
                case 'MRSMatlab (FIT)'
                    data.import.file = NMRfile;
                    [data,gui] = importDataMRSMatlab(data,gui);
            end
            displayStatusText(gui,'Reading NMR Data ... done');
        else
            % import from mat-file
            displayStatusText(gui,'Importing NMR raw data from mat-file ...');
            data = loadGUIrawdata(data,NMRpath,NMRfile);
            displayStatusText(gui,'Importing NMR raw data from mat-file ... done');
        end
        % update the path info field with "NMRpath" ("NMRfile")
        if NMRfile > 0
            tmpstr = fullfile(NMRpath,NMRfile);
        else
            tmpstr = NMRpath;
        end
        if length(tmpstr)>50
            set(gui.text_handles.data_path,'String',['...',tmpstr(end-50:end)],...
                'HorizontalAlignment','left');
        else
            set(gui.text_handles.data_path,'String',tmpstr,...
                'HorizontalAlignment','left');
        end
        set(gui.text_handles.data_path,'TooltipString',tmpstr);
        % update the ini-file
        gui.myui.inidata.importpath = data.import.path;
        gui = makeINIfile(gui,'update');
        % update the list of file names
        set(gui.listbox_handles.signal,'String',data.import.NMR.filesShort);
        set(gui.listbox_handles.signal,'Value',[],'Max',2,'Min',0);
        % create a global INVdata struct for every file in the list
        if isstruct(getappdata(fig,'INVdata'))
            setappdata(fig,'INVdata',[]);
        end
        INVdata = cell(length(data.import.NMR.filesShort),1);
        setappdata(fig,'INVdata',INVdata);
        % clear all axes
        clearAllAxes(gui.figh);
        % update GUI data and interface
        setappdata(fig,'data',data);
        setappdata(fig,'gui',gui);
        enableGUIelements('NMR');
        % special treatment of LIAG projects
        switch label
            case {'LIAG from project','LIAG last project'}
                cpath = data.import.LIAG.calibrationpath;
                % check if this calibration file was already used
                isfile = dir(fullfile(cpath,'NUCLEUS_calibData.mat'));
                if ~isempty(isfile)
                    id = 2;
                    % if data is there reuse it
                    calib = load(fullfile(cpath,isfile.name),'calib');
                    INVdata{id} = calib.calib;
                    data.calib = INVdata{id}.calib;
                    data.import.LIAG.Tbulk = data.calib.Tbulk;%INVdata{id}.results.invstd.T2;
                    setappdata(fig,'INVdata',INVdata);
                    setappdata(fig,'data',data);
                    % color the list entry
                    strL = get(gui.listbox_handles.signal,'String');
                    str1 = strL{id};
                    str2 = ['<HTML><BODY bgcolor="rgb(',...
                        sprintf('%d,%d,%d',gui.myui.colors.listINV.*255),')">',...
                        str1,'</BODY></HTML>'];
                    strL{id} = str2;
                    set(gui.listbox_handles.signal,'String',strL);
                end
            otherwise
        end
        % update GUI interface
        NUCLEUSinv_updateInterface;
        % if the 2D window is open, update it
        if ~isempty(findobj('Tag','2DINV'))
            % but only if there is 2D data loaded
            if isfield(data.import,'T1T2map')
                Inv2DView(gui.menu.extra_T1T2map);
            else
                helpdlg({'function: importNMRdata',...
                    'Careful: 2D GUI is open but 1D data set was imported'},...
                    'Import Notification');
            end
        end
    end
catch ME
    % show error message in case import fails
    errmsg = {ME.message;[ME.stack(1).name,' Line: ',num2str(ME.stack(1).line)];...
        'Check File Format settings.'};
    errordlg(errmsg,'importNMRdata: Error!');
end
end
%%
function [NMRpath,NMRfile] = getNMRPathFile(label,import)
NMRpath = -1;
NMRfile = -1;
% for almost all import cases we load a folder ... but not for all
switch label
    case {'BAM TOM','BGR std','CoreLab ascii','GGE ascii','GGE field',...
            'HeliosCPMG','HeliosSeries','LIAG core','LIAG single',...
            'MOUSE','MouseCPMG','MouseLift','MouseT1T2','PM25','Dart (jrd)',...
            'RoCA T1T2'}
        % if there is already a data folder present we start from here
        if isfield(import,'path')
            NMRpath = uigetdir(import.path,'Choose Data Path');
        else
            % otherwise we start at the current working dircetory
            % 'NMRpath' holds the name of the choosen data path
            here = mfilename('fullpath');
            [pathstr,~,~] = fileparts(here);
            NMRpath = uigetdir(pathstr,'Choose Data Path');
        end
    case 'LIAG from project'
        % if there is already a data folder present we start from here
        if isfield(import,'path')
            NMRpath = uigetdir(import.path,'Choose Project Path');
        else
            % otherwise we start at the current working dircetory
            % 'NMRpath' holds the name of the choosen data path
            here = mfilename('fullpath');
            [pathstr,~,~] = fileparts(here);
            NMRpath = uigetdir(pathstr,'Choose Project Path');
        end
    case 'LIAG last project'
        % there is already a data folder and we use this one
        if isfield(import,'path')
            NMRpath = import.path;
        else
            % otherwise we start at the current working dircetory
            % 'NMRpath' holds the name of the choosen data path
            here = mfilename('fullpath');
            [pathstr,~,~] = fileparts(here);
            NMRpath = uigetdir(pathstr,'Choose Project Path');
        end
    case {'GGE Dart','DART','BGR mat','NMR mat'}
        % if there is already a data folder present we start from here
        if isfield(import,'path')
            [NMRfile,NMRpath] = uigetfile(import.path,'Choose Data file');
        else
            % otherwise we start at the current working dircetory
            % 'foldername' hold s the name of the choosen data path
            here = mfilename('fullpath');
            [pathstr,~,~] = fileparts(here);
            [NMRfile,NMRpath] = uigetfile(pathstr,'Choose Data file');
        end
    case 'MRSMatlab (FIT)'
        % if there is already a data folder present we start from here
        if isfield(import,'path')
            [NMRfile,NMRpath] = uigetfile('*.mrsd','Choose mrsd Data file',import.path);
        else
            % otherwise we start at the current working dircetory
            % 'foldername' hold s the name of the choosen data path
            here = mfilename('fullpath');
            [pathstr,~,~] = fileparts(here);
            [NMRfile,NMRpath] = uigetfile('*.mrsd','mrsd Choose Data file',pathstr);
        end
    case 'PM5'
        % if there is already a data folder present we start from here
        if isfield(import,'path')
            NMRpath = uigetdir(import.path,'Choose PM5 Data Path');
        else
            % otherwise we start at the current working dircetory
            % 'NMRpath' holds the name of the choosen data path
            here = mfilename('fullpath');
            [pathstr,~,~] = fileparts(here);
            NMRpath = uigetdir(pathstr,'Choose PM5 Data Path');
        end
        % check if there are multiple inf-files available
        % if yes -> choose one
        inffiles = dir(fullfile(NMRpath,'*.inf'));
        if numel(inffiles) > 1
            [NMRfile,NMRpath] = uigetfile(fullfile(NMRpath,'*.inf'),...
                'Choose INF file');
        elseif numel(inffiles) == 1
            NMRfile = inffiles.name;
        end
end
end
%%
function [data,gui] = importDataMouseCPMG(data,gui)
csv_t2path = dir(fullfile(data.import.path,'CPMG'));
csv_t2path = csv_t2path(~ismember({csv_t2path.name},{'.','..'}));
fnames = struct;
% shownames is just a dummy to hold all data file names that
% will be shown in the listbox
shownames = cell(1,1);
c = 0;
if ~isempty(csv_t2path)
    for i = 1:size(csv_t2path,1)
        in.T1T2 = 'T2';
        in.path = fullfile(data.import.path,'CPMG',csv_t2path(i).name);
        in.fileformat = data.import.fileformat;
        out = LoadNMRData_driver(in);
        for j = 1:size(out.nmrData,2)
            % the individual file names
            c = c + 1;
            fnames(c).parfile = 'acqu.par';
            fnames(c).datafile = out.nmrData{j}.datfile;
            fnames(c).T2specfile = '';
            shownames{c} = ['T2_',csv_t2path(i).name,'_',fnames(c).datafile];
            % the NMR data
            % here we fix the time scale from [ms] to [s]
            if max(out.nmrData{j}.time) > 100
                out.nmrData{j}.time = out.nmrData{j}.time/1000;
                out.nmrData{j}.raw.time = out.nmrData{j}.raw.time/1000;
            end
            data.import.NMR.data{c} = out.nmrData{j};
            data.import.NMR.para{c} = out.parData;
        end
    end
end
if isempty(csv_t2path)
    helpdlg('No data folders in the given directory.','onMenuImport: No data.');
else
    % update the global data structure
    data.import.NMR.files = fnames;
    data.import.NMR.filesShort = shownames;
end
end
%%
function [data,gui] = importDataBGRmat(data,gui)
in.path = fullfile(data.import.path);
in.name = data.import.file;
in.fileformat = data.import.fileformat;
out = LoadNMRData_driver(in);
fnames = struct;
% shownames is just a dummy to hold all data file names that
% will be shown in the listbox
shownames = cell(1,1);
c = 0;
table = {true,0,1,'D'};
for j = 1:size(out.nmrData,2)
    % the individual file names
    c = c + 1;
    fnames(c).parfile = '';
    fnames(c).datafile = data.import.file;
    fnames(c).T2specfile = '';
    shownames{c} = out.parData{j}.file;
    data.import.NMR.data{c} = out.nmrData{j};
    data.import.NMR.para{c} = out.parData{j};
    if isfield(out,'pressData')
        % convert hPa to Pa
        table{c,1} = true;
        table{c,2} = out.pressData.p(j)*1e2;
        table{c,3} = out.pressData.S(j);
        table{c,4} = 'D';
    end
end
% global Tbulk
data.invstd.Tbulk = out.parData{1}.Tbulk;
% global porosity
data.import.BGR.porosity = out.parData{1}.porosity;
data.import.NMR.files = fnames;
data.import.NMR.filesShort = shownames;
% import pressure / saturation data
if isfield(out,'pressData')
    data.pressure.unit = 'kPa';
    data.pressure.unitfac = 1e-3;
    data.pressure.table = table;
end
end
%%
function [data,gui] = importDataBGRliftSingle(data,gui)
% first check whether T1 or T2 was measured...
% by analyzing the name of data folder
ind = find(data.import.path == filesep);
checkT1T2 = data.import.path(ind(end-1)+1:ind(end)-1);
if strcmp(checkT1T2,'t1test')
    in.T1T2 = 'T1';
elseif strcmp(checkT1T2,'T1auto')
    in.T1T2 = 'T1';
elseif strcmp(checkT1T2,'cpmgfastautotest')
    in.T1T2 = 'T2';
elseif strcmp(checkT1T2,'cpmgfastauto')
    in.T1T2 = 'T2';
else
    disp('Please chose an original Prospa folder for Mouse Lift data!');
end
% % there should be folders with integer values in their names
% t1t2path = data.import.path;
fnames = struct;
% shownames is just a dummy to hold all data file names that
% will be shown in the listbox
shownames = cell(1,1);
c = 0;
if ~isempty(data.import.path)
    %    for i = 1:size(t1t2path,1)
    in.path = data.import.path;
    in.fileformat = data.import.fileformat;
    out = LoadNMRData_driver(in);
    for j = 1:size(out.nmrData,2)
        % the individual file names
        c = c + 1;
        fnames(c).parfile = 'acq.par';
        fnames(c).datafile = out.nmrData{j}.datfile;
        shownames{c} = [in.T1T2,'_',fnames(c).datafile];
        % the NMR data
        % here we fix the time scale from [ms] to [s]
        if max(out.nmrData{j}.time) > 100
            out.nmrData{j}.time = out.nmrData{j}.time/1000;
            out.nmrData{j}.raw.time = out.nmrData{j}.raw.time/1000;
        end
        data.import.NMR.data{c} = out.nmrData{j};
        data.import.NMR.para{c} = out.parData;
    end
else
    helpdlg('No data folders in the given directory.','onMenuImport: No data.');
end
% update the global data structure
data.import.NMR.files = fnames;
data.import.NMR.filesShort = shownames;
end
%%
function [data,gui] = importDataBGRlift(data,gui)
% 1) show all folders and ask for sample
subdirs = dir(data.import.path);
% remove the dot-dirs
subdirs = subdirs(~ismember({subdirs.name},{'.','..'}));
fnames = {subdirs.name};
[indx,~] = listdlg('PromptString','Choose data set:',...
    'SelectionMode','multiple',...
    'ListString',fnames);
% first check whether T1 or T2 was measured
ind = find(data.import.path == filesep);
checkT1T2 = data.import.path(ind(end)+1:end);
if strcmp(checkT1T2,'t1test')
    in.T1T2 = 'T1';
elseif strcmp(checkT1T2,'T1auto')
    in.T1T2 = 'T1';
elseif strcmp(checkT1T2,'cpmgfastautotest')
    in.T1T2 = 'T2';
elseif strcmp(checkT1T2,'cpmgfastauto')
    in.T1T2 = 'T2';
else
    helpdlg('No original data folder','onMenuImport: No data.');
end
% now ask for stacking
answer = questdlg('Do you want to stack the slices?');
switch answer
    case 'Yes'
        doSliceStack = true;
        % if stacking ask for stack-rotate-order
        answer = questdlg('Select stack-rotate-order:',...
            'Select order', ...
            'stack-rotate (default)','rotate-stack','Cancel','stack-rotate (default)');
        switch answer
            case 'stack-rotate'
                StackFirst = true;
            case 'rotate-stack'
                StackFirst = false;
            otherwise
                StackFirst = true;
        end
    otherwise
        doSliceStack = false;
end
fnames = struct;
% shownames is just a dummy to hold all data file names that
% will be shown in the listbox
shownames = cell(1,1);
c = 0;
if ~isempty(indx)
    for i = indx
        in.path = fullfile(data.import.path,subdirs(i).name);
        in.fileformat = data.import.fileformat;
        out = LoadNMRData_driver(in);
        if doSliceStack
            % the individual file names
            c = c + 1;
            fnames(c).parfile = 'acq.par';
            fnames(c).datafile = out.nmrData{1}.datfile;
            shownames{c} = [in.T1T2,'_',subdirs(i).name];
            % use the meta data from the first slice
            % fix the time scale from [ms] to [s]
            if max(out.nmrData{1}.time) > 100
                out.nmrData{1}.time = out.nmrData{1}.time/1000;
                out.nmrData{1}.raw.time = out.nmrData{1}.raw.time/1000;
            end
            % import into GUI data struct
            data.import.NMR.data{c} = out.nmrData{1};
            % stacking
            for j = 1:size(out.nmrData,2)
                if j == 1
                    signal = out.nmrData{j}.signal;
                else
                    signal = signal + out.nmrData{j}.signal;
                end
            end
            signal = signal./size(out.nmrData,2);
            % now rotate after the stacking
            if StackFirst
                [signal,phase] = rotateT2phase(signal);
                data.import.NMR.data{c}.phase = phase;
                data.import.NMR.data{c}.signal = signal;
                data.import.NMR.data{c}.raw.signal = signal;
            else
                % no rotation after stacking
                data.import.NMR.data{c}.signal = signal;
                data.import.NMR.data{c}.raw.signal = signal;
            end
            % parameter data
            data.import.NMR.para{c} = out.parData;
        else
            for j = 1:size(out.nmrData,2)
                % the individual file names
                c = c + 1;
                fnames(c).parfile = 'acq.par';
                fnames(c).datafile = out.nmrData{j}.datfile;
                shownames{c} = [in.T1T2,'_',subdirs(i).name,'_',fnames(c).datafile];
                % the NMR data
                % here we fix the time scale from [ms] to [s]
                if max(out.nmrData{j}.time) > 100
                    out.nmrData{j}.time = out.nmrData{j}.time/1000;
                    out.nmrData{j}.raw.time = out.nmrData{j}.raw.time/1000;
                end
                data.import.NMR.data{c} = out.nmrData{j};
                data.import.NMR.para{c} = out.parData;
            end
        end
    end
else
    helpdlg('No data folders in the given directory.','onMenuImport: No data.');
end
% update the global data structure
data.import.NMR.files = fnames;
data.import.NMR.filesShort = shownames;
end
%%
function [data,gui] = importDataBGRMouseT1T2(data,gui)
% first ask the user if it is a series of T1 measurements or one T1T2map
answer = questdlg('Is this a series of T1 measurements or one T1-T2 map?', ...
    'Mouse T1T2 import','T1 series','T1-T2 map','T1-T2 map');
switch answer
    case 'T1 series'
        is_T1 = true;
    case 'T1-T2 map'
        is_T1 = false;
    otherwise
        is_T1 = false;
end
% there should be some folders with names ...
% ... similar to the data filenames inside them
datpath = dir(data.import.path);
datpath = datpath(~ismember({datpath.name},{'.','..'}));
fnames = struct;
% shownames is just a dummy to hold all data file names that
% will be shown in the listbox
shownames = cell(1,1);
% ask the user for the amount of T2 echoes to sum for the T1 curve
prompt = {'Enter T2 #echos for one T1 point'};
dlgtitle = 'How many T2 echos';
fieldsize = [1 45];
if is_T1
    definput = {'30'};
else
    definput = {'3'};
end
answer = inputdlg(prompt,dlgtitle,fieldsize,definput);
Nechos = str2double(answer{1});
if is_T1
    % load a series of T1-T2 data and extract only the T1 curves
    c = 0;
    if ~isempty(datpath)
        content = datpath;
        for j = 1:size(content,1)
            in.T1T2 = 'T2';
            in.name = 'data2D.dat';
            in.path = fullfile(data.import.path,content(j).name);
            in.fileformat = data.import.fileformat;
            in.importflag = 'T1';
            in.Nechos = Nechos;
            out = LoadNMRData_driver(in);
            for j1 = 1:numel(out.nmrData)
                % the individual file names
                c = c + 1;
                fnames(c).parfile = 'acqu.par';
                fnames(c).datafile = out.nmrData{j1}.datfile;
                fnames(c).T2specfile = '';
                shownames{c} = ['T1_',content(j).name];
                data.import.NMR.data{c} = out.nmrData{j1};
                data.import.NMR.para{c} = out.parData;
            end
        end
    end
else
    % load a single T1-T2 data set
    c = 0;
    if ~isempty(datpath)
        content = datpath;
        for j = 1:size(content,1)
            if strcmp(content(j).name,'data2D.dat')
                in.T1T2 = 'T2';
                in.name = content(j).name;
                in.path = fullfile(data.import.path);
                in.fileformat = data.import.fileformat;
                in.importflag = 'T1T2map';
                out = LoadNMRData_driver(in);
                for j1 = 1:numel(out.nmrData)
                    % the individual file names
                    c = c + 1;
                    fnames(c).parfile = 'acqu.par';
                    fnames(c).datafile = out.nmrData{j1}.datfile;
                    fnames(c).T2specfile = '';
                    shownames{c} = ['T2_',content(j).name,'_',sprintf('%03d',j1)];
                    data.import.NMR.data{c} = out.nmrData{j1};
                    data.import.NMR.para{c} = out.parData;
                end
            end
        end
        % save the recovery time vector for later use
        t_recov = out.parData.T1Axis;
        t2 = out.parData.T2Axis;
        t2N = numel(t2);
        data.import.T1T2map.t_recov = t_recov(:);
        data.import.T1T2map.t1N = numel(t_recov);
        data.import.T1T2map.t2 = t2;
        data.import.T1T2map.t2N = t2N;
        % add the stacked signal to the data
        flag = 'T1';
        time = data.import.T1T2map.t_recov;
        signal = zeros(numel(data.import.NMR.data),1);
        for i1 = 1:numel(data.import.NMR.data)
            signal(i1) = mean(real(data.import.NMR.data{i1}.signal(1:Nechos)));
        end
        disp('NUCLUESinv import: Estimating noise from exponential fit ...');
        param.T1IRfac = 1;
        param.noise = 0;
        param.optim = 'off';
        param.Tfixed_bool = [0 0 0 0 0];
        param.Tfixed_val = [0 0 0 0 0];
        for i1 = 1:5
            invstd = fitDataFree(time,signal,flag,param,i1);
            if i1 == 1
                noise = invstd.rms;
            else
                noise = min([noise invstd.rms]);
            end
        end
        disp('NUCLUESinv import: done.')
        % finally create a new "import" data set
        data_new = data.import.NMR.data(1);
        para_new = data.import.NMR.para(1);
        data_new{1}.flag = flag;
        data_new{1}.T1IRfac = param.T1IRfac;
        data_new{1}.time = time;
        data_new{1}.signal = signal;
        data_new{1}.noise = noise;
        data_new{1}.raw.time = time;
        data_new{1}.raw.signal = signal;
        data.import.NMR.data{c+1} = data_new{1};
        data.import.NMR.para{c+1} = para_new{1};
        fnames(c+1).datafile = 'T1_merged.dat';
        shownames{c+1} = 'T1_merged';
        % set global echo time
        data.inv2D.prop.te = data.import.NMR.para{1}.echoTime/1e6; % [s]
        % set T1 SR/IR factor
        data.inv2D.inv.T1IRfac = 1; % PM25 Mouse does SR
    end
end
% update the global data structure
data.import.NMR.files = fnames;
data.import.NMR.filesShort = shownames;
end
%%
function [data,gui] = importDataHeliosCPMG(data,gui)
% first check the subpaths
% there should be some folders with names ...
% ... similar to the data filenames inside them
datpath = dir(data.import.path);
datpath = datpath(~ismember({datpath.name},{'.','..'}));
fnames = struct;
% shownames is just a dummy to hold all data file names that
% will be shown in the listbox
shownames = cell(1,1);
c = 0;
if ~isempty(datpath)
    for i = 1:size(datpath,1)
        % does datpath.name points to a folder?
        if datpath(i).isdir
            % check if datpath.name includes regular Helios data files
            content = dir([data.import.path,filesep,datpath(i).name]);
            content = content(~ismember({content.name},{'.','..'}));
            % only keep hrd-files
            content = content(contains({content.name},'.hrd'));
            % remove reference hrd-files
            content = content(~contains({content.name},'_ref.hrd'));
            for j = 1:size(content,1)
                in.T1T2 = 'T2';
                in.name = content(j).name;
                in.path = fullfile(data.import.path,filesep,datpath(i).name);
                in.fileformat = data.import.fileformat;
                out = LoadNMRData_driver(in);
                % the individual file names
                c = c + 1;
                fnames(c).parfile = '';
                fnames(c).datafile = out.nmrData.datfile;
                fnames(c).T2specfile = '';
                shownames{c} = ['T2_',datpath(i).name];
                data.import.NMR.data{c} = out.nmrData;
                data.import.NMR.para{c} = out.parData;
            end
        end
    end
end
% update the global data structure
data.import.NMR.files = fnames;
data.import.NMR.filesShort = shownames;
end
%%
function [data,gui] = importDataHeliosSeries(data,gui)
% first ask the user if it is pure T2 data or T2 data belonging to a T1
% measurement to generate T1-T2 maps
answer = questdlg('Is this series a T1 measurement or pure T2?', ...
    'HELIOS import', ...
    'T1','T2','T2');
switch answer
    case 'T1'
        is_T1 = true;
    case 'T2'
        is_T1 = false;
    otherwise
        is_T1 = false;
end
% now ask for manualS stacking (only for T2 data)
if ~is_T1
    answer = questdlg('Do you want to stack several files?','Stack Dialog','No');
    switch answer
        case 'Yes'
            doStack = true;
            prompt = {'Enter No. of files to stack together'};
            dlgtitle = 'Stack Value';
            fieldsize = [1 40];
            definput = {'16'};
            answer2 = inputdlg(prompt,dlgtitle,fieldsize,definput);
            if ~isempty(answer2)
                nstacks = str2double(answer2{1,1});
            else
                doStack = false;
            end
        otherwise
            doStack = false;
    end
end
% now check the subpaths
% there should be some folders with names ...
% ... similar to the data filenames inside them
datpath = dir(data.import.path);
datpath = datpath(~ismember({datpath.name},{'.','..'}));
% remove any subfolder within the data directory
datpath = datpath(~ismember([datpath.isdir],true));
% only keep hrd-files
datpath = datpath(contains({datpath.name},'.hrd'));
% remove reference hrd-files
datpath = datpath(~contains({datpath.name},'_ref.hrd'));
% remove duplicate hrd-files
datpath = datpath(~contains({datpath.name},'.dup'));
fnames = struct;
% shownames is just a dummy to hold all data file names that
% will be shown in the listbox
shownames = cell(1,1);
c = 0;
if ~isempty(datpath)
    content = datpath;
    if is_T1
        t_recov = zeros(floor(numel(content)/2),2);
    end
    for j = 1:size(content,1)
        in.T1T2 = 'T2';
        in.name = content(j).name;
        in.path = fullfile(data.import.path);
        in.fileformat = data.import.fileformat;
        out = LoadNMRData_driver(in);
        % the individual file names
        c = c + 1;
        fnames(c).parfile = '';
        fnames(c).datafile = out.nmrData.datfile;
        fnames(c).T2specfile = '';
        if is_T1
            shownames{c} = content(j).name;
        else
            shownames{c} = ['T2_',content(j).name];
        end
        data.import.NMR.data{c} = out.nmrData;
        data.import.NMR.para{c} = out.parData;
        % collect recovery times in case of T1 data set
        if is_T1
            t_recov(c,1) = out.parData.t_recov;
            t_recov(c,2) = out.nmrData.phase;
        end
    end
    % in case of T1 data, use the phase of the signal with the longest
    % recovery time to rotate the other signals
    if is_T1
        phase = t_recov(t_recov(:,1)==max(t_recov(:,1)),2);
        for i1 = 1:numel(data.import.NMR.data)
            % the original raw data
            s = data.import.NMR.data{i1}.raw.signal;
            s =  s * exp(1i*(-data.import.NMR.data{i1}.phase));
            % s_rot is the rotated signal
            s_rot = s .* exp(1i*phase);
            % write the rotated signal back to the data struct
            data.import.NMR.data{i1}.signal = s_rot;
            data.import.NMR.data{i1}.phase = phase;
            % get the shortest T2 signal length
            if i1 == 1
                t2N = numel(data.import.NMR.data{i1}.raw.time);
            else
                t2N = min([t2N numel(data.import.NMR.data{i1}.raw.time)]);
            end
            t2 = data.import.NMR.data{i1}.raw.time(1:t2N);
        end
        % for convenience, sort the data by recovery time
        [t_s,ix] = sort(t_recov(:,1));
        data.import.NMR.data = data.import.NMR.data(ix);
1000         data.import.NMR.para = data.import.NMR.para(ix);
1001         fnames = fnames(ix);
1002         shownames = shownames(ix);
1003
1004         % save the recovery time vector for later use
1005         data.import.T1T2map.t_recov = t_s(:,1)/1000;
1006         data.import.T1T2map.t1N = numel(data.import.T1T2map.t_recov);
1007         data.import.T1T2map.t2 = t2;
1008         data.import.T1T2map.t2N = t2N;
1009
1010         % ask if the single measurements should be "stacked" to one T1
1011         % curve
1012         answer = questdlg('Do you want a single T1 curve or a T1-T2 map?', ...
1013             'HELIOS import', ...
1014             'single T1','T1-T2 map','T1-T2 map');
1015         switch answer
1016             case 'single T1'
1017                 singleT1 = true;
1018             case 'T1-T2 map'
1019                 singleT1 = false;
1020         end
1021
1022         if singleT1
1023             % ask how many T2-echos should be stacked together to one T1
1024             % point
1025             prompt = {'Enter T2 #echos for one T1 point'};
1026             dlgtitle = 'How many T2 echos';
1027             fieldsize = [1 45];
1028             definput = {'3'};
1029             answer = inputdlg(prompt,dlgtitle,fieldsize,definput);
1030             Nechos = str2double(answer{1});
1031
1032             flag = 'T1';
1033             time = data.import.T1T2map.t_recov;
1034             signal = zeros(numel(data.import.NMR.data),1);
1035             for i1 = 1:numel(data.import.NMR.data)
1036                 signal(i1) = mean(real(data.import.NMR.data{i1}.signal(1:Nechos)));
1037             end
1038
1039             disp('NUCLUESinv import: Estimating noise from exponential fit ...');
1040             param.T1IRfac = 2;
1041             param.noise = 0;
1042             param.optim = data.info.has_optim;
1043             param.Tfixed_bool = [0 0 0 0 0];
1044             param.Tfixed_val = [0 0 0 0 0];
1045             for i1 = 1:5
1046                 invstd = fitDataFree(time,signal,flag,param,i1);
1047                 if i1 == 1
1048                     noise = invstd.rms;
1049                 else
1050                     noise = min([noise invstd.rms]);
1051                 end
1052             end
1053             disp('NUCLUESinv import: done.')
1054
1055             % finally create a new "import" data set
1056             data_new = data.import.NMR.data(1);
1057             para_new = data.import.NMR.para(1);
1058             % remove the 2D data
1059             data.import = rmfield(data.import,'T1T2map');
1060
1061             data_new{1}.flag = flag;
1062             data_new{1}.T1IRfac = param.T1IRfac;
1063             data_new{1}.time = time;
1064             data_new{1}.signal = signal;
1065             data_new{1}.noise = noise;
1066             data_new{1}.raw.time = time;
1067             data_new{1}.raw.signal = signal;
1068
1069             % use the last sub folder as name
1070             pn = regexp(datpath(1).folder, filesep, 'split');
1071
1072             fnames = fnames(1);
1073             shownames = shownames(1);
1074             shownames{1} = [pn{end},'_T1_merged'];
1075
1076             data.import.NMR.data = data_new;
1077             data.import.NMR.para = para_new;
1078         else
1079             prompt = {'Enter T2 #echos for one T1 point for the merged T1 curve'};
1080             dlgtitle = 'How many T2 echos';
1081             fieldsize = [1 45];
1082             definput = {'3'};
1083             answer = inputdlg(prompt,dlgtitle,fieldsize,definput);
1084             Nechos = str2double(answer{1});
1085
1086             % add the stacked signal to the data
1087             flag = 'T1';
1088             time = data.import.T1T2map.t_recov;
1089             signal = zeros(numel(data.import.NMR.data),1);
1090             for i1 = 1:numel(data.import.NMR.data)
1091                 signal(i1) = mean(real(data.import.NMR.data{i1}.signal(1:Nechos)));
1092             end
1093
1094             disp('NUCLUESinv import: Estimating noise from exponential fit ...');
1095             param.T1IRfac = 2;
1096             param.noise = 0;
1097             param.optim = 'off';
1098             param.Tfixed_bool = [0 0 0 0 0];
1099             param.Tfixed_val = [0 0 0 0 0];
1100             for i1 = 1:5
1101                 invstd = fitDataFree(time,signal,flag,param,i1);
1102                 if i1 == 1
1103                     noise = invstd.rms;
1104                 else
1105                     noise = min([noise invstd.rms]);
1106                 end
1107             end
1108             disp('NUCLUESinv import: done.')
1109
1110             % finally create a new "import" data set
1111             data_new = data.import.NMR.data(1);
1112             para_new = data.import.NMR.para(1);
1113
1114             data_new{1}.flag = flag;
1115             data_new{1}.T1IRfac = param.T1IRfac;
1116             data_new{1}.time = time;
1117             data_new{1}.signal = signal;
1118             data_new{1}.noise = noise;
1119             data_new{1}.raw.time = time;
1120             data_new{1}.raw.signal = signal;
1121
1122             data.import.NMR.data{numel(t_s)+1} = data_new{1};
1123             data.import.NMR.para{numel(t_s)+1} = para_new{1};
1124             fnames(numel(t_s)+1).datafile = 'T1_merged.dat';
1125             shownames{numel(t_s)+1} = 'T1_merged';
1126             % set global echo time
1127             data.inv2D.prop.te = data.import.NMR.para{1}.t_echo;
1128             % set T1 SR/IR factor
1129             data.inv2D.inv.T1IRfac = 2; % Helios default
1130         end
1131     else % pure T2 data
1132         % do restacking if desired
1133         if doStack
1134             % before stacking, sort the data by date (time)
1135             N = length(shownames);
1136             time = zeros(N,1);
1137             for i = 1:N
1138                 time(i,1) = data.import.NMR.data{i}.datenum;
1139             end
1140             [~,ix] = sort(time);
1141             % now apply changes - resort the imported data
1142             data.import.NMR.data = {data.import.NMR.data{ix'}}; %#ok<*CCAT1>
1143             data.import.NMR.para = {data.import.NMR.para{ix'}};
1144             fnames = fnames(ix);
1145             shownames = {shownames{ix'}};
1146
1147             c = 0;
1148             % prepare data variables
1149             datanew = cell(1,1);
1150             paranew = cell(1,1);
1151             fnamesnew = fnames(1);
1152             shownamesnew = cell(1,1);
1153             tmp_signal = zeros(size(data.import.NMR.data{1}.signal));
1154             % loop over all already imported files
1155             for i1 = 1:numel(fnames)
1156                 % stack up files
1157                 tmp_signal = tmp_signal + data.import.NMR.data{i1}.signal;
1158                 % check if stack count is reached
1159                 if mod(i1,nstacks)==0
1160                     % current stack has finished
1161                     c = c + 1;
1162                     % save data
1163                     datanew{c} = data.import.NMR.data{i1};
1164                     datanew{c}.signal = tmp_signal./nstacks;
1165                     datanew{c}.raw.signal = tmp_signal./nstacks;
1166
1167                     paranew{c} = data.import.NMR.para{i1};
1168                     paranew{c}.Nscans = paranew{c}.Nscans*nstacks;
1169                     paranew{c}.all{1,1}{6} = ['Nscans = ',num2str(paranew{c}.Nscans)];
1170
1171                     fnamesnew(c) = fnames(i1);
1172                     shownamesnew{c} = [shownames{i1},'_',num2str(nstacks)];
1173
1174                     % reset the tmp_signal to zero
1175                     tmp_signal = zeros(size(data.import.NMR.data{1}.signal));
1176                 end
1177             end
1178             data.import.NMR.data = datanew;
1179             data.import.NMR.para = paranew;
1180
1181             fnames = fnamesnew;
1182             shownames = shownamesnew;
1183         end
1184     end
1185 end
1186
1187 % update the global data structure
1188 data.import.NMR.files = fnames;
1189 data.import.NMR.filesShort = shownames;
1190
1191 end
1192
1193 %%
1194 function [data,gui] = importDataDartSeries(data,gui)
1195
1196 % first ask the user if it is pure T2 data or T2 data belonging to a T1
1197 % measurement to generate a T1 signal or a T1-T2 map
1198 answer = questdlg('What kind of data you want to import?', ...
1199     'DART import', ...
1200     'single T1','T1-T2 map','T2 (log)','T2 (log)');
1201 switch answer
1202     case 'single T1'
1203         is_T1 = true;
1204         singleT1 = true;
1205     case 'T1-T2 map'
1206         is_T1 = true;
1207         singleT1 = false;
1208     otherwise
1209         is_T1 = false;
1210         singleT1 = false;
1211 end
1212
1213 % now check the subpaths
1214 % there should be some folders with names ...
1215 % ... similar to the data filenames inside them
1216 datpath = dir(data.import.path);
1217 datpath = datpath(~ismember({datpath.name},{'.','..'}));
1218 % remove any subfolder within the data directory
1219 datpath = datpath(~ismember([datpath.isdir],true));
1220
1221 fnames = struct;
1222 % shownames is just a dummy to hold all data file names that
1223 % will be shown in the listbox
1224 shownames = cell(1,1);
1225
1226 useburst = 0;
1227 stackfreq = 1;
1228 c = 0;
1229 if ~isempty(datpath)
1230     content = datpath;
1231     if is_T1
1232         t_recov = zeros(1,2);
1233     else
1234         depth = zeros(1,1);
1235     end
1236     for j = 1:size(content,1)
1237         if strcmp(content(j).name(end-3:end),'.jrd')
1238             c = c + 1;
1239
1240             in.T1T2 = 'T2';
1241             in.name = content(j).name;
1242             in.path = fullfile(data.import.path);
1243             in.fileformat = data.import.fileformat;
1244             in.version = 4;
1245             out = LoadNMRData_driver(in);
1246
1247             % ask for burst usage and frequency stacking
1248             if c == 1 & out.hasburst == 1
1249                 answer = questdlg('Do you want to use the burst?', ...
1250                 'DART import', ...
1251                 'Yes','No','Yes');
1252                 switch answer
1253                     case 'Yes'
1254                         useburst = 1;
1255                     otherwise
1256                         useburst = 0;
1257                 end
1258             end
1259             if c == 1 & out.Nfreq > 1
1260                 answer = questdlg('Do you want to stack frequencies?', ...
1261                 'DART import', ...
1262                 'F1 only','F2 only','F1+F2','F1+F2');
1263                 switch answer
1264                     case 'F1 only'
1265                         stackfreq = 1;
1266                     case 'F2 only'
1267                         stackfreq = 2;
1268                     case 'F1+F2'
1269                         stackfreq = 3;
1270                 end
1271             end
1272
1273             if useburst
1274                 for i1 = 1:numel(out.nmrData)/2
1275                     sig = real(out.nmrData{i1}.signal);
1276                     burst = real(out.nmrData{i1+out.Nfreq}.signal);
1277
1278                     burst_echoes = out.parData{i1+out.Nfreq}.n_echo;
1279                     ms = mean(sig(2:burst_echoes));
1280                     mb = mean(burst(2:burst_echoes));
1281
1282                     burst_shift = complex(burst+(ms-mb),imag(out.nmrData{i1+out.Nfreq}.signal));
1283                     out.nmrData{i1}.signal(1:burst_echoes) = burst_shift;
1284                     out.nmrData{i1}.raw.signal = out.nmrData{i1}.signal;
1285                 end
1286             end
1287
1288             if stackfreq == 1
1289                 fnames(c).parfile = '';
1290                 fnames(c).datafile = out.nmrData{1}.datfile;
1291                 fnames(c).T2specfile = '';
1292                 shownames{c} = content(j).name;
1293                 data.import.NMR.data{c} = out.nmrData{1};
1294                 data.import.NMR.para{c} = out.parData{1};
1295
1296             elseif stackfreq == 2
1297                 fnames(c).parfile = '';
1298                 fnames(c).datafile = out.nmrData{2}.datfile;
1299                 fnames(c).T2specfile = '';
1300                 shownames{c} = content(j).name;
1301                 data.import.NMR.data{c} = out.nmrData{2};
1302                 data.import.NMR.para{c} = out.parData{2};
1303
1304             elseif stackfreq == 3
1305                 fnames(c).parfile = '';
1306                 fnames(c).datafile = out.nmrData{1}.datfile;
1307                 fnames(c).T2specfile = '';
1308                 shownames{c} = content(j).name;
1309
1310                 tmp1 = out.nmrData{1};
1311                 tmp2 = out.nmrData{2};
1312                 signal = (tmp1.signal + tmp2.signal)./2;
1313
1314                 out.nmrData{1}.signal = signal;
1315                 out.nmrData{1}.raw.signal = signal;
1316                 data.import.NMR.data{c} = out.nmrData{1};
1317                 data.import.NMR.para{c} = out.parData{1};
1318             end
1319
1320             % collect recovery times in case of T1 data set
1321             if is_T1
1322                 t_recov(c,1) = out.parData{1}.t_recov;
1323                 t_recov(c,2) = out.nmrData{1}.phase;
1324             else
1325                 % try to collect depth values
1326                 depth(c,1) = data.import.NMR.para{c}.depth;
1327             end
1328         end
1329     end
1330
1331     % in case if T1 data, use the phase of the signal with the longest
1332     % recovery time to rotate the other signals
1333     if is_T1
1334         phase = t_recov(t_recov(:,1)==max(t_recov(:,1)),2);
1335         for i1 = 1:numel(data.import.NMR.data)
1336             % the original raw data
1337             s = data.import.NMR.data{i1}.raw.signal;
1338             % s_rot is the rotated signal
1339             s_rot = s .* exp(1i*phase);
1340             % write the rotated signal back to the data struct
1341             data.import.NMR.data{i1}.signal = s_rot;
1342             data.import.NMR.data{i1}.phase = phase;
1343
1344             % get the shortest T2 signal length
1345             if i1 == 1
1346                 t2N = numel(data.import.NMR.data{i1}.raw.time);
1347             else
1348                 t2N = min([t2N numel(data.import.NMR.data{i1}.raw.time)]);
1349             end
1350             t2 = data.import.NMR.data{i1}.raw.time(1:t2N);
1351         end
1352
1353         % for convenience, sort the data by recovery time
1354         [t_s,ix] = sort(t_recov(:,1));
1355         data.import.NMR.data = data.import.NMR.data(ix);
1356         data.import.NMR.para = data.import.NMR.para(ix);
1357         fnames = fnames(ix);
1358         shownames = shownames(ix);
1359
1360         % save the recovery time vector for later use
1361         data.import.T1T2map.t_recov = t_s(:,1)/1000;
1362         data.import.T1T2map.t1N = numel(data.import.T1T2map.t_recov);
1363         data.import.T1T2map.t2 = t2;
1364         data.import.T1T2map.t2N = t2N;
1365
1366         % ask how many T2-echos should be stacked together to one T1
1367         % point
1368         prompt = {'Enter T2 #echos for one T1 point for the merged T1 curve'};
1369         dlgtitle = 'How many T2 echos';
1370         fieldsize = [1 45];
1371         definput = {'3'};
1372         answer = inputdlg(prompt,dlgtitle,fieldsize,definput);
1373         Nechos = str2double(answer{1});
1374
1375         flag = 'T1';
1376         time = data.import.T1T2map.t_recov;
1377         signal = zeros(numel(data.import.NMR.data),1);
1378         for i1 = 1:numel(data.import.NMR.data)
1379             signal(i1) = mean(real(data.import.NMR.data{i1}.signal(1:Nechos)));
1380         end
1381
1382         disp('NUCLUESinv import: Estimating noise from exponential fit ...');
1383         param.T1IRfac = 1;
1384         param.noise = 0;
1385         param.optim = 'off';
1386         param.Tfixed_bool = [0 0 0 0 0];
1387         param.Tfixed_val = [0 0 0 0 0];
1388         for i1 = 1:5
1389             invstd = fitDataFree(time,signal,flag,param,i1);
1390             if i1 == 1
1391                 noise = invstd.rms;
1392             else
1393                 noise = min([noise invstd.rms]);
1394             end
1395         end
1396         disp('NUCLUESinv import: done.')
1397
1398         if singleT1
1399             % finally create a new "import" data set
1400             data_new = data.import.NMR.data(1);
1401             para_new = data.import.NMR.para(1);
1402             data.import = rmfield(data.import,'T1T2map');
1403
1404             data_new{1}.flag = flag;
1405             data_new{1}.T1IRfac = param.T1IRfac;
1406             data_new{1}.time = time;
1407             data_new{1}.signal = signal;
1408             data_new{1}.noise = noise;
1409             data_new{1}.raw.time = time;
1410             data_new{1}.raw.signal = signal;
1411
1412             fnames = fnames(1);
1413             shownames = {'T1_merged'};
1414
1415             data.import.NMR.data = data_new;
1416             data.import.NMR.para = para_new;
1417         else
1418             % finally create a new "import" data set
1419             data_new = data.import.NMR.data(1);
1420             para_new = data.import.NMR.para(1);
1421
1422             data_new{1}.flag = flag;
1423             data_new{1}.T1IRfac = param.T1IRfac;
1424             data_new{1}.time = time;
1425             data_new{1}.signal = signal;
1426             data_new{1}.noise = noise;
1427             data_new{1}.raw.time = time;
1428             data_new{1}.raw.signal = signal;
1429
1430             data.import.NMR.data{numel(t_s)+1} = data_new{1};
1431             data.import.NMR.para{numel(t_s)+1} = para_new{1};
1432             fnames(numel(t_s)+1).datafile = 'T1_merged.dat';
1433             shownames{numel(t_s)+1} = 'T1_merged';
1434             % set global echo time
1435             data.inv2D.prop.te = data.import.NMR.para{1}.t_echo;
1436             % set T1 SR/IR factor
1437             data.inv2D.inv.T1IRfac = 1; % Dart default
1438         end
1439     else
1440         % T2 data
1441         data.import.BAM.use_z = true;
1442         data.import.BAM.z_unit = 'm';
1443         data.import.BAM.zslice = depth - data.import.NMR.para{1}.stick_up_height;
1444         for i1 = 1:numel(shownames)
1445             tmp = shownames{i1};
1446             shownames{i1} = ['z:',sprintf('%05.2f',depth(i1)),'m ',tmp];
1447         end
1448     end
1449 end
1450
1451 % update the global data structure
1452 data.import.NMR.files = fnames;
1453 data.import.NMR.filesShort = shownames;
1454
1455 end
1456
1457 %%
1458 function [data,gui] = importDataDart(data,gui)
1459
1460 in.path = fullfile(data.import.path);
1461 in.name = data.import.file;
1462 in.fileformat = data.import.fileformat;
1463 in.version = data.import.version;
1464 out = LoadNMRData_driver(in);
1465
1466 fnames = struct;
1467 % shownames is just a dummy to hold all data file names that
1468 % will be shown in the listbox
1469 shownames = cell(1,1);
1470
1471 c = 0;
1472 for j = 1:size(out.nmrData,2)
1473     % the individual file names
1474     c = c + 1;
1475     fnames(c).parfile = '';
1476     fnames(c).datafile = data.import.file;
1477     fnames(c).T2specfile = '';
1478
1479     shownames{c} = ['depth_',sprintf('%04.3f',out.parData{j}.depth)];
1480
1481     % the NMR data
1482     % here we fix the time scale from [ms] to [s]
1483     if max(out.nmrData{j}.time) > 100
1484         out.nmrData{j}.time = out.nmrData{j}.time/1000;
1485         out.nmrData{j}.raw.time = out.nmrData{j}.raw.time/1000;
1486     end
1487     data.import.NMR.data{c} = out.nmrData{j};
1488     data.import.NMR.para{c} = out.parData{j};
1489 end
1490
1491 % update the global data structure
1492 data.import.NMR.files = fnames;
1493 data.import.NMR.filesShort = shownames;
1494
1495 end
1496
1497 %%
1498 function [data,gui] = importDataRoCAT1T2(data,gui)
1499
1500 % there should be some folders with names ...
1501 % ... similar to the data filenames inside them
1502 datpath = dir(data.import.path);
1503 datpath = datpath(~ismember({datpath.name},{'.','..'}));
1504 % remove any subfolder within the data directory
1505 datpath = datpath(~ismember([datpath.isdir],true));
1506
1507 fnames = struct;
1508 % shownames is just a dummy to hold all data file names that
1509 % will be shown in the listbox
1510 shownames = cell(1,1);
1511
1512 c = 0;
1513 if ~isempty(datpath)
1514     content = datpath;
1515     for j = 1:size(content,1)
1516         if strcmp(content(j).name,'data2.csv')
1517             in.T1T2 = 'T2';
1518             in.name = content(j).name;
1519             in.path = fullfile(data.import.path);
1520             in.fileformat = data.import.fileformat;
1521             out = LoadNMRData_driver(in);
1522
1523             for j1 = 1:numel(out.nmrData)
1524                 % the individual file names
1525                 c = c + 1;
1526                 fnames(c).parfile = 'acqu.par';
1527                 fnames(c).datafile = out.nmrData{j1}.datfile;
1528                 fnames(c).T2specfile = '';
1529
1530                 shownames{c} = ['T2_',content(j).name,'_',sprintf('%03d',j1)];
1531
1532                 data.import.NMR.data{c} = out.nmrData{j1};
1533                 data.import.NMR.para{c} = out.parData;
1534             end
1535         end
1536     end
1537
1538     % save the recovery time vector for later use
1539     t2 = data.import.NMR.data{1}.time;
1540     t2N = numel(t2);
1541     t_recov = logspace(log10(out.parData.minTau),log10(out.parData.maxTau),out.parData.tauSteps);
1542     data.import.T1T2map.t_recov = t_recov(:)./1e3; % to [s]
1543     data.import.T1T2map.t1N = numel(data.import.T1T2map.t_recov);
1544     data.import.T1T2map.t2 = t2;
1545     data.import.T1T2map.t2N = t2N;
1546
1547     % add the stacked signal to the data
1548     Nechos = 1;
1549     flag = 'T1';
1550     time = data.import.T1T2map.t_recov;
1551     signal = zeros(numel(data.import.NMR.data),1);
1552     for i1 = 1:numel(data.import.NMR.data)
1553         signal(i1) = mean(real(data.import.NMR.data{i1}.signal(1:Nechos)));
1554     end
1555
1556     disp('NUCLUESinv import: Estimating noise from exponential fit ...');
1557     param.T1IRfac = 2;
1558     param.noise = 0;
1559     param.optim = 'off';
1560     param.Tfixed_bool = [0 0 0 0 0];
1561     param.Tfixed_val = [0 0 0 0 0];
1562     for i1 = 1:5
1563         invstd = fitDataFree(time,signal,flag,param,i1);
1564         if i1 == 1
1565             noise = invstd.rms;
1566         else
1567             noise = min([noise invstd.rms]);
1568         end
1569     end
1570     disp('NUCLUESinv import: done.')
1571
1572     % finally create a new "import" data set
1573     data_new = data.import.NMR.data(1);
1574     para_new = data.import.NMR.para(1);
1575
1576     data_new{1}.flag = flag;
1577     data_new{1}.T1IRfac = param.T1IRfac;
1578     data_new{1}.time = time;
1579     data_new{1}.signal = signal;
1580     data_new{1}.noise = noise;
1581     data_new{1}.raw.time = time;
1582     data_new{1}.raw.signal = signal;
1583
1584     data.import.NMR.data{c+1} = data_new{1};
1585     data.import.NMR.para{c+1} = para_new{1};
1586     fnames(c+1).datafile = 'T1_merged.dat';
1587     shownames{c+1} = 'T1_merged';
1588     % set global echo time
1589     data.inv2D.prop.te = data.import.NMR.para{1}.echoTime/1e6; % [s]
1590     % set T1 SR/IR factor
1591     data.inv2D.inv.T1IRfac = 2; % Rock Core Analyzer default(?)
1592 end
1593
1594 % update the global data structure
1595 data.import.NMR.files = fnames;
1596 data.import.NMR.filesShort = shownames;
1597 end
1598
1599 %%
1600 function [data,gui] = importDataGeneral(data,gui)
1601
1602 % look for all files ending with '.par'
1603 % should exist for T1 and T2 measurements
1604 filenames = dir(fullfile(data.import.path,'*.par'));
1605
1606 fnames = struct;
1607 % shownames is just a dummy to hold all data file names that
1608 % will be shown in the listbox
1609 shownames = cell(1,1);
1610
1611 % loop over all found files and import the data
1612 c = 0;
1613 in.path = data.import.path;
1614 for i = 1:size(filenames,1)
1615     ind = strfind(filenames(i).name,'.');
1616     ind = max(ind);
1617     in.name = filenames(i).name(1:ind-1);
1618     in.fileformat = data.import.fileformat;
1619     out = LoadNMRData_driver(in);
1620
1621     for j = 1:size(out.nmrData,2)
1622         % the individual file names
1623         c = c + 1;
1624         fnames(c).parfile = filenames(i).name;
1625         fnames(c).datafile = out.nmrData{j}.datfile;
1626         if strcmp(out.nmrData{j}.flag,'T2') && isfield(out.nmrData{j},'specfile')
1627             fnames(c).T2specfile = out.nmrData{j}.specfile;
1628         else
1629             fnames(c).T2specfile = '';
1630         end
1631         shownames{c} = fnames(c).datafile;
1632
1633         % the NMR data
1634         % here we fix the time scale from [ms] to [s]
1635         if max(out.nmrData{j}.time) > 100
1636             out.nmrData{j}.time = out.nmrData{j}.time/1000;
1637             out.nmrData{j}.raw.time = out.nmrData{j}.raw.time/1000;
1638         end
1639         data.import.NMR.data{c} = out.nmrData{j};
1640         data.import.NMR.para{c} = out.parData;
1641     end
1642 end
1643
1644 switch data.import.fileformat
1645     case 'bamtom'
1646         nslices = out.parData.nSlices;
1647         ncsvfiles = numel(fnames);
1648
1649         % check for background file ("Leermessung")
1650         has_bg = false;
1651         for i = 1:numel(fnames)
1652             if ~isempty(strfind(fnames(i).datafile,'000'))
1653                 has_bg = true;
1654                 index_bg = i;
1655                 break;
1656             end
1657         end
1658
1659         if has_bg
1660             % background data set
1661             bg = data.import.NMR.data{index_bg};
1662
1663             % vector of indices of the files that get corrected
1664             ind_files = 1:1:ncsvfiles;
1665             ind_files(ind_files==index_bg) = [];
1666
1667             for i = ind_files
1668                 % subtract the background signal
1669                 s = data.import.NMR.data{i}.signal;
1670                 s_bg = bg.signal;
1671                 % if the background signal is longer than the signal cut it
1672                 if numel(s_bg) > numel(s)
1673                     tmp_s = s_bg(1:numel(s));
1674                 else % if not pad it with zeros
1675                     tmp_s = zeros(size(s));
1676                     tmp_s(1:numel(s_bg)) = s_bg;
1677                 end
1678                 s = complex(real(s)-real(tmp_s),imag(s)-imag(tmp_s));
1679                 % update original data set
1680                 data.import.NMR.data{i}.signal = s;
1681             end
1682
1683             % check if the number of slices is equal to the number of files
1684             % (excluding the background file)
1685             if nslices == numel(ind_files)
1686                 % create z-vector
1687                 p = out.parData;
1688                 zslice = linspace(p.startPos,p.endPos,p.nSlices)';
1689                 data.import.BAM.use_z = true;
1690                 data.import.BAM.zslice = zslice;
1691                 if numel(zslice) > 1
1692                     c = 0;
1693                     for i = ind_files
1694                         c = c + 1;
1695                         tmp = shownames{i};
1696                         shownames{i} = [tmp,' z:',sprintf('%5.4f',zslice(c))];
1697                     end
1698                 end
1699             else
1700                 data.import.BAM.use_z = false;
1701                 data.import.BAM.zslice = 1:1:max([numel(ind_files) 1]);
1702             end
1703         else
1704             if nslices == ncsvfiles
1705                 % create z-vector
1706                 p = out.parData;
1707                 zslice = linspace(p.startPos,p.endPos,p.nSlices)';
1708                 data.import.BAM.use_z = true;
1709                 data.import.BAM.zslice = zslice;
1710                 if numel(zslice) > 1
1711                     for i = 1:numel(zslice)
1712                         tmp = shownames{i};
1713                         shownames{i} = [tmp,' z:',sprintf('%5.4f',zslice(i))];
1714                     end
1715                 end
1716             else
1717                 data.import.BAM.use_z = false;
1718                 data.import.BAM.zslice = 1:1:ncsvfiles;
1719             end
1720         end
1721         data.import.BAM.z_unit = 'm';
1722 end
1723
1724 % update the global data structure
1725 data.import.NMR.files = fnames;
1726 data.import.NMR.filesShort = shownames;
1727
1728 end
1729
1730 %%
1731 function [data,gui] = importDataLIAG(data,gui)
1732
1733 in.path = fullfile(data.import.path);
1734 in.fileformat = data.import.fileformat;
1735 out = LoadNMRData_driver(in);
1736
1737 fnames = struct;
1738 % shownames is just a dummy to hold all data file names that
1739 % will be shown in the listbox
1740 shownames = cell(1,1);
1741
1742 c = 0;
1743 for j = 1:size(out.nmrData,2)
1744     % the individual file names
1745     c = c + 1;
1746     fnames(c).parfile = 'acqu.par';
1747     fnames(c).datafile = out.nmrData{j}.datfile;
1748     fnames(c).T2specfile = '';
1749
1750     shownames{c} = fnames(c).datafile;
1751
1752     % the NMR data
1753     % here we fix the time scale to [s] if neccessary
1754     TE = out.parData.echoTime; % [s]
1755     if out.nmrData{j}.time(1)== TE/1e3
1756         % change [ms] to [s]
1757         out.nmrData{j}.time = out.nmrData{j}.time/1e3;
1758         out.nmrData{j}.raw.time = out.nmrData{j}.raw.time/1e3;
1759     elseif out.nmrData{j}.time(1)== TE
1760         % change [s] to [s] -> very unlikely
1761         out.nmrData{j}.time = out.nmrData{j}.time/1e6;
1762         out.nmrData{j}.raw.time = out.nmrData{j}.raw.time/1e6;
1763     end
1764     data.import.NMR.data{c} = out.nmrData{j};
1765     data.import.NMR.para{c} = out.parData;
1766 end
1767
1768 % update the global data structure
1769 data.import.NMR.files = fnames;
1770 data.import.NMR.filesShort = shownames;
1771
1772 end
1773
1774 %%
1775 function [data,gui] = importDataLIAGcore(data,gui)
1776
1777 % get all subfolders containing a measurement at a certain heigth
1778 subdirs = dir(data.import.path);
1779 % remove the dot-dirs
1780 subdirs = subdirs(~ismember({subdirs.name},{'.','..'}));
1781
1782 % now get the background data ("Leermessung")
1783 bgPath = uigetdir(data.import.path,'Choose Background Data Path');
1784 isbgPath = false;
1785 if bgPath == 0
1786     disp('NUCLEUSinv: LIAG core import: No background file provided.');
1787 else
1788     isbgPath = true;
1789     in.path = fullfile(bgPath);
1790     in.fileformat = data.import.fileformat;
1791     bgout = LoadNMRData_driver(in);
1792     ref1.t = bgout.nmrData{1}.time;
1793     ref1.s = bgout.nmrData{1}.signal;
1794     [ref1.s,~] = rotateT2phase(ref1.s);
1795 end
1796
1797 % get the Position file
1798 [posFile,posFilePath] = uigetfile('*.*','Choose Lift Position File',data.import.path);
1799 isposFile = false;
1800 if posFilePath == 0
1801     disp('NUCLEUSinv: LIAG core import: No position file provided.');
1802 else
1803     isposFile = true;
1804     % import LIAG lift file
1805     buffer = fileread(fullfile(posFilePath,posFile));
1806
1807     % get the time stamps of the lift positions
1808     substr = 'Zeit:' ;
1809     loc = strfind(buffer, substr);
1810     timepoint = cell(1,1);
1811     for i = 1:length(loc)
1812         timestr = strtrim(buffer(loc(i)+numel(substr):loc(i)+numel(substr)+19));
1813         timepoint{i} = datetime(timestr,'InputFormat','dd.MM.yyyy HH:mm:ss');
1814     end
1815     % ignore the first time stamp
1816     t_range = [datenum(timepoint{2}), datenum(timepoint{3})];
1817     % get the z coords
1818     substr = 'Z1=';
1819     loc = strfind(buffer, substr) ;
1820     z_range(1) = sscanf(buffer(loc+numel(substr):loc+numel(substr)+10),'%f',1);
1821     substr = 'Z2=';
1822     loc = strfind(buffer, substr) ;
1823     z_range(2) =  sscanf(buffer(loc+numel(substr):loc+numel(substr)+10),'%f',1);
1824 end
1825
1826 % import the NMR data
1827 count = 0;
1828 levels = zeros(size(subdirs));
1829 nmrDataTMP = cell(1,1);
1830 for i = 1:numel(subdirs)
1831     if ~isnan(str2double(subdirs(i).name))
1832
1833         % import the NMR file
1834         in.path = fullfile(data.import.path,subdirs(i).name,'T2CPMG');
1835         in.fileformat = data.import.fileformat;
1836         out = LoadNMRData_driver(in);
1837
1838         % if there is a position file
1839         if isposFile
1840             % keep only files within the correct time range
1841             if out.nmrData{1}.datenum > t_range(1) && out.nmrData{1}.datenum < t_range(2)
1842                 count = count + 1;
1843                 % interpolate the z position via the time stamp of the NMR file
1844                 levels(count) = interp1(t_range,z_range,out.nmrData{1}.datenum,'linear');
1845                 nmrDataTMP{count} = out;
1846             end
1847         else % just read everything
1848             count = count + 1;
1849             levels(count) = str2double(subdirs(i).name);
1850             nmrDataTMP{count} = out;
1851         end
1852     end
1853 end
1854 % cut off data that is not part of the scan
1855 levels = levels(1:count);
1856 % sort in ascending order
1857 [levels,idx] = sort(levels);
1858
1859 % sort the NMR data accordingly
1860 fnames = struct;
1861 % shownames is just a dummy to hold all data file names that
1862 % will be shown in the listbox
1863 shownames = cell(1,1);
1864 for c = 1:numel(levels)
1865     % the individual file names
1866     fnames(c).parfile = 'acqu.par';
1867     fnames(c).datafile = nmrDataTMP{idx(c)}.nmrData{1}.datfile;
1868     fnames(c).T2specfile = '';
1869
1870     shownames{c} = fnames(c).datafile;
1871     tmp = shownames{c};
1872     if isposFile
1873         shownames{c} = [tmp,': ',sprintf('%4d',floor(levels(c))),'mm'];
1874     else
1875         shownames{c} = [tmp,' level:',sprintf('%d',levels(c))];
1876     end
1877     out = nmrDataTMP{idx(c)};
1878
1879     % the NMR data
1880     % here we fix the time scale to [s] if neccessary
1881     TE = out.parData.echoTime; % [s]
1882     if out.nmrData{1}.time(1) == TE/1e3
1883         % change [ms] to [s]
1884         out.nmrData{1}.time = out.nmrData{1}.time/1e3;
1885         out.nmrData{1}.raw.time = out.nmrData{1}.raw.time/1e3;
1886     elseif out.nmrData{1}.time(1) == TE
1887         % change [s] to [s] -> very unlikely
1888         out.nmrData{1}.time = out.nmrData{1}.time/1e6;
1889         out.nmrData{1}.raw.time = out.nmrData{1}.raw.time/1e6;
1890     end
1891     data.import.NMR.data{c} = out.nmrData{1};
1892     data.import.NMR.para{c} = out.parData;
1893
1894     % subtract the background signal is one is available
1895     if isbgPath
1896         % get the original signal
1897         s = data.import.NMR.data{c}.signal;
1898         % if the background signal is longer than the signal cut it, if
1899         % not extend it with zeros
1900         if numel(ref1.s) > numel(s)
1901             tmp_r = ref1.s(1:numel(s));
1902         else
1903             tmp_r = zeros(size(s));
1904             tmp_r(1:numel(ref1.s)) = ref1.s;
1905         end
1906         s = complex(real(s)-real(tmp_r),imag(s)-imag(tmp_r));
1907
1908         % sign check
1909         if real(s(1:3))<0
1910             s = s*-1;
1911         end
1912
1913         % rotate phase again - TEST
1914         [s,~] = rotateT2phase(s);
1915
1916         % update signal
1917         data.import.NMR.data{c}.signal = s;
1918         data.import.NMR.data{c}.raw.signal = s;
1919     end
1920 end
1921 if isposFile
1922     data.import.LIAGCORE.use_z = true;
1923 else
1924     data.import.LIAGCORE.use_z = false;
1925 end
1926 data.import.LIAGCORE.zslice = levels;
1927
1928 % update the global data structure
1929 data.import.NMR.files = fnames;
1930 data.import.NMR.filesShort = shownames;
1931
1932 end
1933
1934 %%
1935 function [data,gui] = importDataLIAGproject(data,gui)
1936
1937 % 1) show all folders and ask for sample
1938 subdirs = dir(data.import.path);
1939 % remove the dot-dirs
1940 subdirs = subdirs(~ismember({subdirs.name},{'.','..'}));
1941
1942 fnames = {subdirs.name};
1943 [indx,~] = listdlg('PromptString','Select Sample:',...
1944     'SelectionMode','single',...
1945     'ListString',fnames);
1946
1947 if ~isempty(indx)
1948     % 2) check corresponding SampleParameter.par file for reference and
1949     % calibration sample and other parameters
1950     datapath = fullfile(data.import.path,fnames{indx});
1951     % load SampleParameter file for sample
1952     [SampleParameter] = loadGUIParameters(datapath,'SampleParameters.par');
1953     if isfield(SampleParameter,'sampleVolume')
1954         dataVol = SampleParameter.sampleVolume;
1955     else
1956         dataVol = 1;
1957     end
1958
1959     % 2a) background file #1
1960     backgroundFile1 = SampleParameter.backgroundFile;
1961     if isempty(backgroundFile1)
1962         bnames = {subdirs.name};
1963         bnames(indx) = [];
1964         [indb,~] = listdlg('PromptString','Select Background File:',...
1965             'SelectionMode','single',...
1966             'ListString',bnames);
1967         if ~isempty(indb)
1968             backgroundFile1 = bnames{indb};
1969         else
1970             backgroundFile1 = '';
1971         end
1972     end
1973     if ~isempty(backgroundFile1)
1974         ind = strfind(backgroundFile1,filesep);
1975         if ~isempty(ind)
1976             backgroundFile1 = backgroundFile1(ind(end)+1:end);
1977         end
1978         fileInList = ismember(fnames,{backgroundFile1});
1979         if any(fileInList)
1980             backgroundpath1 = fullfile(data.import.path,fnames{fileInList});
1981         end
1982     else
1983         backgroundpath1 = '';
1984         backgroundFile1 = '';
1985     end
1986     backVol = 1;
1987
1988     % 2b) calibration file
1989     c = 0;
1990     if isfield(SampleParameter,'calibrationFile0')
1991         c = c + 1;
1992         calibrationFiles{c} = SampleParameter.calibrationFile0;
1993     end
1994     if isfield(SampleParameter,'calibrationFile1')
1995         c = c + 1;
1996         calibrationFiles{c} = SampleParameter.calibrationFile1;
1997     end
1998     if isfield(SampleParameter,'calibrationFile2')
1999         c = c + 1;
2000         calibrationFiles{c} = SampleParameter.calibrationFile2;
2001     end
2002     if isfield(SampleParameter,'calibrationFile3')
2003         c = c + 1;
2004         calibrationFiles{c} = SampleParameter.calibrationFile3;
2005     end
2006
2007     % find the non-empty one
2008     ind = ismember(calibrationFiles,{''});
2009     % there are three possibilities: 0, 1 and more than 1 calib. files
2010     calibrationFiles(ind) = [];
2011     if isempty(calibrationFiles)
2012         cnames = {subdirs.name};
2013         cnames(indx) = [];
2014         [indc,~] = listdlg('PromptString','Select Calibration File:',...
2015             'SelectionMode','single',...
2016             'ListString',cnames);
2017         if ~isempty(indc)
2018             calibrationFiles = cnames{indc};
2019         else
2020             calibrationFiles = '';
2021         end
2022     else
2023         % if there are more than one let the user select the correct one
2024         if numel(calibrationFiles) > 1
2025             [ind,~] = listdlg('PromptString','Select Calibration File:',...
2026                 'SelectionMode','single',...
2027                 'ListString',calibrationFiles);
2028             calibrationFiles = calibrationFiles{ind};
2029         else
2030             calibrationFiles = calibrationFiles{1};
2031         end
2032     end
2033     if ~isempty(calibrationFiles)
2034         ind = strfind(calibrationFiles,filesep);
2035         if ~isempty(ind)
2036             calibrationFiles = calibrationFiles(ind(end)+1:end);
2037         end
2038         fileInList = ismember(fnames,{calibrationFiles});
2039         if any(fileInList)
2040             calibrationpath = fullfile(data.import.path,fnames{fileInList});
2041         end
2042     else
2043         calibrationpath = '';
2044         calibrationFiles = '';
2045     end
2046
2047     if ~isempty(calibrationpath)
2048         [SampleParameterC] = loadGUIParameters(calibrationpath,'SampleParameters.par');
2049         if isfield(SampleParameterC,'sampleVolume')
2050             calibVol = SampleParameterC.sampleVolume;
2051         else
2052             calibVol = 1;
2053         end
2054
2055         % 2a) background file #2
2056         backgroundFile2 = SampleParameterC.backgroundFile;
2057         if isempty(backgroundFile2)
2058             bnames = {subdirs.name};
2059             bnames(indx) = [];
2060             [indb,~] = listdlg('PromptString','Select Background File for Calibration:',...
2061                 'SelectionMode','single',...
2062                 'ListString',bnames);
2063             if ~isempty(indb)
2064                 backgroundFile2 = bnames{indb};
2065             else
2066                 backgroundFile2 = '';
2067             end
2068         end
2069         if ~isempty(backgroundFile2)
2070             ind = strfind(backgroundFile2,filesep);
2071             if ~isempty(ind)
2072                 backgroundFile2 = backgroundFile2(ind(end)+1:end);
2073             end
2074             fileInList = ismember(fnames,{backgroundFile2});
2075             if any(fileInList)
2076                 backgroundpath2 = fullfile(data.import.path,fnames{fileInList});
2077             end
2078         else
2079             backgroundpath2 = '';
2080             backgroundFile2 = '';
2081         end
2082     else
2083         calibVol = 1;
2084         backgroundpath2 = '';
2085         backgroundFile2 = '';
2086     end
2087
2088     % 3) now load the data
2089     workpaths = {datapath,calibrationpath,backgroundpath1,backgroundpath2};
2090     workfiles = {fnames{indx},[calibrationFiles,' - calibration'],...
2091         [backgroundFile1,' - backgroundS'],[backgroundFile2,' - backgroundC']};
2092     out = cell(size(workpaths));
2093     count = 0;
2094     keep = false(size(workpaths));
2095     for i = 1:numel(workpaths)
2096         if ~isempty(workpaths{i})
2097             workdirs = dir(workpaths{i});
2098             workdirs = workdirs(~ismember({workdirs.name},{'.','..'}));
2099             isT2 = ismember({workdirs.name},{'T2CPMG'});
2100             if any(isT2)
2101                 keep(i) = true;
2102                 count = count + 1;
2103                 T2path = fullfile(workdirs(isT2).folder,workdirs(isT2).name);
2104                 in.path = T2path;
2105                 in.fileformat = data.import.fileformat;
2106                 out{i} = LoadNMRData_driver(in);
2107             end
2108         end
2109     end
2110
2111     if isempty(backgroundpath1)
2112         ref1 = struct;
2113     else
2114         background1 = out{3};
2115         % get the background data 1
2116         ref1.t = background1.nmrData{1}.time;
2117         ref1.s = background1.nmrData{1}.signal;
2118         [ref1.s,~] = rotateT2phase(ref1.s);
2119     end
2120
2121     if isempty(backgroundpath2)
2122         ref2 = struct;
2123     else
2124         background2 = out{4};
2125         % get the background data 2
2126         ref2.t = background2.nmrData{1}.time;
2127         ref2.s = background2.nmrData{1}.signal;
2128         [ref2.s,~] = rotateT2phase(ref2.s);
2129     end
2130
2131     workpaths = workpaths(keep);
2132     workfiles = workfiles(keep);
2133     out = out(keep);
2134
2135     ffnames = struct;
2136     % shownames is just a dummy to hold all data file names that
2137     % will be shown in the listbox
2138     shownames = cell(1,1);
2139
2140     for i = 1:count
2141         ffnames(i).parfile = 'acqu.par';
2142         ffnames(i).datafile = workfiles{i};
2143         ffnames(i).T2specfile = '';
2144
2145         shownames{i} = ffnames(i).datafile;
2146
2147         % the NMR data
2148         % here we fix the time scale to [s] if neccessary
2149         TE = out{i}.parData.echoTime; % [s]
2150         if out{i}.nmrData{1}.time(1)== TE/1e3
2151             % change [ms] to [s]
2152             out{i}.nmrData{1}.time = out{i}.nmrData{1}.time/1e3;
2153             out{i}.nmrData{1}.raw.time = out{i}.nmrData{1}.raw.time/1e3;
2154         elseif out{i}.nmrData{1}.time(1)== TE
2155             % change [s] to [s] -> very unlikely
2156             out{i}.nmrData{1}.time = out{i}.nmrData{1}.time/1e6;
2157             out{i}.nmrData{1}.raw.time = out{i}.nmrData{1}.raw.time/1e6;
2158         end
2159
2160         data.import.NMR.data{i} = out{i}.nmrData{1};
2161         data.import.NMR.para{i} = out{i}.parData;
2162         data.import.NMR.para{i}.SampleParameter = SampleParameter;
2163
2164         % subtract the background signal
2165         s = data.import.NMR.data{i}.signal;
2166         if i==1 && isfield(ref1,'s')
2167             % if the background signal is longer than the signal cut it, if
2168             % not extend it with zeros
2169             if numel(ref1.s) > numel(s)
2170                 tmp_r = ref1.s(1:numel(s));
2171             else
2172                 tmp_r = zeros(size(s));
2173                 tmp_r(1:numel(ref1.s)) = ref1.s;
2174             end
2175             s = complex(real(s)-real(tmp_r),imag(s)-imag(tmp_r));
2176         elseif i==2 && isfield(ref2,'s')
2177             % if the background signal is longer than the signal cut it, if
2178             % not extend it with zeros
2179             if numel(ref2.s) > numel(s)
2180                 tmp_r = ref2.s(1:numel(s));
2181             else
2182                 tmp_r = zeros(size(s));
2183                 tmp_r(1:numel(ref2.s)) = ref2.s;
2184             end
2185             s = complex(real(s)-real(tmp_r),imag(s)-imag(tmp_r));
2186         end
2187         data.import.NMR.data{i}.signal = s;
2188         data.import.NMR.data{i}.raw.signal = s;
2189
2190         if ~isempty(strfind(workfiles{i},' - background'))
2191             data.import.LIAG.sampleVol(i) = backVol;
2192         elseif ~isempty(strfind(workfiles{i},' - calibration'))
2193             data.import.LIAG.sampleVol(i) = calibVol;
2194         elseif isempty(strfind(workfiles{i},' - background')) &&...
2195                 isempty(strfind(workfiles{i},' - calibration'))
2196             data.import.LIAG.sampleVol(i) = dataVol;
2197         end
2198     end
2199     data.import.LIAG.Tbulk = 1e6;
2200     data.import.LIAG.Tbulk_keep_fit = false;
2201     data.import.LIAG.workpaths = workpaths;
2202     data.import.LIAG.datapath = datapath;
2203     data.import.LIAG.calibrationpath = calibrationpath;
2204     data.import.LIAG.backgroundpath1 = backgroundpath1;
2205     data.import.LIAG.backgroundpath2 = backgroundpath2;
2206
2207     % update the global data structure
2208     data.import.NMR.files = ffnames;
2209     data.import.NMR.filesShort = shownames;
2210 end
2211
2212 end
2213
2214 %%
2215 function [data,gui] = importDataMouse(data,gui)
2216
2217 in.path = fullfile(data.import.path);
2218 in.fileformat = data.import.fileformat;
2219 out = LoadNMRData_driver(in);
2220
2221 fnames = struct;
2222 % shownames is just a dummy to hold all data file names that
2223 % will be shown in the listbox
2224 shownames = cell(1,1);
2225
2226 c = 0;
2227 for j = 1:size(out.nmrData,2)
2228     % the individual file names
2229     c = c + 1;
2230     fnames(c).parfile = 'acq.par';
2231     fnames(c).datafile = out.nmrData{j}.datfile;
2232     fnames(c).T2specfile = '';
2233
2234     shownames{c} = ['T2_',fnames(c).datafile];
2235
2236     % the NMR data
2237     % here we fix the time scale from [ms] to [s]
2238     if max(out.nmrData{j}.time) > 100
2239         out.nmrData{j}.time = out.nmrData{j}.time/1000;
2240         out.nmrData{j}.raw.time = out.nmrData{j}.raw.time/1000;
2241     end
2242     data.import.NMR.data{c} = out.nmrData{j};
2243     data.import.NMR.para{c} = out.parData;
2244 end
2245
2246 % update the global data structure
2247 data.import.NMR.files = fnames;
2248 data.import.NMR.filesShort = shownames;
2249
2250 end
2251
2252 %%
2253 function [data,gui] = importDataMRSMatlab(data,gui)
2254
2255 in.path = fullfile(data.import.path);
2256 in.name = data.import.file;
2257 in.fileformat = data.import.fileformat;
2258 out = LoadNMRData_driver(in);
2259
2260 fnames = struct;
2261 % shownames is just a dummy to hold all data file names that
2262 % will be shown in the listbox
2263 shownames = cell(1,1);
2264
2265 c = 0;
2266 for j = 1:size(out.nmrData,2)
2267     % the individual file names
2268     c = c + 1;
2269     fnames(c).parfile = '';
2270     fnames(c).datafile = data.import.file;
2271     fnames(c).T2specfile = '';
2272
2273     shownames{c} = out.parData{j}.file;
2274
2275     data.import.NMR.data{c} = out.nmrData{j};
2276     data.import.NMR.para{c} = out.parData{j};
2277 end
2278
2279 data.import.MRSMATLAB.q = out.q;
2280 data.import.NMR.files = fnames;
2281 data.import.NMR.filesShort = shownames;
2282
2283 answer = questdlg('Stack all or stack individually', ...
2284     'MRSD import', ...
2285     'all','individual','none','none');
2286
2287 switch answer
2288     case 'all'
2289         s = zeros(size(data.import.NMR.data{1}.signal));
2290         for c = 1:numel(data.import.NMR.data)
2291             s = s + data.import.NMR.data{c}.signal;
2292         end
2293         s = s./numel(data.import.NMR.data);
2294
2295     case 'individual'
2296         [indx,~] = listdlg('PromptString','Select pulse moments:',...
2297             'SelectionMode','multi',...
2298             'ListString',shownames);
2299
2300         if ~isempty(indx)
2301             s = zeros(size(data.import.NMR.data{1}.signal));
2302             for c = indx
2303                 s = s + data.import.NMR.data{c}.signal;
2304             end
2305             s = s./numel(indx);
2306         end
2307 end
2308
2309 switch answer
2310     case {'all','individual'}
2311         tmpdata = data.import.NMR.data{1};
2312         tmpdata.signal = s;
2313         tmpdata.raw.signal = s;
2314
2315         data.import.NMR.data = cell(1,1);
2316         data.import.NMR.data{1} = tmpdata;
2317
2318         tmppar = data.import.NMR.para{1};
2319         data.import.NMR.para = cell(1,1);
2320         data.import.NMR.para{1} = tmppar;
2321
2322         fnames = fnames(1);
2323         shownames = cell(1,1);
2324         shownames{1} = fnames.datafile;
2325
2326         data.import.NMR.files = fnames;
2327         data.import.NMR.filesShort = shownames;
2328     otherwise
2329         % nothing to do
2330 end
2331
2332 end
2333
2334 %%
2335 function [data,gui] = importDataIBAC(data,gui)
2336
2337 in.path = fullfile(data.import.path);
2338 in.name = data.import.file;
2339 in.fileformat = data.import.fileformat;
2340 out = LoadNMRData_driver(in);
2341
2342 nslices = out.parData.depths;
2343 nfiles = size(out.nmrData,2);
2344
2345 fnames = struct;
2346 % shownames is just a dummy to hold all data file names that
2347 % will be shown in the listbox
2348 shownames = cell(1,1);
2349
2350 c = 0;
2351 for j = 1:size(out.nmrData,2)
2352     % the individual file names
2353     c = c + 1;
2354     fnames(c).parfile = out.parData.parfile;
2355     fnames(c).datafile = out.nmrData{j}.datfile;
2356     fnames(c).T2specfile = '';
2357
2358     shownames{c} = [fnames(c).datafile];
2359
2360     data.import.NMR.data{c} = out.nmrData{j};
2361     data.import.NMR.para{c} = out.parData;
2362 end
2363
2364 % check if the number of depth levels is equal to the number of
2365 % measurements
2366 if nslices == nfiles
2367     % create z-vector
2368     p = out.parData;
2369     zslice = linspace(p.initialdepth,p.finaldepth,p.depths)';
2370     data.import.IBAC.use_z = true;
2371     data.import.IBAC.zslice = zslice;
2372     if numel(zslice) > 1
2373         c = 0;
2374         for i = 1:nfiles
2375             c = c + 1;
2376             tmp = shownames{i};
2377             shownames{i} = [tmp,' z:',sprintf('%05d',zslice(c))];
2378         end
2379     end
2380 else
2381     data.import.IBAC.use_z = false;
2382     data.import.IBAC.zslice = 1:1:max([nfiles 1]);
2383 end
2384
2385 % update the global data structure
2386 data.import.NMR.files = fnames;
2387 data.import.NMR.filesShort = shownames;
2388
2389 end
2390
2391 %%
2392 function data = loadGUIParameters(datapath,fname)
2393 fid = fopen(fullfile(datapath,fname));
2394 d = textscan(fid,'%s','Delimiter','\n');
2395 fclose(fid);
2396 data = struct;
2397 for i = 1:size(d{1},1)
2398     str = char(d{1}(i));
2399     str = fixParameterString(str);
2400     eval(['data.',str,';']); %#ok<EVLDOT>
2401 end
2402
2403 end
2404
2405 %%
2406 function data = loadGUIrawdata(data,NMRpath,NMRfile)
2407
2408 load(fullfile(NMRpath,'NUCLEUSinv_raw.mat'),'savedata');
2409
2410 data.import.file = NMRfile;
2411 data.import.path = NMRpath;
2412 data.import.NMR = savedata;
2413
2414 end
2415
2416 %------------- END OF CODE --------------
2417
2418 %% License:
2419 % MIT License
2420 %
2421 % Copyright (c) 2018 Thomas Hiller
2422 %
2423 % Permission is hereby granted, free of charge, to any person obtaining a copy
2424 % of this software and associated documentation files (the "Software"), to deal
2425 % in the Software without restriction, including without limitation the rights
2426 % to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
2427 % copies of the Software, and to permit persons to whom the Software is
2428 % furnished to do so, subject to the following conditions:
2429 %
2430 % The above copyright notice and this permission notice shall be included in all
2431 % copies or substantial portions of the Software.
2432 %
2433 % THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
2434 % IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
2435 % FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
2436 % AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
2437 % LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
2438 % OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
2439 % SOFTWARE.