Description of onListboxData
onListboxData
PURPOSE
handles the calls from the context menu of the data
SYNOPSIS
function onListboxData(src,~)
DESCRIPTION
onListboxData handles the calls from the context menu of the data
listbox
 Syntax:
       onListboxData
 Inputs:
       src - handle of the calling object
 Outputs:
       none
 Example:
       onListboxData(src,~)
 Other m-files required:
       clearSingleAxis
       NUCLEUSinv_updateInterface
       onPushRun
       processNMRDataControl
       removeInversionFields
       updateInfo
       updatePlotsDistribution
       updatePlotsLcurve
       updatePlotsSignal
 Subfunctions:
       none
 MAT-files required:
       none
 See also: NUCLEUSinv
 Author: see AUTHORS.md
 email: see AUTHORS.md
 License: MIT License (at end)
CROSS-REFERENCE INFORMATION
This function calls:
NUCLEUSinv_updateInterface updates all GUI elements
onPopupInvstdType selects the inversion method for the standard inversion
onPushRun handles the callbacks to all RUN push buttons in both GUIs and
FixedTimeView is an extra subGUI to fix certain relaxation times during
PhaseView is an extra subGUI to visualize the phase of a T2 signal
clearSingleAxis clears an individual axis
processNMRDataControl prepares simple NMR raw data processing
removeInversionFields deletes all inversion result fields from NUCLEUSinv
showFitStatistics shows an extra fit statistics figure (for T2 data)
updateInfo updates the information shown in all information list boxes
updatePlotsDistribution plots the RTD and PSD curves into NUCLEUSinv
updatePlotsJointInversion plots the joint-inversion results in NUCLEUSinv
updatePlotsLcurve plots the results of the L-curve calculation
updatePlotsSignal plots the raw and processed NMR signals in NUCLEUSinv
This function is called by:
NUCLEUSinv_createPanelData creates data panel
importINV2INV imports a previously saved NUCLEUSinv session
runInversionBatch batch processes the inversion using for all NMR signals
SOURCE CODE
function onListboxData(src,~)
%onListboxData handles the calls from the context menu of the data
%listbox
%
% Syntax:
%       onListboxData
%
% Inputs:
%       src - handle of the calling object
%
% Outputs:
%       none
%
% Example:
%       onListboxData(src,~)
%
% Other m-files required:
%       clearSingleAxis
%       NUCLEUSinv_updateInterface
%       onPushRun
%       processNMRDataControl
%       removeInversionFields
%       updateInfo
%       updatePlotsDistribution
%       updatePlotsLcurve
%       updatePlotsSignal
%
% Subfunctions:
%       none
%
% MAT-files required:
%       none
%
% See also: NUCLEUSinv
% Author: see AUTHORS.md
% email: see AUTHORS.md
% License: MIT License (at end)
%------------- BEGIN CODE --------------
%% get GUI handle and data
fig = findobj('Tag','INV');
gui = getappdata(fig,'gui');
data = getappdata(fig,'data');
INVdata = getappdata(fig,'INVdata');
% check if there is any data at all
if isfield(data.import,'NMR')
    % id of the selected file
    id = get(src,'Value');
    if ~isempty(id) && numel(id) == 1
        % get possible parameter file information
        if isfield(data.import.NMR,'para')
            data.info.parameter = data.import.NMR.para{id};
        else
            data.info.parameter = 'No parameter data available.';
        end
        % check if inversion data already exists for this file
        if isstruct(INVdata{id})
            % if so update the data and the GUI
            data_upd = INVdata{id};
            data_upd.info = data.info;
            data_upd.import = data.import;
            data_upd.calib = data.calib;
            data_upd.pressure = data.pressure;
            data = data_upd;
            % if "mono" or "free" inversion is chossen update the internal
            % fixed relaxation times field
            if strcmp(data.invstd.invtype,'mono') ||...
                    strcmp(data.invstd.invtype,'free')
                data.invstd.Tfixed_val = [data.results.invstd.T zeros(1,5-data.invstd.freeDT)];
            end
            setappdata(fig,'data',data);
            % update interface and plot axes
            NUCLEUSinv_updateInterface;
            updatePlotsSignal;
            updateInfo(gui.plots.SignalPanel);
            gui = getappdata(fig,'gui');
            if isfield(data,'results')
                if isfield(data.results,'invstd')
                    updatePlotsDistribution;
                end
                if isfield(data.results,'invjoint')
                    updatePlotsJointInversion;
                end
                if isfield(data.results,'lcurve')
                    updatePlotsLcurve;
                end
            end
        else
            % remove temporary data fields
            data = removeInversionFields(data);
            % set format and T1/T2 dependent GUI elements
            data.process.isgated = false;
            switch data.import.NMR.data{id}.flag
                case 'T1'
                    data.process.gatetype = 'raw';
                    data.process.start = 1;
                case 'T2'
                    switch data.import.fileformat
                        case {'dart','excel','field','helios','mouse','NMRMOD'}
                            data.process.gatetype = 'raw';
                            data.process.start = 1;
                        otherwise
                            % standard T2
                            data.process.gatetype = 'log';
                            data.process.start = 1;
                    end
                otherwise
                    disp('onListboxData: Something is utterly wrong.')
            end
            % take all echoes
            data.process.end = length(data.import.NMR.data{id}.signal);
            % ---
            % special treatments
            % there is no volume or porosity
            data.param.sampVol = 1;
            if isfield(data.import,'BGR')
                data.invstd.porosity = data.import.BGR.porosity;
            else
                data.invstd.porosity = 1;
            end
            if isfield(data.import,'LIAG')
                data.param.sampVol = data.import.LIAG.sampleVol(id);
                if ~isempty(strfind(data.import.NMR.filesShort{id},' - calibration'))
                    data.param.calibVol = data.import.LIAG.sampleVol(id);
                    % update the GUI data
                    setappdata(fig,'data',data);
                    % set mono fit as default
                    set(gui.popup_handles.invstd_InvType,'Value',1);
                    onPopupInvstdType(gui.popup_handles.invstd_InvType);
                    data = getappdata(fig,'data');
                end
                if isempty(strfind(data.import.NMR.filesShort{id},' - calibration'))
                    data.invstd.Tbulk = data.import.LIAG.Tbulk;
                    % update the GUI data
                    setappdata(fig,'data',data);
                    % set mono fit as default
                    set(gui.popup_handles.invstd_InvType,'Value',3);
                    onPopupInvstdType(gui.popup_handles.invstd_InvType);
                    data = getappdata(fig,'data');
                end
            else
                data.param.sampVol = 1;
            end
            if isfield(data.import,'NMRMOD')
                data.param.rho = data.import.NMR.para{id}.rho*1e6;
                data.invstd.Tbulk = data.import.NMR.para{id}.Tbulk;
                data.invstd.Tdiff = data.import.NMR.para{id}.Tdiff;
                data.invstd.porosity = data.import.NMR.para{id}.porosity;
            end
            % ---
            % update the figure data
            setappdata(fig,'data',data);
            % process the NMR data
            processNMRDataControl(fig,id);
             % update interface
            NUCLEUSinv_updateInterface;
            % update the data plot axes
            updatePlotsSignal;
            % update the info fields
            updateInfo(gui.plots.SignalPanel);
            gui = getappdata(fig,'gui');
            % clear inversion axes
            clearSingleAxis(gui.axes_handles.rtd);
            clearSingleAxis(gui.axes_handles.psd);
            % switch-off uncert context menu
            set(gui.cm_handles.axes_rtd_uncert,'Enable','off');
        end
        % set focus on data
        % set(gui.plots.SignalPanel,'Selection',1);
        % set(gui.plots.DistPanel,'Selection',1);
        % reset all RUN buttons
        set(gui.push_handles.invstd_run,'String','<HTML><u>R</u>UN',...
            'BackgroundColor','g','Enable','on','Callback',@onPushRun);
        set(gui.push_handles.invjoint_run,'String','<HTML><u>R</u>UN',...
            'BackgroundColor','g','Enable','on','Callback',@onPushRun);
        % if the Fit Statistics window is open update it
        if ~isempty(findobj('Tag','FITSTATS'))
            showFitStatistics;
        end
        % if the PhaseView window is open update it
        if ~isempty(findobj('Tag','PHASEVIEW'))
            PhaseView(gui.menu.extra_phaseview);
        end
        % if the FixedTimeView window is open update it
        if ~isempty(findobj('Tag','FIXEDTIMEVIEW'))
            FixedTimeView(gui.menu.extra_fixedtime);
        end
    else
        helpdlg({'onListboxData:','Only choose one data set at a time.'},...
            'too many data');
    end
else
    helpdlg('Nothing to do because there is no data loaded!',...
        'onListboxData: Load NMR data first.');
end
% update the figure data
setappdata(fig,'gui',gui);
end
%------------- END OF CODE --------------
%% License:
% MIT License
%
% Copyright (c) 2018 Thomas Hiller
%
% Permission is hereby granted, free of charge, to any person obtaining a copy
% of this software and associated documentation files (the "Software"), to deal
% in the Software without restriction, including without limitation the rights
% to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
% copies of the Software, and to permit persons to whom the Software is
% furnished to do so, subject to the following conditions:
%
% The above copyright notice and this permission notice shall be included in all
% copies or substantial portions of the Software.
%
% THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
% IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
% FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
% AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
% LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
% OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
% SOFTWARE.