Description of onPushRun
onPushRun
PURPOSE
handles the callbacks to all RUN push buttons in both GUIs and
SYNOPSIS
function onPushRun(src,~)
DESCRIPTION
onPushRun handles the callbacks to all RUN push buttons in both GUIs and
starts the corresponding calculation
 Syntax:
       onPushRun
 Inputs:
       src - handle of the calling object
 Outputs:
       none
 Example:
       onPushRun(src,~)
 Other m-files required:
       none
 Subfunctions:
       none
 MAT-files required:
           runInversionStd
           runInversionJoint
           caluclatePressureSaturation
           calculateNMR
 See also: NUCLEUSinv
 Author: see AUTHORS.md
 email: see AUTHORS.md
 License: MIT License (at end)
CROSS-REFERENCE INFORMATION
This function calls:
calculateNMR calculates the NMR signals for the full and partially saturated
caluclatePressureSaturation calculates the geometry dependent pressure
runInversionBatch batch processes the inversion using for all NMR signals
runInversionJoint controls the joint inversion process to infer a pore size
runInversionStd controls the standard inversion process to invert a
runUncertaintyCalculation caluclates inverison statistics in some kind of
This function is called by:
NUCLEUSinv_createPanelInversionJoint creates joint inversion panel
NUCLEUSinv_createPanelInversionStd creates standard inversion panel
NUCLEUSmod_createPanelCPS creates pressure panel
NUCLEUSmod_createPanelNMR creates NMR panel
onContextSignalList handles the calls from the context menu of the data
onListboxData handles the calls from the context menu of the data
onPushStop recognizes that a STOP push button was pressed and resets the
caluclatePressureSaturation calculates the geometry dependent pressure
runInversionBatch batch processes the inversion using for all NMR signals
runInversionJoint controls the joint inversion process to infer a pore size
runInversionStd controls the standard inversion process to invert a
runUncertaintyCalculation caluclates inverison statistics in some kind of
SOURCE CODE
function onPushRun(src,~)
%onPushRun handles the callbacks to all RUN push buttons in both GUIs and
%starts the corresponding calculation
%
% Syntax:
%       onPushRun
%
% Inputs:
%       src - handle of the calling object
%
% Outputs:
%       none
%
% Example:
%       onPushRun(src,~)
%
% Other m-files required:
%       none
%
% Subfunctions:
%       none
%
% MAT-files required:
%           runInversionStd
%           runInversionJoint
%           caluclatePressureSaturation
%           calculateNMR
%
% See also: NUCLEUSinv
% Author: see AUTHORS.md
% email: see AUTHORS.md
% License: MIT License (at end)
%------------- BEGIN CODE --------------
%% get GUI handle and data
fig = ancestor(src,'figure','toplevel');
fig_tag = get(fig,'Tag');
% switch depending on the calling figure
switch fig_tag
    case 'INV'
        gui = getappdata(fig,'gui');
        tag = get(src,'Tag');
        % switch depending on inversion method
        switch tag
            case 'std'
                switch get(gui.check_handles.invstd_batch,'Value')
                    case 0
                        runInversionStd;
                    case 1
                        runInversionBatch;
                end
             case 'stdbatch'
                runInversionBatch;
            case 'joint'
                runInversionJoint;
            case 'uncert'
                runUncertaintyCalculation;
        end
    case 'MOD'
        tag = get(src,'Tag');
        % switch depending on calculation
        switch tag
            case 'pressure'
                caluclatePressureSaturation;
            case 'nmr'
                calculateNMR;
        end
end
end
%------------- END OF CODE --------------
%% License:
% MIT License
%
% Copyright (c) 2018 Thomas Hiller
%
% Permission is hereby granted, free of charge, to any person obtaining a copy
% of this software and associated documentation files (the "Software"), to deal
% in the Software without restriction, including without limitation the rights
% to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
% copies of the Software, and to permit persons to whom the Software is
% furnished to do so, subject to the following conditions:
%
% The above copyright notice and this permission notice shall be included in all
% copies or substantial portions of the Software.
%
% THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
% IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
% FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
% AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
% LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
% OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
% SOFTWARE.