Description of onPushStop
onPushStop
PURPOSE
recognizes that a STOP push button was pressed and resets the
SYNOPSIS
function onPushStop(src,~)
DESCRIPTION
onPushStop recognizes that a STOP push button was pressed and resets the
button to a RUN button; the switch is accomplished by the "UserData" property
where the value 0 indicates in the calling function that the STOP button was
actually pressed
 Syntax:
       onPushStop
 Inputs:
       src - handle of the calling object
 Outputs:
       none
 Example:
       onPushStop(src,~)
 Other m-files required:
       none
 Subfunctions:
       none
 MAT-files required:
       none
 See also: NUCLEUSinv
 Author: Thomas Hiller
 email: thomas.hiller[at]leibniz-liag.de
 License: MIT License (at end)
CROSS-REFERENCE INFORMATION
This function calls:
onPushRun handles the callbacks to all RUN push buttons in both GUIs and
This function is called by:
runInversionBatch batch processes the inversion using for all NMR signals
runInversionJoint controls the joint inversion process to infer a pore size
runInversionStd controls the standard inversion process to invert a
SOURCE CODE
function onPushStop(src,~)
%onPushStop recognizes that a STOP push button was pressed and resets the
%button to a RUN button; the switch is accomplished by the "UserData" property
%where the value 0 indicates in the calling function that the STOP button was
%actually pressed
%
% Syntax:
%       onPushStop
%
% Inputs:
%       src - handle of the calling object
%
% Outputs:
%       none
%
% Example:
%       onPushStop(src,~)
%
% Other m-files required:
%       none
%
% Subfunctions:
%       none
%
% MAT-files required:
%       none
%
% See also: NUCLEUSinv
% Author: Thomas Hiller
% email: thomas.hiller[at]leibniz-liag.de
% License: MIT License (at end)
%------------- BEGIN CODE --------------
%% if the button was pressed 'Value' is 1
value = get(src,'Value');
% STOP button was pressed so reset to a RUN button
% "UserData" reset to 0
if value == 1
    set(src,'String','<HTML><u>R</u>UN','BackGroundColor','g','UserData',0,'Callback',@onPushRun);
end
end
%------------- END OF CODE --------------
%% License:
% MIT License
%
% Copyright (c) 2018 Thomas Hiller
%
% Permission is hereby granted, free of charge, to any person obtaining a copy
% of this software and associated documentation files (the "Software"), to deal
% in the Software without restriction, including without limitation the rights
% to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
% copies of the Software, and to permit persons to whom the Software is
% furnished to do so, subject to the following conditions:
%
% The above copyright notice and this permission notice shall be included in all
% copies or substantial portions of the Software.
%
% THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
% IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
% FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
% AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
% LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
% OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
% SOFTWARE.