Description of Inv2DView
Inv2DView
PURPOSE
is an extra subGUI to calculate 2D inversion of T1-T2 data
SYNOPSIS
function Inv2DView(src,~)
DESCRIPTION
Inv2DView is an extra subGUI to calculate 2D inversion of T1-T2 data
 Syntax:
       Inv2DView
 Inputs:
       src - handle of the calling object
 Outputs:
       none
 Example:
       Inv2DView(src,~)
 Other m-files required:
       beautifyAxes
       clearAllAxes
       displayStatusText
       fitData2D
       imagescnan
       onListboxData
       onRadioGates
       updatePlotsSignal;
       updatePlotsDistribution;
       updateInfo;
 Subfunctions:
       findApproxTlgmAmplitude
       tv_closeme
       tv_estimateIRtype
       tv_getTLGM
       tv_onCheckDCM
       tv_onEditValue
       tv_onPopupIRType
       tv_onPopupT1Type
       tv_onPushRun
       tv_onPushSave
       tv_onPushView
       tv_onPushUpdate
       tv_onRadioLogLin
       tv_plotResults
       tv_plotRawData
       tv_prepareRawData
       tv_setAxesScaling
 MAT-files required:
       none
 See also: NUCLEUSinv
 Author: see AUTHORS.md
 email: see AUTHORS.md
 License: MIT License (at end)
CROSS-REFERENCE INFORMATION
This function calls:
onListboxData handles the calls from the context menu of the data
onMenuView handles the view menu entries
beautifyAxes can be used to globally change the general appearance of axes
changeColorTheme changes the color theme of the calling figure
clearAllAxes clears all axes of a given figure
clearSingleAxis clears an individual axis
displayStatusText shows status information either in the GUI or on the
fixVerticalTextAlignment fixes the vertical positioning of all text
minimizePanel handles the minimization/maximization of all box-panels for
onFigureSizeChange fixes an ugly Matlab bug when resizing a box-panel
applyGatesToSignal re-samples (gates) a NMR signal to speedup the
fitData2D is a control routine that fits 2D NMR data;
getFitErrors calculates all relevant fitting errors for the NMR inversion
getTLogMean2D
runLcurveDiscrete
runLcurveIterative performs an iterative L-curve calculation. This routine
This function is called by:
onMenuSubGUIs handles the extra menu entries to open NUCLEUS sub GUIs
importMOD2D2INV imports data directly from the NUCLEUSmod 2D GUI
importNMRdata is the general import routine for NMR data
SUBFUNCTIONS
function tv_onCheckLinkLambdas(src,~)
function tv_onCheckLogGates(src,~)
function tv_onEditValue(src,~)
function tv_onPopupT1Type(src,~)
function tv_onPopupIRType(src,~)
function tv_onPopupRegType(src,~)
function tv_onPushRun(src,~)
function tv_onPush2DLCURVE(src,~)
function [dat,param] = tv_prepareInvData(figh)
function tv_onPushSave(src,~)
function tv_onPushView(src,~)
function tv_onPushUpdate(src,~)
function tv_onRadioLogLin(src,~)
function tv_onCheckDCM(src,~)
function tv_onPopupCbar(src,~)
function tv_setAxesScaling(figh)
function tv_plotLCurveUpdate(figh,tmp_norm,method)
function tv_plotResults(figh)
function tv_plotRawData(figh)
function tv_checkLSEparams(data)
function tv_getTLGM(figh)
function amp = findApproxTlgmAmplitude(t,f,TLGM)
function tv_prepareRawData(figh)
function tv_estimateIRtype(figh)
function txt = localDcmFcn(~,event,ax)
function tv_closeme(src,~)
SOURCE CODE
function Inv2DView(src,~)
%Inv2DView is an extra subGUI to calculate 2D inversion of T1-T2 data
%
% Syntax:
%       Inv2DView
%
% Inputs:
%       src - handle of the calling object
%
% Outputs:
%       none
%
% Example:
%       Inv2DView(src,~)
%
% Other m-files required:
%       beautifyAxes
%       clearAllAxes
%       displayStatusText
%       fitData2D
%       imagescnan
%       onListboxData
%       onRadioGates
%       updatePlotsSignal;
%       updatePlotsDistribution;
%       updateInfo;
%
% Subfunctions:
%       findApproxTlgmAmplitude
%       tv_closeme
%       tv_estimateIRtype
%       tv_getTLGM
%       tv_onCheckDCM
%       tv_onEditValue
%       tv_onPopupIRType
%       tv_onPopupT1Type
%       tv_onPushRun
%       tv_onPushSave
%       tv_onPushView
%       tv_onPushUpdate
%       tv_onRadioLogLin
%       tv_plotResults
%       tv_plotRawData
%       tv_prepareRawData
%       tv_setAxesScaling
%
% MAT-files required:
%       none
%
% See also: NUCLEUSinv
% Author: see AUTHORS.md
% email: see AUTHORS.md
% License: MIT License (at end)
%------------- BEGIN CODE --------------
%% get GUI handle and data
figh_nucleus = ancestor(src,'figure','toplevel');
nucleus.data = getappdata(figh_nucleus,'data');
nucleus.gui = getappdata(figh_nucleus,'gui');
myui = nucleus.gui.myui;
colors = myui.colors;
%% get GUI data from NUCLEUS
data = nucleus.data.inv2D;
% check if the figure is already open
fig_T1T2map = findobj('Tag','2DINV');
% if not, create it
if isempty(fig_T1T2map)
    % draw the figure on top of NUCLEUSinv
    fig_T1T2map = figure('Name','NUCLEUSinv - 2D Inversion',...
        'NumberTitle','off','Resize','on','ToolBar','none',...
        'Tag','2DINV','CloseRequestFcn',@tv_closeme,...
        'SizeChangedFcn',@onFigureSizeChange,'MenuBar','none');
    pos0 = get(figh_nucleus,'Position');
    cent(1) = (pos0(1)+pos0(3)/2);
    cent(2) = (pos0(2)+pos0(4)/2);
    posf = [cent(1)-pos0(3)/2.5 pos0(2)+22 pos0(3)/1.25 pos0(4)-22];
    % posf = pos0;
    set(fig_T1T2map,'Position',posf);
    gui.menu.view = uimenu(fig_T1T2map,'Label','View');
    gui.menu.view_toolbar = uimenu(gui.menu.view,'Label','Figure Toolbar',...
        'Callback',@onMenuView);
    cpanel_w = 175;
    % create the main layout
    gui.main = uix.HBox('Parent',fig_T1T2map,'BackGroundColor',colors.panelBG,...
        'Spacing',5,'Padding',5,'Visible','off');
    gui.left = uix.ScrollingPanel('Parent',gui.main);
    gui.panels.main = uix.VBox('Parent',gui.left,'BackGroundColor',colors.panelBG,...
        'Spacing',5,'Padding',0); % controls
    gui.right = uix.VBox('Parent',gui.main,'BackGroundColor',colors.panelBG,...
        'Spacing',5,'Padding',0); % plots
    set(gui.main,'Widths',[350 -1 ]);
    % waitbar indicating the loading of the GUI
    steps = 6;
    hwb = waitbar(0,'loading ...','Name','T1T2 2DInv GUI initialization','Visible','off');
    set(hwb,'Units','Pixel')
    posw = get(hwb,'Position');
    set(hwb,'Position',[posf(1)+posf(3)/2-posw(3)/2 posf(2)+posf(4)/2-posw(4)/2 posw(3:4)]);
    set(hwb,'Visible','on');
    %% --- properties panel ---
    waitbar(1/steps,hwb,'loading GUI elements - properties');
    gui.panels.prop.main = uix.BoxPanel('Parent',gui.panels.main,...
        'Title','Properties','MinimizeFcn',@minimizePanel,...
        'BackGroundColor',colors.panelBG,...
        'TitleColor',colors.BoxINV,'ForegroundColor',colors.BoxTitle);
    gui.panels.prop.VBox = uix.VBox('Parent',gui.panels.prop.main,...
        'BackGroundColor',colors.panelBG,'Spacing',3,'Padding',3);
    % D coeff.
    gui.panels.prop.HBox1 = uix.HBox('Parent',gui.panels.prop.VBox,...
        'BackGroundColor',colors.panelBG,'Spacing',3);
    gui.text_handles.diff = uicontrol('Parent',gui.panels.prop.HBox1,...
        'Style','text','FontSize',myui.fontsize,'HorizontalAlignment','center',...
        'BackGroundColor',colors.panelBG,'ForeGroundColor',colors.panelFG,...
        'String',['Diffusion coeff. [10',char(hex2dec('207B')),...
        char(hex2dec('2079')),' m',char(hex2dec('00B2')),'/s]']);
    uix.Empty('Parent',gui.panels.prop.HBox1);
    tstr = 'Set diffusion coefficient.';
    gui.edit_handles.diff = uicontrol('Parent',gui.panels.prop.HBox1,...
        'Style','edit','String',sprintf('%4.3f',data.prop.D*1e9),...
        'FontSize',myui.fontsize,'Tag','diff',...
        'BackGroundColor',colors.editBG,'ForeGroundColor',colors.panelFG,...
        'ToolTipString',tstr,'UserData',struct('Tooltipstr',tstr),...
        'Callback',@tv_onEditValue);
    set(gui.panels.prop.HBox1,'Widths',[cpanel_w -1 -1]);
    % Gradient
    gui.panels.prop.HBox2 = uix.HBox('Parent',gui.panels.prop.VBox,...
        'BackGroundColor',colors.panelBG,'Spacing',3);
    gui.text_handles.gradient = uicontrol('Parent',gui.panels.prop.HBox2,...
        'Style','text','FontSize',myui.fontsize,'HorizontalAlignment','center',...
        'BackGroundColor',colors.panelBG,'ForeGroundColor',colors.panelFG,...
        'String',"Gradient [T/m]");
    uix.Empty('Parent',gui.panels.prop.HBox2);
    tstr = 'Set device gradient.';
    gui.edit_handles.gradient = uicontrol('Parent',gui.panels.prop.HBox2,...
        'Style','edit','String',sprintf('%d',data.prop.G0),...
        'FontSize',myui.fontsize,'Tag','gradient',...
        'BackGroundColor',colors.editBG,'ForeGroundColor',colors.panelFG,...
        'ToolTipString',tstr,'UserData',struct('Tooltipstr',tstr),...
        'Callback',@tv_onEditValue);
    set(gui.panels.prop.HBox2,'Widths',[cpanel_w -1 -1]);
    % echo time
    gui.panels.prop.HBox3 = uix.HBox('Parent',gui.panels.prop.VBox,...
        'BackGroundColor',colors.panelBG,'Spacing',3);
    gui.text_handles.echo_time = uicontrol('Parent',gui.panels.prop.HBox3,...
        'Style','text','FontSize',myui.fontsize,'HorizontalAlignment','center',...
        'BackGroundColor',colors.panelBG,'ForeGroundColor',colors.panelFG,...
        'String',"Echo time TE [µs]");
    uix.Empty('Parent',gui.panels.prop.HBox3);
    tstr = 'Set echo time tE.';
    gui.edit_handles.echo_time = uicontrol('Parent',gui.panels.prop.HBox3,...
        'Style','edit','String',sprintf('%d',data.prop.te*1e6),...
        'FontSize',myui.fontsize,'Tag','echo_time',...
        'BackGroundColor',colors.editBG,'ForeGroundColor',colors.panelFG,...
        'ToolTipString',tstr,'UserData',struct('Tooltipstr',tstr),...
        'Enable','off',...
        'Callback',@tv_onEditValue);
    set(gui.panels.prop.HBox3,'Widths',[cpanel_w -1 -1]);
    % first and last recovery time
    gui.panels.prop.HBox4 = uix.HBox('Parent',gui.panels.prop.VBox,...
        'BackGroundColor',colors.panelBG,'Spacing',3);
    gui.text_handles.firstT1 = uicontrol('Parent',gui.panels.prop.HBox4,...
        'Style','text','FontSize',myui.fontsize,'HorizontalAlignment','center',...
        'BackGroundColor',colors.panelBG,'ForeGroundColor',colors.panelFG,...
        'String',"T1 recov - first | last");
    tstr = 'Set first / last T1 recovery time.';
    gui.edit_handles.firstT1 = uicontrol('Parent',gui.panels.prop.HBox4,...
        'Style','edit','String',sprintf('%d',data.prop.firstT1),...
        'FontSize',myui.fontsize,'Tag','firstT1',...
        'BackGroundColor',colors.editBG,'ForeGroundColor',colors.panelFG,...
        'ToolTipString',tstr,'UserData',struct('Tooltipstr',tstr),...
        'Callback',@tv_onEditValue);
    gui.edit_handles.lastT1 = uicontrol('Parent',gui.panels.prop.HBox4,...
        'Style','edit','String',sprintf('%d',data.prop.lastT1),...
        'FontSize',myui.fontsize,'Tag','lastT1',...
        'BackGroundColor',colors.editBG,'ForeGroundColor',colors.panelFG,...
        'ToolTipString',tstr,'UserData',struct('Tooltipstr',tstr),...
        'Callback',@tv_onEditValue);
    set(gui.panels.prop.HBox4,'Widths',[cpanel_w -1 -1]);
    % first and last echo
    gui.panels.prop.HBox5 = uix.HBox('Parent',gui.panels.prop.VBox,...
        'BackGroundColor',colors.panelBG,'Spacing',3);
    gui.text_handles.first = uicontrol('Parent',gui.panels.prop.HBox5,...
        'Style','text','FontSize',myui.fontsize,'HorizontalAlignment','center',...
        'BackGroundColor',colors.panelBG,'ForeGroundColor',colors.panelFG,...
        'String',"T2 echoes - first | last");
    tstr = 'Set first / last echo of all T2 signals.';
    gui.edit_handles.firstT2 = uicontrol('Parent',gui.panels.prop.HBox5,...
        'Style','edit','String',sprintf('%d',data.prop.firstT2),...
        'FontSize',myui.fontsize,'Tag','firstT2',...
        'BackGroundColor',colors.editBG,'ForeGroundColor',colors.panelFG,...
        'ToolTipString',tstr,'UserData',struct('Tooltipstr',tstr),...
        'Callback',@tv_onEditValue);
    gui.edit_handles.lastT2 = uicontrol('Parent',gui.panels.prop.HBox5,...
        'Style','edit','String',sprintf('%d',data.prop.lastT2),...
        'FontSize',myui.fontsize,'Tag','lastT2',...
        'BackGroundColor',colors.editBG,'ForeGroundColor',colors.panelFG,...
        'ToolTipString',tstr,'UserData',struct('Tooltipstr',tstr),...
        'Callback',@tv_onEditValue);
    set(gui.panels.prop.HBox5,'Widths',[cpanel_w -1 -1]);
    % signal gateing
    gui.panels.prop.HBox6 = uix.HBox('Parent',gui.panels.prop.VBox,...
        'BackGroundColor',colors.panelBG,'Spacing',3);
    gui.text_handles.gateing = uicontrol('Parent',gui.panels.prop.HBox6,...
        'Style','text','FontSize',myui.fontsize,'HorizontalAlignment','center',...
        'BackGroundColor',colors.panelBG,'ForeGroundColor',colors.panelFG,...
        'String',"Log gating | #gates");
    tstr = 'Activate / deactivate signal log gateing. Set number of gates.';
    gui.check_handles.gateing = uicontrol('Parent',gui.panels.prop.HBox6,...
        'Style','checkbox','String','on/off','Value',0,...
        'FontSize',myui.fontsize,'Tag','gateing',...
        'BackGroundColor',myui.colors.panelBG,'ForeGroundColor',myui.colors.panelFG,...
        'ToolTipString',tstr,'UserData',struct('Tooltipstr',tstr),...
        'Callback',@tv_onCheckLogGates);
    gui.edit_handles.Ngates = uicontrol('Parent',gui.panels.prop.HBox6,...
        'Style','edit','String',sprintf('%d',data.prop.Ngates),...
        'FontSize',myui.fontsize,'Tag','Ngates',...
        'BackGroundColor',colors.editBG,'ForeGroundColor',colors.panelFG,...
        'ToolTipString',tstr,'UserData',struct('Tooltipstr',tstr),...
        'Enable','off',...
        'Callback',@tv_onEditValue);
    set(gui.panels.prop.HBox6,'Widths',[cpanel_w -1 -1]);
    %% --- inversion panel ---
    waitbar(2/steps,hwb,'loading GUI elements - 2D inversion');
    gui.panels.inv.main = uix.BoxPanel('Parent',gui.panels.main,...
        'Title','2D inversion settings','MinimizeFcn',@minimizePanel,...
        'BackGroundColor',colors.panelBG,...
        'TitleColor',colors.BoxINV,'ForegroundColor',colors.BoxTitle);
    gui.panels.inv.VBox = uix.VBox('Parent',gui.panels.inv.main,...
        'BackGroundColor',colors.panelBG,'Spacing',3,'Padding',3);
    % T1type
    gui.panels.inv.HBox0 = uix.HBox('Parent',gui.panels.inv.VBox,...
        'BackGroundColor',colors.panelBG,'Spacing',3);
    gui.text_handles.T1type = uicontrol('Parent',gui.panels.inv.HBox0,...
        'Style','text','FontSize',myui.fontsize,'HorizontalAlignment','center',...
        'BackGroundColor',colors.panelBG,'ForeGroundColor',colors.panelFG,...
        'String','T1 type (SR / IR)');
    tstr = 'Choose between Saturation and Inversion Recovery.';
    gui.popup_handles.T1type = uicontrol('Parent',gui.panels.inv.HBox0,...
        'Style','popup','String',{'Saturation Recovery','Inversion Recovery'},...
        'Value',data.inv.T1IRfac,'FontSize',myui.fontsize,...
        'BackGroundColor',myui.colors.editBG,'ForeGroundColor',myui.colors.panelFG,...
        'UserData',struct('Tooltipstr',tstr),'Callback',@tv_onPopupT1Type);
    set(gui.panels.inv.HBox0,'Widths',[cpanel_w -1]);
    % IR kernel type
    gui.panels.inv.HBox01 = uix.HBox('Parent',gui.panels.inv.VBox,...
        'BackGroundColor',colors.panelBG,'Spacing',3);
    gui.text_handles.IRtype = uicontrol('Parent',gui.panels.inv.HBox01,...
        'Style','text','FontSize',myui.fontsize,'HorizontalAlignment','center',...
        'BackGroundColor',colors.panelBG,'ForeGroundColor',colors.panelFG,...
        'String','IR kernel type');
    tstr = 'Choose IR kernel type.';
    gui.popup_handles.IRtype = uicontrol('Parent',gui.panels.inv.HBox01,...
        'Style','popup','String',{'1-2exp(-t/T1)','-exp(-t/T1)'},...
        'Value',1,'FontSize',myui.fontsize,...
        'BackGroundColor',myui.colors.editBG,'ForeGroundColor',myui.colors.panelFG,...
        'UserData',struct('Tooltipstr',tstr),'Callback',@tv_onPopupIRType);
    set(gui.panels.inv.HBox01,'Widths',[cpanel_w -1]);
    % RTD T1
    gui.panels.inv.HBox1 = uix.HBox('Parent',gui.panels.inv.VBox,...
        'BackGroundColor',colors.panelBG,'Spacing',3);
    gui.text_handles.rtdT1 = uicontrol('Parent',gui.panels.inv.HBox1,...
        'Style','text','FontSize',myui.fontsize,'HorizontalAlignment','center',...
        'BackGroundColor',colors.panelBG,'ForeGroundColor',colors.panelFG,...
        'String','RTD T1 [s] -  min | max | #');
    tstr = "";
    gui.edit_handles.rtdT1min = uicontrol('Parent',gui.panels.inv.HBox1,...
        'Style','edit','String',sprintf('%5.4f',data.inv.T1min),...
        'FontSize',myui.fontsize,'Tag','rtdT1min',...
        'BackGroundColor',colors.editBG,'ForeGroundColor',colors.panelFG,...
        'ToolTipString',tstr,'UserData',struct('Tooltipstr',tstr),...
        'Callback',@tv_onEditValue);
    tstr = "";
    gui.edit_handles.rtdT1max = uicontrol('Parent',gui.panels.inv.HBox1,...
        'Style','edit','String',sprintf('%d',data.inv.T1max),...
        'FontSize',myui.fontsize,'Tag','rtdT1max',...
        'BackGroundColor',colors.editBG,'ForeGroundColor',colors.panelFG,...
        'ToolTipString',tstr,'UserData',struct('Tooltipstr',tstr),...
        'Callback',@tv_onEditValue);
    tstr = "";
    gui.edit_handles.rtdT1N = uicontrol('Parent',gui.panels.inv.HBox1,...
        'Style','edit','String',sprintf('%d',data.inv.T1N),...
        'FontSize',myui.fontsize,'Tag','rtdT1N',...
        'BackGroundColor',colors.editBG,'ForeGroundColor',colors.panelFG,...
        'ToolTipString',tstr,'UserData',struct('Tooltipstr',tstr),...
        'Callback',@tv_onEditValue);
    set(gui.panels.inv.HBox1,'Widths',[cpanel_w -1 -1 -1]);
    % RTD T2
    gui.panels.inv.HBox2 = uix.HBox('Parent',gui.panels.inv.VBox,...
        'BackGroundColor',colors.panelBG,'Spacing',3);
    gui.text_handles.rtdT2 = uicontrol('Parent',gui.panels.inv.HBox2,...
        'Style','text','FontSize',myui.fontsize,'HorizontalAlignment','center',...
        'BackGroundColor',colors.panelBG,'ForeGroundColor',colors.panelFG,...
        'String','RTD T2 [s] - min | max | #');
    tstr = "";
    gui.edit_handles.rtdT2min = uicontrol('Parent',gui.panels.inv.HBox2,...
        'Style','edit','String',sprintf('%5.4f',data.inv.T2min),...
        'FontSize',myui.fontsize,'Tag','rtdT2min',...
        'BackGroundColor',colors.editBG,'ForeGroundColor',colors.panelFG,...
        'ToolTipString',tstr,'UserData',struct('Tooltipstr',tstr),...
        'Callback',@tv_onEditValue);
    tstr = "";
    gui.edit_handles.rtdT2max = uicontrol('Parent',gui.panels.inv.HBox2,...
        'Style','edit','String',sprintf('%d',data.inv.T2max),...
        'FontSize',myui.fontsize,'Tag','rtdT2max',...
        'BackGroundColor',colors.editBG,'ForeGroundColor',colors.panelFG,...
        'ToolTipString',tstr,'UserData',struct('Tooltipstr',tstr),...
        'Callback',@tv_onEditValue);
    tstr = "";
    gui.edit_handles.rtdT2N = uicontrol('Parent',gui.panels.inv.HBox2,...
        'Style','edit','String',sprintf('%d',data.inv.T2N),...
        'FontSize',myui.fontsize,'Tag','rtdT2N',...
        'BackGroundColor',colors.editBG,'ForeGroundColor',colors.panelFG,...
        'ToolTipString',tstr,'UserData',struct('Tooltipstr',tstr),...
        'Callback',@tv_onEditValue);
    set(gui.panels.inv.HBox2,'Widths',[cpanel_w -1 -1 -1]);
    % regularization option
    gui.panels.inv.HBox3 = uix.HBox('Parent',gui.panels.inv.VBox,...
        'BackGroundColor',colors.panelBG,'Spacing',3);
    gui.text_handles.RegType = uicontrol('Parent',gui.panels.inv.HBox3,...
        'Style','text','FontSize',myui.fontsize,'HorizontalAlignment','center',...
        'BackGroundColor',colors.panelBG,'ForeGroundColor',colors.panelFG,...
        'String','Regularization');
    tstr = 'Choose regularization option.';
    gui.popup_handles.RegType = uicontrol('Parent',gui.panels.inv.HBox3,...
        'Style','popup','String',{'manual','Tikhonov (SVD)','TSVD (SVD)','DSVD (SVD)','Discrep. (SVD)'},...
        'Value',1,'FontSize',myui.fontsize,...
        'BackGroundColor',myui.colors.editBG,'ForeGroundColor',myui.colors.panelFG,...
        'UserData',struct('Tooltipstr',tstr),'Callback',@tv_onPopupRegType);
    set(gui.panels.inv.HBox3,'Widths',[cpanel_w -1]);
    % T1 lambda / order
    gui.panels.inv.HBox4 = uix.HBox('Parent',gui.panels.inv.VBox,...
        'BackGroundColor',colors.panelBG,'Spacing',3);
    gui.text_handles.lambdaT1 = uicontrol('Parent',gui.panels.inv.HBox4,...
        'Style','text','FontSize',myui.fontsize,'HorizontalAlignment','center',...
        'BackGroundColor',colors.panelBG,'ForeGroundColor',colors.panelFG,...
        'String','Lambda T1 | L-order');
    tstr = "";
    gui.edit_handles.lambdaT1 = uicontrol('Parent',gui.panels.inv.HBox4,...
        'Style','edit','String',sprintf('%f',data.inv.T1lambda),...
        'FontSize',myui.fontsize,'Tag','lambdaT1',...
        'BackGroundColor',colors.editBG,'ForeGroundColor',colors.panelFG,...
        'ToolTipString',tstr,'UserData',struct('Tooltipstr',tstr),...
        'Callback',@tv_onEditValue);
    tstr = "";
    gui.edit_handles.orderT1 = uicontrol('Parent',gui.panels.inv.HBox4,...
        'Style','edit','String',sprintf('%d',data.inv.T1order),...
        'FontSize',myui.fontsize,'Tag','orderT1',...
        'BackGroundColor',colors.editBG,'ForeGroundColor',colors.panelFG,...
        'ToolTipString',tstr,'UserData',struct('Tooltipstr',tstr),...
        'Callback',@tv_onEditValue);
    set(gui.panels.inv.HBox4,'Widths',[cpanel_w -1 -1]);
    % T2 lambda / order
    gui.panels.inv.HBox5 = uix.HBox('Parent',gui.panels.inv.VBox,...
        'BackGroundColor',colors.panelBG,'Spacing',3);
    gui.text_handles.lambdaT2 = uicontrol('Parent',gui.panels.inv.HBox5,...
        'Style','text','FontSize',myui.fontsize,'HorizontalAlignment','center',...
        'BackGroundColor',colors.panelBG,'ForeGroundColor',colors.panelFG,...
        'String','Lambda T2 | L-order');
    tstr = "";
    gui.edit_handles.lambdaT2 = uicontrol('Parent',gui.panels.inv.HBox5,...
        'Style','edit','String',sprintf('%f',data.inv.T2lambda),...
        'FontSize',myui.fontsize,'Tag','lambdaT2',...
        'BackGroundColor',colors.editBG,'ForeGroundColor',colors.panelFG,...
        'ToolTipString',tstr,'UserData',struct('Tooltipstr',tstr),...
        'Callback',@tv_onEditValue);
    tstr = "";
    gui.edit_handles.orderT2 = uicontrol('Parent',gui.panels.inv.HBox5,...
        'Style','edit','String',sprintf('%d',data.inv.T2order),...
        'FontSize',myui.fontsize,'Tag','orderT2',...
        'BackGroundColor',colors.editBG,'ForeGroundColor',colors.panelFG,...
        'ToolTipString',tstr,'UserData',struct('Tooltipstr',tstr),...
        'Enable','off','Callback',@tv_onEditValue);
    set(gui.panels.inv.HBox5,'Widths',[cpanel_w -1 -1]);
    % RUN button
    gui.panels.inv.HBox6 = uix.HBox('Parent',gui.panels.inv.VBox,...
        'BackGroundColor',colors.panelBG,'Spacing',3);
    uix.Empty('Parent',gui.panels.inv.HBox6);
    tstr = 'RUN 2D inversion.';
    gui.push_handles.run_inv = uicontrol('Parent',gui.panels.inv.HBox6,...
        'String','RUN 2D INV','FontSize',myui.fontsize,'Tag','rtd',...
        'ToolTipString',tstr,'UserData',struct('Tooltipstr',tstr),...
        'BackGroundColor','g','Callback',@tv_onPushRun);
    set(gui.panels.inv.HBox6,'Widths',[cpanel_w -1]);
    %% --- L-curve panel ---
    waitbar(3/steps,hwb,'loading GUI elements - regularisation panel');
    gui.panels.regu.main = uix.BoxPanel('Parent',gui.panels.main,...
        'Title','Regularisation - "L-curve"','MinimizeFcn',@minimizePanel,...
        'BackGroundColor',colors.panelBG,...
        'TitleColor',colors.BoxINV,'ForegroundColor',colors.BoxTitle);
    gui.panels.regu.VBox = uix.VBox('Parent',gui.panels.regu.main,...
        'BackGroundColor',colors.panelBG,'Spacing',3,'Padding',3);
    % link lambdas
    gui.panels.regu.HBox1 = uix.HBox('Parent',gui.panels.regu.VBox,...
        'BackGroundColor',colors.panelBG,'Spacing',3);
    gui.text_handles.linklambda = uicontrol('Parent',gui.panels.regu.HBox1,...
        'Style','text','FontSize',myui.fontsize,'HorizontalAlignment','center',...
        'BackGroundColor',colors.panelBG,'ForeGroundColor',colors.panelFG,...
        'String',"Link Lambdas | factor");
    tstr = 'Activate / deactivate lambda linking. Set factor x so that L1 = x*L2.';
    gui.check_handles.linking = uicontrol('Parent',gui.panels.regu.HBox1,...
        'Style','checkbox','String','on/off','Value',0,...
        'FontSize',myui.fontsize,'Tag','linking',...
        'BackGroundColor',myui.colors.panelBG,'ForeGroundColor',myui.colors.panelFG,...
        'ToolTipString',tstr,'UserData',struct('Tooltipstr',tstr),...
        'Callback',@tv_onCheckLinkLambdas);
    gui.edit_handles.lambdaFactor = uicontrol('Parent',gui.panels.regu.HBox1,...
        'Style','edit','String',sprintf('%d',data.regu.lambdaFactor),...
        'FontSize',myui.fontsize,'Tag','lambdaFactor',...
        'BackGroundColor',colors.editBG,'ForeGroundColor',colors.panelFG,...
        'ToolTipString',tstr,'UserData',struct('Tooltipstr',tstr),...
        'Enable','off',...
        'Callback',@tv_onEditValue);
    set(gui.panels.regu.HBox1,'Widths',[cpanel_w -1 -1]);
    % lambda T1 - L-curve
    gui.panels.regu.HBox2 = uix.HBox('Parent',gui.panels.regu.VBox,...
        'BackGroundColor',colors.panelBG,'Spacing',3);
    gui.text_handles.lambdaT1min = uicontrol('Parent',gui.panels.regu.HBox2,...
        'Style','text','FontSize',myui.fontsize,'HorizontalAlignment','center',...
        'BackGroundColor',colors.panelBG,'ForeGroundColor',colors.panelFG,...
        'String','Lambda T1 -  min | max | #');
    tstr = "";
    gui.edit_handles.lambdaT1min = uicontrol('Parent',gui.panels.regu.HBox2,...
        'Style','edit','String',sprintf('%3.2f',data.regu.lambdaT1min),...
        'FontSize',myui.fontsize,'Tag','lambdaT1min',...
        'BackGroundColor',colors.editBG,'ForeGroundColor',colors.panelFG,...
        'ToolTipString',tstr,'UserData',struct('Tooltipstr',tstr),...
        'Callback',@tv_onEditValue);
    tstr = "";
    gui.edit_handles.lambdaT1max = uicontrol('Parent',gui.panels.regu.HBox2,...
        'Style','edit','String',sprintf('%d',data.regu.lambdaT1max),...
        'FontSize',myui.fontsize,'Tag','lambdaT1max',...
        'BackGroundColor',colors.editBG,'ForeGroundColor',colors.panelFG,...
        'ToolTipString',tstr,'UserData',struct('Tooltipstr',tstr),...
        'Callback',@tv_onEditValue);
    tstr = "";
    gui.edit_handles.lambdaT1N = uicontrol('Parent',gui.panels.regu.HBox2,...
        'Style','edit','String',sprintf('%d',data.regu.lambdaT1N),...
        'FontSize',myui.fontsize,'Tag','lambdaT1N',...
        'BackGroundColor',colors.editBG,'ForeGroundColor',colors.panelFG,...
        'ToolTipString',tstr,'UserData',struct('Tooltipstr',tstr),...
        'Callback',@tv_onEditValue);
    set(gui.panels.regu.HBox2,'Widths',[cpanel_w -1 -1 -1]);
    % lambda T2 - L-curve
    gui.panels.regu.HBox3 = uix.HBox('Parent',gui.panels.regu.VBox,...
        'BackGroundColor',colors.panelBG,'Spacing',3);
    gui.text_handles.lambdaT2min = uicontrol('Parent',gui.panels.regu.HBox3,...
        'Style','text','FontSize',myui.fontsize,'HorizontalAlignment','center',...
        'BackGroundColor',colors.panelBG,'ForeGroundColor',colors.panelFG,...
        'String','Lambda T2 -  min | max | #');
    tstr = "";
    gui.edit_handles.lambdaT2min = uicontrol('Parent',gui.panels.regu.HBox3,...
        'Style','edit','String',sprintf('%3.2f',data.regu.lambdaT2min),...
        'FontSize',myui.fontsize,'Tag','lambdaT2min',...
        'BackGroundColor',colors.editBG,'ForeGroundColor',colors.panelFG,...
        'ToolTipString',tstr,'UserData',struct('Tooltipstr',tstr),...
        'Callback',@tv_onEditValue);
    tstr = "";
    gui.edit_handles.lambdaT2max = uicontrol('Parent',gui.panels.regu.HBox3,...
        'Style','edit','String',sprintf('%d',data.regu.lambdaT2max),...
        'FontSize',myui.fontsize,'Tag','lambdaT2max',...
        'BackGroundColor',colors.editBG,'ForeGroundColor',colors.panelFG,...
        'ToolTipString',tstr,'UserData',struct('Tooltipstr',tstr),...
        'Callback',@tv_onEditValue);
    tstr = "";
    gui.edit_handles.lambdaT2N = uicontrol('Parent',gui.panels.regu.HBox3,...
        'Style','edit','String',sprintf('%d',data.regu.lambdaT2N),...
        'FontSize',myui.fontsize,'Tag','lambdaT2N',...
        'BackGroundColor',colors.editBG,'ForeGroundColor',colors.panelFG,...
        'ToolTipString',tstr,'UserData',struct('Tooltipstr',tstr),...
        'Callback',@tv_onEditValue);
    set(gui.panels.regu.HBox3,'Widths',[cpanel_w -1 -1 -1]);
    % RUN button
    gui.panels.regu.HBox5 = uix.HBox('Parent',gui.panels.regu.VBox,...
        'BackGroundColor',colors.panelBG,'Spacing',3);
    gui.text_handles.calc2Dlcurve = uicontrol('Parent',gui.panels.regu.HBox5,...
        'Style','text','FontSize',myui.fontsize,'HorizontalAlignment','center',...
        'BackGroundColor',colors.panelBG,...
        'String','EXPERIMENTAL FEATURE','ForeGroundColor','red');
    % uix.Empty('Parent',gui.panels.regu.HBox5);
    tstr = 'Get 2D L-curve.';
    gui.push_handles.run_2dlcurve = uicontrol('Parent',gui.panels.regu.HBox5,...
        'String','CALC 2D L-CURVE','FontSize',myui.fontsize,'Tag','rtd',...
        'ToolTipString',tstr,'UserData',struct('Tooltipstr',tstr),...
        'BackGroundColor','g','Callback',@tv_onPush2DLCURVE);
    set(gui.panels.regu.HBox5,'Widths',[cpanel_w -1]);
    %% --- information panel ---
    waitbar(4/steps,hwb,'loading GUI elements - information panel');
    gui.panels.info.main = uix.BoxPanel('Parent',gui.panels.main,...
        'Title','Information','MinimizeFcn',@minimizePanel,...
        'BackGroundColor',colors.panelBG,...
        'TitleColor',colors.BoxINV,'ForegroundColor',colors.BoxTitle);
    gui.panels.info.VBox = uix.VBox('Parent',gui.panels.info.main,...
        'BackGroundColor',colors.panelBG,'Spacing',3,'Padding',3);
    % T1 range
    gui.panels.info.HBox1 = uix.HBox('Parent',gui.panels.info.VBox,...
        'BackGroundColor',colors.panelBG,'Spacing',3);
    gui.text_handles.rangeT1 = uicontrol('Parent',gui.panels.info.HBox1,...
        'Style','text','FontSize',myui.fontsize,'HorizontalAlignment','center',...
        'BackGroundColor',colors.panelBG,'ForeGroundColor',colors.panelFG,...
        'String','T1 range - min [s] | max [s]');
    tstr = "";
    gui.edit_handles.T1min = uicontrol('Parent',gui.panels.info.HBox1,...
        'Style','edit','String',sprintf('%5.4f',data.info.T1min),...
        'FontSize',myui.fontsize,'Tag','T1min',...
        'BackGroundColor',colors.editBG,'ForeGroundColor',colors.panelFG,...
        'ToolTipString',tstr,'UserData',struct('Tooltipstr',tstr),...
        'Callback',@tv_onEditValue);
    tstr = "";
    gui.edit_handles.T1max = uicontrol('Parent',gui.panels.info.HBox1,...
        'Style','edit','String',sprintf('%d',data.info.T1max),...
        'FontSize',myui.fontsize,'Tag','T1max',...
        'BackGroundColor',colors.editBG,'ForeGroundColor',colors.panelFG,...
        'ToolTipString',tstr,'UserData',struct('Tooltipstr',tstr),...
        'Callback',@tv_onEditValue);
    set(gui.panels.info.HBox1,'Widths',[cpanel_w -1 -1]);
    % T2 range
    gui.panels.info.HBox2 = uix.HBox('Parent',gui.panels.info.VBox,...
        'BackGroundColor',colors.panelBG,'Spacing',3);
    gui.text_handles.rangeT2 = uicontrol('Parent',gui.panels.info.HBox2,...
        'Style','text','FontSize',myui.fontsize,'HorizontalAlignment','center',...
        'BackGroundColor',colors.panelBG,'ForeGroundColor',colors.panelFG,...
        'String','T2 range - min [s] | max [s]');
    tstr = "";
    gui.edit_handles.T2min = uicontrol('Parent',gui.panels.info.HBox2,...
        'Style','edit','String',sprintf('%5.4f',data.info.T2min),...
        'FontSize',myui.fontsize,'Tag','T2min',...
        'BackGroundColor',colors.editBG,'ForeGroundColor',colors.panelFG,...
        'ToolTipString',tstr,'UserData',struct('Tooltipstr',tstr),...
        'Callback',@tv_onEditValue);
    tstr = "";
    gui.edit_handles.T2max = uicontrol('Parent',gui.panels.info.HBox2,...
        'Style','edit','String',sprintf('%d',data.info.T2max),...
        'FontSize',myui.fontsize,'Tag','T2max',...
        'BackGroundColor',colors.editBG,'ForeGroundColor',colors.panelFG,...
        'ToolTipString',tstr,'UserData',struct('Tooltipstr',tstr),...
        'Callback',@tv_onEditValue);
    set(gui.panels.info.HBox2,'Widths',[cpanel_w -1 -1]);
    % E0
    gui.panels.info.HBox0 = uix.HBox('Parent',gui.panels.info.VBox,...
        'BackGroundColor',colors.panelBG,'Spacing',3);
    gui.text_handles.E0 = uicontrol('Parent',gui.panels.info.HBox0,...
        'Style','text','FontSize',myui.fontsize,'HorizontalAlignment','center',...
        'BackGroundColor',colors.panelBG,'ForeGroundColor',colors.panelFG,...
        'String','E0 [-]');
    uix.Empty('Parent',gui.panels.info.HBox0);
    tstr = "";
    gui.edit_handles.E0 = uicontrol('Parent',gui.panels.info.HBox0,...
        'Style','edit','String',sprintf('%4.3f',data.info.E0),...
        'FontSize',myui.fontsize,'Tag','E0',...
        'BackGroundColor',colors.editBG,'ForeGroundColor',colors.panelFG,...
        'ToolTipString',tstr,'UserData',struct('Tooltipstr',tstr),...
        'Enable','off');
    set(gui.panels.info.HBox0,'Widths',[cpanel_w -1 -1]);
    % TLGM
    gui.panels.info.HBox3 = uix.HBox('Parent',gui.panels.info.VBox,...
        'BackGroundColor',colors.panelBG,'Spacing',3);
    gui.text_handles.Tlgm = uicontrol('Parent',gui.panels.info.HBox3,...
        'Style','text','FontSize',myui.fontsize,'HorizontalAlignment','center',...
        'BackGroundColor',colors.panelBG,'ForeGroundColor',colors.panelFG,...
        'String','TLGM [s] (T1,T2)');
    tstr = "";
    gui.edit_handles.T1tlgm = uicontrol('Parent',gui.panels.info.HBox3,...
        'Style','edit','String',sprintf('%4.3f',data.info.T1tlgm),...
        'FontSize',myui.fontsize,'Tag','T1tlgm',...
        'BackGroundColor',colors.editBG,'ForeGroundColor',colors.panelFG,...
        'ToolTipString',tstr,'UserData',struct('Tooltipstr',tstr),...
        'Enable','off');
    tstr = "";
    gui.edit_handles.T2tlgm = uicontrol('Parent',gui.panels.info.HBox3,...
        'Style','edit','String',sprintf('%4.3f',data.info.T2tlgm),...
        'FontSize',myui.fontsize,'Tag','T2tlgm',...
        'BackGroundColor',colors.editBG,'ForeGroundColor',colors.panelFG,...
        'ToolTipString',tstr,'UserData',struct('Tooltipstr',tstr),...
        'Enable','off');
    set(gui.panels.info.HBox3,'Widths',[cpanel_w -1 -1]);
    % TLGM ratio
    gui.panels.info.HBox4 = uix.HBox('Parent',gui.panels.info.VBox,...
        'BackGroundColor',colors.panelBG,'Spacing',3);
    gui.text_handles.Tlgm_ratio = uicontrol('Parent',gui.panels.info.HBox4,...
        'Style','text','FontSize',myui.fontsize,'HorizontalAlignment','center',...
        'BackGroundColor',colors.panelBG,'ForeGroundColor',colors.panelFG,...
        'String','TLGM ratio T1/T2');
    uix.Empty('Parent',gui.panels.info.HBox4);
    tstr = "";
    gui.edit_handles.Tlgm_ratio = uicontrol('Parent',gui.panels.info.HBox4,...
        'Style','edit','String',sprintf('%4.3f',data.info.T1tlgm/data.info.T2tlgm),...
        'FontSize',myui.fontsize,'Tag','Tlgm_ratio',...
        'BackGroundColor',colors.editBG,'ForeGroundColor',colors.panelFG,...
        'ToolTipString',tstr,'UserData',struct('Tooltipstr',tstr),...
        'Enable','off');
    set(gui.panels.info.HBox4,'Widths',[cpanel_w -1 -1]);
    % Tmax
    gui.panels.info.HBox5 = uix.HBox('Parent',gui.panels.info.VBox,...
        'BackGroundColor',colors.panelBG,'Spacing',3);
    gui.text_handles.Tmax = uicontrol('Parent',gui.panels.info.HBox5,...
        'Style','text','FontSize',myui.fontsize,'HorizontalAlignment','center',...
        'BackGroundColor',colors.panelBG,'ForeGroundColor',colors.panelFG,...
        'String','TMAX [s] (T1,T2)');
    tstr = "";
    gui.edit_handles.T1tmax = uicontrol('Parent',gui.panels.info.HBox5,...
        'Style','edit','String',sprintf('%4.3f',data.info.T1tmax),...
        'FontSize',myui.fontsize,'Tag','T1tmax',...
        'BackGroundColor',colors.editBG,'ForeGroundColor',colors.panelFG,...
        'ToolTipString',tstr,'UserData',struct('Tooltipstr',tstr),...
        'Enable','off');
    tstr = "";
    gui.edit_handles.T2tmax = uicontrol('Parent',gui.panels.info.HBox5,...
        'Style','edit','String',sprintf('%4.3f',data.info.T2tmax),...
        'FontSize',myui.fontsize,'Tag','T2tmax',...
        'BackGroundColor',colors.editBG,'ForeGroundColor',colors.panelFG,...
        'ToolTipString',tstr,'UserData',struct('Tooltipstr',tstr),...
        'Enable','off');
    set(gui.panels.info.HBox5,'Widths',[cpanel_w -1 -1]);
    % Tmax ratio
    gui.panels.info.HBox6 = uix.HBox('Parent',gui.panels.info.VBox,...
        'BackGroundColor',colors.panelBG,'Spacing',3);
    gui.text_handles.Tmax_ratio = uicontrol('Parent',gui.panels.info.HBox6,...
        'Style','text','FontSize',myui.fontsize,'HorizontalAlignment','center',...
        'BackGroundColor',colors.panelBG,'ForeGroundColor',colors.panelFG,...
        'String','TMAX ratio T1/T2');
    uix.Empty('Parent',gui.panels.info.HBox6);
    tstr = "";
    gui.edit_handles.Tmax_ratio = uicontrol('Parent',gui.panels.info.HBox6,...
        'Style','edit','String',sprintf('%4.3f',data.info.T1tmax/data.info.T2tmax),...
        'FontSize',myui.fontsize,'Tag','Tmax_ratio',...
        'BackGroundColor',colors.editBG,'ForeGroundColor',colors.panelFG,...
        'ToolTipString',tstr,'UserData',struct('Tooltipstr',tstr),...
        'Enable','off');
    set(gui.panels.info.HBox6,'Widths',[cpanel_w -1 -1]);
    % log/lin axes
    gui.panels.info.HBox7 = uix.HBox('Parent',gui.panels.info.VBox,...
        'BackGroundColor',colors.panelBG,'Spacing',3);
    gui.text_handles.loglin_axes = uicontrol('Parent',gui.panels.info.HBox7,...
        'Style','text','FontSize',myui.fontsize,'HorizontalAlignment','center',...
        'BackGroundColor',colors.panelBG,'ForeGroundColor',colors.panelFG,...
        'String','Echo time axes');
    tstr = "";
    gui.radio_handles.log = uicontrol('Parent',gui.panels.info.HBox7,...
        'Style','radiobutton','String','log','FontSize',myui.fontsize,'Tag','log',...
        'ToolTipString',tstr,'UserData',struct('Tooltipstr',tstr),...
        'BackGroundColor',myui.colors.panelBG,'ForeGroundColor',myui.colors.panelFG,...
        'Enable','on','Value',1,'Callback',@tv_onRadioLogLin);
    gui.radio_handles.lin = uicontrol('Parent',gui.panels.info.HBox7,...
        'Style','radiobutton','String','lin','FontSize',myui.fontsize,'Tag','lin',...
        'ToolTipString',tstr,'UserData',struct('Tooltipstr',tstr),...
        'BackGroundColor',myui.colors.panelBG,'ForeGroundColor',myui.colors.panelFG,...
        'Enable','on','Value',0,'Callback',@tv_onRadioLogLin);
    set(gui.panels.info.HBox7,'Widths',[cpanel_w -1 -1]);
    % DCM for 2D plot
    gui.panels.info.HBox8 = uix.HBox('Parent',gui.panels.info.VBox,...
        'BackGroundColor',colors.panelBG,'Spacing',3);
    gui.text_handles.dcm = uicontrol('Parent',gui.panels.info.HBox8,...
        'Style','text','FontSize',myui.fontsize,'HorizontalAlignment','center',...
        'BackGroundColor',colors.panelBG,'ForeGroundColor',colors.panelFG,...
        'String','2D model data inspection');
    tstr = "";
    gui.check_handles.dcm = uicontrol('Parent',gui.panels.info.HBox8,...
        'Style','checkbox','String','activate','FontSize',myui.fontsize,'Tag','dcm',...
        'ToolTipString',tstr,'UserData',struct('Tooltipstr',tstr),...
        'BackGroundColor',myui.colors.panelBG,'ForeGroundColor',myui.colors.panelFG,...
        'Enable','off','Callback',@tv_onCheckDCM);
    set(gui.panels.info.HBox8,'Widths',[cpanel_w -1]);
    % 2D plot colorbar settings
    gui.panels.info.HBox9 = uix.HBox('Parent',gui.panels.info.VBox,...
        'BackGroundColor',colors.panelBG,'Spacing',3);
    gui.text_handles.cbar = uicontrol('Parent',gui.panels.info.HBox9,...
        'Style','text','FontSize',myui.fontsize,'HorizontalAlignment','center',...
        'BackGroundColor',colors.panelBG,'ForeGroundColor',colors.panelFG,...
        'String','2D model colorbar');
    tstr = "colorbar position";
    gui.popup_handles.cbarpos = uicontrol('Parent',gui.panels.info.HBox9,...
        'Style','popupmenu','String',{'inside','outside','none'},'FontSize',myui.fontsize,'Tag','pos',...
        'ToolTipString',tstr,'UserData',struct('Tooltipstr',tstr),...
        'BackGroundColor',myui.colors.editBG,'ForeGroundColor',myui.colors.panelFG,...
        'Enable','off','Callback',@tv_onPopupCbar);
    set(gui.panels.info.HBox9,'Widths',[cpanel_w -1]);
    % --- update MAIN GUI button ---
    gui.panels.save.HBox1 = uix.VBox('Parent',gui.panels.main,...
        'BackGroundColor',colors.panelBG,'Spacing',3);
    tstr = 'UPDATE 2D inversion data in main NUCLEUSinv GUI.';
    gui.push_handles.update = uicontrol('Parent',gui.panels.save.HBox1,...
        'String','UPDATE MAIN GUI','FontSize',myui.fontsize,'Tag','update',...
        'ToolTipString',tstr,'UserData',struct('Tooltipstr',tstr),...
        'BackGroundColor',myui.colors.editBG,'ForeGroundColor',myui.colors.panelFG,...
        'Callback',@tv_onPushUpdate);
    tstr = 'SAVE 2D inversion data to external file.';
    gui.push_handles.save = uicontrol('Parent',gui.panels.save.HBox1,...
        'String','SAVE RESULT','FontSize',myui.fontsize,'Tag','save',...
        'ToolTipString',tstr,'UserData',struct('Tooltipstr',tstr),...
        'BackGroundColor',myui.colors.editBG,'ForeGroundColor',myui.colors.panelFG,...
        'Callback',@tv_onPushSave);
    tstr = 'Export current graphics view to Figure.';
    gui.push_handles.view = uicontrol('Parent',gui.panels.save.HBox1,...
        'String','VIEW2FIG','FontSize',myui.fontsize,'Tag','view',...
        'ToolTipString',tstr,'UserData',struct('Tooltipstr',tstr),...
        'BackGroundColor',myui.colors.editBG,'ForeGroundColor',myui.colors.panelFG,...
        'Callback',@tv_onPushView);
    % set(gui.panels.save.HBox1,'Widths',[-1 -1]);
    % empty space at bottom of left side
    uix.Empty('Parent',gui.panels.main);
    % adjust the heights of all left-column-panels
    heights = [22 22 22 22 28 -1; 22+6*24+8*3 22+8*24+10*4 22+4*24+6*4 22+10*24+12*3 28*3 -1];
    % panel header is always 22 high
    set(gui.panels.main,'Heights',heights(2,:),...
        'MinimumHeights',[22 22 22 22 28*3 0]);
    set(gui.left,'Heights',-1,'MinimumHeights',190+254+22+22+28*3);
    % --- plot boxes ---
    waitbar(5/steps,hwb,'loading GUI elements - graphics');
    gui.rightPanel = uix.TabPanel('Parent',gui.right,...
        'BackGroundColor',colors.panelBG);
    % -- tab1
    gui.tab1 = uix.GridFlex('Parent',gui.rightPanel,...
        'BackGroundColor',colors.panelBG,'Spacing',5);
    gui.pbox11 = uicontainer('Parent',gui.tab1,...
        'BackGroundColor',colors.panelBG);
    gui.pbox13 = uicontainer('Parent',gui.tab1,...
        'BackGroundColor',colors.panelBG);
    gui.pbox12 = uicontainer('Parent',gui.tab1,...
        'BackGroundColor',colors.panelBG);
    gui.pbox14 = uicontainer('Parent',gui.tab1,...
        'BackGroundColor',colors.panelBG);
    set(gui.tab1,'Widths',[-1 -1],'Heights',[-1 -1]);
    % -- tab2
    gui.tab2 = uix.GridFlex('Parent',gui.rightPanel,...
        'BackGroundColor',colors.panelBG,'Spacing',5,'Padding',5);
    gui.pbox21 = uicontainer('Parent',gui.tab2,...
        'BackGroundColor',colors.panelBG);
    gui.pbox22 = uicontainer('Parent',gui.tab2,...
        'BackGroundColor',colors.panelBG);
    gui.pbox23 = uicontainer('Parent',gui.tab2,...
        'BackGroundColor',colors.panelBG);
    gui.pbox24 = uicontainer('Parent',gui.tab2,...
        'BackGroundColor',colors.panelBG);
    set(gui.tab2,'Widths',[-6 -1],'Heights',[-1 -6]);
    % -- tab3
    gui.tab3 = uix.VBoxFlex('Parent',gui.rightPanel,...
        'BackGroundColor',colors.panelBG,'Spacing',5);
    gui.pbox31 = uicontainer('Parent',gui.tab3,...
        'BackGroundColor',colors.panelBG);
    gui.pbox32 = uicontainer('Parent',gui.tab3,...
        'BackGroundColor',colors.panelBG);
    set(gui.tab3,'Heights',[-1 -2]);
    gui.rightPanel.TabTitles = {'DATA','2D INV','FITS'};
    gui.rightPanel.TabWidth = 75;
    gui.rightPanel.TabEnables = {'on','on','on'};
    % -- plot axes --
    gui.axes11 = axes('Parent',gui.pbox11,'Color',colors.axisBG,...
            'XColor',colors.axisFG,'YColor',colors.axisFG,'Box','on');
    gui.axes12 = axes('Parent',gui.pbox12,'Color',colors.axisBG,...
            'XColor',colors.axisFG,'YColor',colors.axisFG,'Box','on');
    gui.axes13 = axes('Parent',gui.pbox13,'Color',colors.axisBG,...
            'XColor',colors.axisFG,'YColor',colors.axisFG,'Box','on');
    gui.axes14 = axes('Parent',gui.pbox14,'Color',colors.axisBG,...
            'XColor',colors.axisFG,'YColor',colors.axisFG,'Box','on');
    gui.axes2 = axes('Parent',gui.pbox22,'Color',colors.axisBG,...
            'XColor',colors.axisFG,'YColor',colors.axisFG,'Box','on','Tag','2D');
    gui.axes21 = axes('Parent',gui.pbox21,'Color',colors.axisBG,...
            'XColor',colors.axisFG,'YColor',colors.axisFG,'Box','on');
    gui.axes24 = axes('Parent',gui.pbox24,'Color',colors.axisBG,...
            'XColor',colors.axisFG,'YColor',colors.axisFG,'Box','on');
    gui.axes31 = axes('Parent',gui.pbox31,'Color',colors.axisBG,...
            'XColor',colors.axisFG,'YColor',colors.axisFG,'Box','on');
    gui.axes32 = axes('Parent',gui.pbox32,'Color',colors.axisBG,...
            'XColor',colors.axisFG,'YColor',colors.axisFG,'ZColor',colors.axisFG,'Box','on');
    % create data curor mode for 2D inv plot inspection
    waitbar(6/steps,hwb,'loading GUI elements - finalizing');
    gui.dcm = datacursormode(fig_T1T2map);
    gui.dcm.UpdateFcn = @(hObj,event,ax)localDcmFcn(hObj,event,gui.axes2);
    gui.dcm.Enable = 'off';
    % --- store main GUI settings ---
    gui.myui = nucleus.gui.myui;
    gui.myui.heights = heights;
    datacmap = load('colormap_rwb.mat');
    gui.myui.cmap_rwb = datacmap.rwb_cmap;
    gui.figh_nucleus = figh_nucleus;
    % --- save gui data to GUI ---
    setappdata(fig_T1T2map,'gui',gui);
    setappdata(fig_T1T2map,'data',data);
    % minimize third panel at startup
    tmp_h = gui.myui.heights(2,:);
    tmp_h(3) = gui.myui.heights(1,3);
    tmp_h(4) = gui.myui.heights(1,4);
    set(gui.panels.main,'Heights',tmp_h);
    set(gui.panels.regu.main,'Minimized',true);
    set(gui.panels.info.main,'Minimized',true);
    fixVerticalTextAlignment(fig_T1T2map);
    changeColorTheme('2DINV',myui.colors.theme);
    % make GUI visible
    delete(hwb);
    set(gui.main,'Visible','on');
else
    % if the figure is already open load the GUI data
    data = getappdata(fig_T1T2map,'data');
    gui = getappdata(fig_T1T2map,'gui');
end
% import the current data from the main NUCLEUS GUI
data.results.T1T2map = nucleus.data.import.T1T2map;
data.results.T1T2map.import = nucleus.data.import.NMR.data;
% check if there is already 2D inversion data in the main NUCLEUS GUI
if isfield(nucleus.data,'results') && isfield(nucleus.data.results,'inv2D')
    % if it is there, then load the INVdata
    nucleus.INVdata = getappdata(figh_nucleus,'INVdata');
    % the 2D data is stored within the data struct of the merged T1 curve
    data.results.inv2D = nucleus.INVdata{end}.results.inv2D;
    % update new 2Dinv GUI data
    setappdata(fig_T1T2map,'data',data);
    if data.prop.useLogGates
        set(gui.check_handles.gateing,'Value',1);
        set(gui.edit_handles.Ngates,'Enable','on');
    end
    % data = getappdata(fig_T1T2map,'data');
    % clear axes
    clearAllAxes(fig_T1T2map);
    % prepare raw data
    tv_prepareRawData(fig_T1T2map);
    % plot the imported raw data
    tv_plotRawData(fig_T1T2map);
    tv_plotResults(fig_T1T2map);
    switch data.inv.regtype
        case 'manual'
            set(gui.popup_handles.RegType,'Value',1);
        case 'gcv_tikh'
            set(gui.popup_handles.RegType,'Value',2);
        case 'gcv_trunc'
            set(gui.popup_handles.RegType,'Value',3);
        case 'gcv_damp'
            set(gui.popup_handles.RegType,'Value',4);
        case 'discrep'
            set(gui.popup_handles.RegType,'Value',5);
    end
    setappdata(fig_T1T2map,'gui',gui);
    tv_onPopupRegType(gui.popup_handles.RegType);
else
    % set the last recovery time entry
    data.prop.lastT1 = numel(data.results.T1T2map.t_recov);
    set(gui.edit_handles.lastT1,'String',num2str(data.prop.lastT1));
    % set the last echo entry
    data.prop.lastT2 = data.results.T1T2map.t2N;
    set(gui.edit_handles.lastT2,'String',num2str(data.prop.lastT2));
    % update new 2Dinv GUI data
    setappdata(fig_T1T2map,'data',data);
    % clear axes
    clearAllAxes(fig_T1T2map);
    % prepare raw data
    tv_prepareRawData(fig_T1T2map);
    % plot the imported raw data
    tv_plotRawData(fig_T1T2map);
end
tv_estimateIRtype(fig_T1T2map);
beautifyAxes(fig_T1T2map);
end
%% subfunction to activate Lambda Linking
function tv_onCheckLinkLambdas(src,~)
figh = ancestor(src,'figure','toplevel');
data = getappdata(figh,'data');
gui = getappdata(figh,'gui');
switch get(src,'Value')
    case 0 % off
        data.regu.linkLambdas = false;
        set(gui.edit_handles.lambdaFactor,'Enable','off');
        set(gui.edit_handles.lambdaT1,'Enable','on');
        set(gui.edit_handles.lambdaT1min,'Enable','on');
        set(gui.edit_handles.lambdaT1max,'Enable','on');
        set(gui.edit_handles.lambdaT1N,'Enable','on');
    case 1 % on
        data.regu.linkLambdas = true;
        set(gui.edit_handles.lambdaFactor,'Enable','on');
        data.inv.T1lambda = data.regu.lambdaFactor * data.inv.T2lambda;
        set(gui.edit_handles.lambdaT1,'Enable','off',...
            'String',num2str(data.inv.T1lambda));
        set(gui.edit_handles.lambdaT1min,'Enable','off');
        set(gui.edit_handles.lambdaT1max,'Enable','off');
        set(gui.edit_handles.lambdaT1N,'Enable','off');
end
% update GUI data
setappdata(figh,'data',data);
end
%% subfunction to activate Log gateing
function tv_onCheckLogGates(src,~)
figh = ancestor(src,'figure','toplevel');
data = getappdata(figh,'data');
gui = getappdata(figh,'gui');
switch get(src,'Value')
    case 0 % off
        data.prop.useLogGates = false;
        set(gui.edit_handles.Ngates,'Enable','off');
    case 1 % on
        data.prop.useLogGates = true;
        set(gui.edit_handles.Ngates,'Enable','on');
end
% update GUI data
setappdata(figh,'data',data);
clearAllAxes(figh);
tv_prepareRawData(figh);
data = getappdata(figh,'data');
tv_checkLSEparams(data);
setappdata(figh,'data',data);
tv_plotRawData(figh);
beautifyAxes(figh);
end
%% subfunction to update the edit fields
function tv_onEditValue(src,~)
figh = ancestor(src,'figure','toplevel');
gui = getappdata(figh,'gui');
data = getappdata(figh,'data');
% get the edit field value
val = str2double(get(src,'String'));
switch get(src,'Tag')
    case {'diff','gradient','echo_time'}
        data.prop.D = str2double(get(gui.edit_handles.diff,'String'))/1e9;
        data.prop.G0 = str2double(get(gui.edit_handles.gradient,'String'));
        data.prop.te = str2double(get(gui.edit_handles.echo_time,'String'))/1e6;
    case {'firstT1','lastT1'}
        data.prop.firstT1 = str2double(get(gui.edit_handles.firstT1,'String'));
        data.prop.lastT1 = str2double(get(gui.edit_handles.lastT1,'String'));
        if data.prop.firstT1 < 1
            data.prop.firstT1 = 1;
            set(gui.edit_handles.firstT1,'String',data.prop.firstT1);
        end
        if data.prop.lastT1 == 0 || data.prop.lastT1 > data.results.T1T2map.t1N
            data.prop.lastT1 = data.results.T1T2map.t1N;
            set(gui.edit_handles.lastT1,'String',data.prop.lastT1);
        end
        % update GUI data
        setappdata(figh,'data',data);
        clearAllAxes(figh);
        tv_prepareRawData(figh);
        data = getappdata(figh,'data');
        tv_plotRawData(figh);
1000         beautifyAxes(figh);
1001     case {'firstT2','lastT2','Ngates'}
1002         data.prop.firstT2 = str2double(get(gui.edit_handles.firstT2,'String'));
1003         data.prop.lastT2 = str2double(get(gui.edit_handles.lastT2,'String'));
1004         if data.prop.firstT2 < 1
1005             data.prop.firstT2 = 1;
1006             set(gui.edit_handles.firstT2,'String',data.prop.firstT2);
1007         end
1008         if data.prop.lastT2 == 0 || data.prop.lastT2 > data.results.T1T2map.t2N
1009             data.prop.lastT2 = data.results.T1T2map.t2N;
1010             set(gui.edit_handles.lastT2,'String',data.prop.lastT2);
1011         end
1012         data.prop.Ngates = str2double(get(gui.edit_handles.Ngates,'String'));
1013         % update GUI data
1014         setappdata(figh,'data',data);
1015         clearAllAxes(figh);
1016         tv_prepareRawData(figh);
1017         data = getappdata(figh,'data');
1018         tv_plotRawData(figh);
1019         beautifyAxes(figh);
1020     case {'rtdT1min','rtdT1max','rtdT1N'}
1021         data.inv.T1min = str2double(get(gui.edit_handles.rtdT1min,'String'));
1022         data.inv.T1max = str2double(get(gui.edit_handles.rtdT1max,'String'));
1023         data.inv.T1N = str2double(get(gui.edit_handles.rtdT1N,'String'));
1024
1025         % update corresponding info fields
1026         data.info.T1min = data.inv.T1min;
1027         set(gui.edit_handles.T1min,'String',num2str(data.info.T1min));
1028         data.info.T1max = data.inv.T1max;
1029         set(gui.edit_handles.T1max,'String',num2str(data.info.T1max));
1030     case {'rtdT2min','rtdT2max','rtdT2N'}
1031         data.inv.T2min = str2double(get(gui.edit_handles.rtdT2min,'String'));
1032         data.inv.T2max = str2double(get(gui.edit_handles.rtdT2max,'String'));
1033         data.inv.T2N = str2double(get(gui.edit_handles.rtdT2N,'String'));
1034
1035         % update corresponding info fields
1036         data.info.T2min = data.inv.T2min;
1037         set(gui.edit_handles.T2min,'String',num2str(data.info.T2min));
1038         data.info.T2max = data.inv.T2max;
1039         set(gui.edit_handles.T2max,'String',num2str(data.info.T2max));
1040     case 'lambdaT1'
1041         data.inv.T1lambda = str2double(get(src,'String'));
1042     case 'orderT1'
1043         set(gui.edit_handles.orderT2,'String',num2str(val));
1044         data.inv.T1order = str2double(get(src,'String'));
1045         data.inv.T2order = str2double(get(gui.edit_handles.orderT2,'String'));
1046     case 'lambdaT2'
1047         data.inv.T2lambda = str2double(get(src,'String'));
1048         if data.regu.linkLambdas
1049             data.inv.T1lambda = data.regu.lambdaFactor * data.inv.T2lambda;
1050             set(gui.edit_handles.lambdaT1,'String',num2str(data.inv.T1lambda));
1051         end
1052     case 'orderT2'
1053         data.inv.T2order = str2double(get(src,'String'));
1054     case 'lambdaFactor'
1055         data.regu.lambdaFactor = str2double(get(src,'String'));
1056         data.inv.T1lambda = data.regu.lambdaFactor * data.inv.T2lambda;
1057         set(gui.edit_handles.lambdaT1,'String',num2str(data.inv.T1lambda));
1058     case {'lambdaT1min','lambdaT1max','lambdaT1N'}
1059         data.regu.lambdaT1min = str2double(get(gui.edit_handles.lambdaT1min,'String'));
1060         data.regu.lambdaT1max = str2double(get(gui.edit_handles.lambdaT1max,'String'));
1061         data.regu.lambdaT1N = str2double(get(gui.edit_handles.lambdaT1N,'String'));
1062     case {'lambdaT2min','lambdaT2max','lambdaT2N'}
1063         data.regu.lambdaT2min = str2double(get(gui.edit_handles.lambdaT2min,'String'));
1064         data.regu.lambdaT2max = str2double(get(gui.edit_handles.lambdaT2max,'String'));
1065         data.regu.lambdaT2N = str2double(get(gui.edit_handles.lambdaT2N,'String'));
1066     case {'T1min','T1max','T2min','T2max'}
1067         data.info.T1min = str2double(get(gui.edit_handles.T1min,'String'));
1068         data.info.T1max = str2double(get(gui.edit_handles.T1max,'String'));
1069         data.info.T2min = str2double(get(gui.edit_handles.T2min,'String'));
1070         data.info.T2max = str2double(get(gui.edit_handles.T2max,'String'));
1071         % update GUI data
1072         setappdata(figh,'data',data);
1073         tv_getTLGM(figh);
1074         data = getappdata(figh,'data');
1075         tv_plotResults(figh);
1076         beautifyAxes(figh);
1077 end
1078
1079 % update GUI data
1080 setappdata(figh,'data',data);
1081 tv_checkLSEparams(data);
1082 % in case an error occurred, reset the RUN buttons
1083 set(gui.push_handles.run_inv,'String','RUN 2D INV',...
1084     'BackgroundColor','g','Enable','on','Callback',@tv_onPushRun);
1085 set(gui.push_handles.run_2dlcurve,'String','CALC 2D L-CURVE',...
1086     'BackgroundColor','g','Enable','on','Callback',@tv_onPush2DLCURVE);
1087 setappdata(figh,'gui',gui);
1088 end
1089
1090 %% subfunction to set the T1 type
1091 function tv_onPopupT1Type(src,~)
1092 figh = ancestor(src,'figure','toplevel');
1093 data = getappdata(figh,'data');
1094 gui = getappdata(figh,'gui');
1095
1096 switch get(src,'Value')
1097     case 1 % Saturation Recovery
1098         data.inv.T1IRfac = 1;
1099         set(gui.popup_handles.IRtype,'Enable','off');
1100     case 2 % Inversion Recovery
1101         data.inv.T1IRfac = 2;
1102         set(gui.popup_handles.IRtype,'Enable','on');
1103 end
1104
1105 % update GUI data
1106 setappdata(figh,'data',data);
1107 setappdata(figh,'gui',gui);
1108 end
1109
1110 %% subfunction to set the IR type
1111 function tv_onPopupIRType(src,~)
1112 figh = ancestor(src,'figure','toplevel');
1113 data = getappdata(figh,'data');
1114
1115 switch get(src,'Value')
1116     case 1 % IR standard 1-2exp()
1117         data.inv.IRtype = 1;
1118     case 2 % IR Hürlimann -exp()
1119         data.inv.IRtype = 2;
1120 end
1121
1122 % update GUI data
1123 setappdata(figh,'data',data);
1124 end
1125
1126 %% subfunction to set the regularization method
1127 function tv_onPopupRegType(src,~)
1128 figh = ancestor(src,'figure','toplevel');
1129 data = getappdata(figh,'data');
1130 gui = getappdata(figh,'gui');
1131
1132 switch get(src,'Value')
1133     case 1 % manual
1134         data.inv.regtype = 'manual';
1135         set(gui.check_handles.linking,'Enable','on','Value',0);
1136         set(gui.edit_handles.lambdaT1,'Enable','on');
1137         set(gui.edit_handles.lambdaT2,'Enable','on');
1138     case 2 % tikhonov
1139         data.inv.regtype = 'gcv_tikh';
1140         set(gui.check_handles.linking,'Enable','off','Value',0);
1141         set(gui.edit_handles.lambdaFactor,'Enable','off');
1142         set(gui.edit_handles.lambdaT1,'Enable','off');
1143         set(gui.edit_handles.lambdaT2,'Enable','off');
1144     case 3 % tikhonov
1145         data.inv.regtype = 'gcv_trunc';
1146         set(gui.check_handles.linking,'Enable','off','Value',0);
1147         set(gui.edit_handles.lambdaFactor,'Enable','off');
1148         set(gui.edit_handles.lambdaT1,'Enable','off');
1149         set(gui.edit_handles.lambdaT2,'Enable','off');
1150     case 4 % tikhonov
1151         data.inv.regtype = 'gcv_damp';
1152         set(gui.check_handles.linking,'Enable','off','Value',0);
1153         set(gui.edit_handles.lambdaFactor,'Enable','off');
1154         set(gui.edit_handles.lambdaT1,'Enable','off');
1155         set(gui.edit_handles.lambdaT2,'Enable','off');
1156     case 5 % tikhonov
1157         data.inv.regtype = 'discrep';
1158         set(gui.check_handles.linking,'Enable','off','Value',0);
1159         set(gui.edit_handles.lambdaFactor,'Enable','off');
1160         set(gui.edit_handles.lambdaT1,'Enable','off');
1161         set(gui.edit_handles.lambdaT2,'Enable','off');
1162 end
1163 data.regu.linkLambdas = 0;
1164
1165 % activate / deactivate experimental 2d l-curve
1166 switch get(src,'Value')
1167     case 1 % manual
1168         set(gui.edit_handles.lambdaT1min,'Enable','on');
1169         set(gui.edit_handles.lambdaT1max,'Enable','on');
1170         set(gui.edit_handles.lambdaT1N,'Enable','on');
1171         set(gui.edit_handles.lambdaT2min,'Enable','on');
1172         set(gui.edit_handles.lambdaT2max,'Enable','on');
1173         set(gui.edit_handles.lambdaT2N,'Enable','on');
1174         set(gui.push_handles.run_2dlcurve,'Enable','on');
1175     otherwise
1176         set(gui.edit_handles.lambdaT1min,'Enable','off');
1177         set(gui.edit_handles.lambdaT1max,'Enable','off');
1178         set(gui.edit_handles.lambdaT1N,'Enable','off');
1179         set(gui.edit_handles.lambdaT2min,'Enable','off');
1180         set(gui.edit_handles.lambdaT2max,'Enable','off');
1181         set(gui.edit_handles.lambdaT2N,'Enable','off');
1182         set(gui.push_handles.run_2dlcurve,'Enable','off');
1183 end
1184
1185 % update GUI data
1186 setappdata(figh,'data',data);
1187 setappdata(figh,'gui',gui);
1188 tv_checkLSEparams(data);
1189 end
1190
1191 %% subfunction to start a new 2D inversion
1192 function tv_onPushRun(src,~)
1193 figh = ancestor(src,'figure','toplevel');
1194 gui = getappdata(figh,'gui');
1195 data = getappdata(figh,'data');
1196 % NUCLEUSinv data
1197 guiN = getappdata(gui.figh_nucleus,'gui');
1198 dataN = getappdata(gui.figh_nucleus,'data');
1199
1200 % prepare all data for the inversion
1201 [dat,param] = tv_prepareInvData(figh);
1202 param.EchoFlag = dataN.info.EchoFlag;
1203
1204 % status bar information
1205 switch dataN.info.solver
1206     case 'lsqlin'
1207         infostring = '2D Inversion using ''Optimization Toolbox'' ... ';
1208     case 'lsqnonneg'
1209         infostring = '2D Inversion using ''lsqnonneg'' ... ';
1210 end
1211 displayStatusText(guiN,infostring);
1212
1213 % disable the RUN button to indicate a running inversion
1214 set(gui.push_handles.run_inv,'String','RUNNING ...',...
1215     'Enable','off'); pause(0.01);
1216
1217 tic;
1218 % call 2D inversion
1219 inv2D = fitData2D(dat,param);
1220 runtime = toc;
1221 displayStatusText(guiN,[infostring,'done | inversion took ',...
1222     sprintf('%5.2f',runtime),' s']);
1223
1224 % enable the RUN button
1225 set(gui.push_handles.run_inv,'String','RUN 2D INV',...
1226     'BackgroundColor','g','Enable','on','Callback',@tv_onPushRun);
1227 setappdata(figh,'gui',gui);
1228
1229 % save results
1230 data.results.inv2D = inv2D;
1231
1232 % update new lambda in GUI
1233 data.inv.T1lambda = inv2D.lambda_out(2); % T1 is second dimension
1234 data.inv.T2lambda = inv2D.lambda_out(1); % T2 is first dimension
1235 set(gui.edit_handles.lambdaT1,'String',sprintf('%5.4f',inv2D.lambda_out(2)));
1236 set(gui.edit_handles.lambdaT2,'String',sprintf('%5.4f',inv2D.lambda_out(1)));
1237
1238 % update data
1239 setappdata(figh,'data',data);
1240
1241 % plot all 2D inversion data
1242 tv_getTLGM(figh);
1243 tv_plotResults(figh);
1244 beautifyAxes(figh);
1245 set(gui.check_handles.dcm,'Enable','on');
1246 set(gui.popup_handles.cbarpos,'Enable','on');
1247 end
1248
1249 %% subfunction to start a new 2D l-curve calculation
1250 function tv_onPush2DLCURVE(src,~)
1251 figh = ancestor(src,'figure','toplevel');
1252 gui = getappdata(figh,'gui');
1253 data = getappdata(figh,'data');
1254 % NUCLEUSinv data
1255 dataN = getappdata(gui.figh_nucleus,'data');
1256 guiN = getappdata(gui.figh_nucleus,'gui');
1257
1258 set(gui.rightPanel,'Selection',1);
1259 % clear the temporay axis
1260 clearSingleAxis(gui.axes13);
1261 clearSingleAxis(gui.axes14);
1262
1263 % prepare all data for the inversion
1264 [dat,param] = tv_prepareInvData(figh);
1265 param.EchoFlag = dataN.info.EchoFlag;
1266
1267 % status bar information
1268 switch dataN.info.solver
1269     case 'lsqlin'
1270         infostring = '2D L-curve using ''Optimization Toolbox'' ... ';
1271     case 'lsqnonneg'
1272         infostring = '2D L-curve using ''lsqnonneg'' ... ';
1273 end
1274 displayStatusText(guiN,infostring);
1275
1276 % disable the RUN button to indicate a running inversion
1277 set(gui.push_handles.run_2dlcurve,'String','RUNNING ...',...
1278     'BackgroundColor',get(gui.push_handles.update,'BackgroundColor'),...
1279     'Enable','off'); pause(0.01);
1280
1281 if data.regu.linkLambdas
1282
1283     tic;
1284     % lambda link factor
1285     lparam.lambdaFactor = data.regu.lambdaFactor;
1286     % data
1287     lparam.data = dat;
1288     % fit function
1289     lparam.func = @fitData2D;
1290     % dimension
1291     lparam.dim = 2;
1292     switch dataN.info.LcurveMethod
1293         case 'iterative'
1294             lparam.lambda_range = [data.regu.lambdaT2min data.regu.lambdaT2max];
1295             % call L-curve function
1296             lc = runLcurveIterative(lparam,param,guiN);
1297         case 'discrete'
1298             lparam.lambda_range = logspace(log10(data.regu.lambdaT2min),...
1299                 log10(data.regu.lambdaT2max),data.regu.lambdaT2N);
1300             % call L-curve function
1301             lc = runLcurveDiscrete(lparam,param,guiN);
1302     end
1303     runtime = toc;
1304     % output to command line
1305     displayStatusText(1,[infostring,'done | calculation took ',...
1306         sprintf('%5.2f',runtime),' s']);
1307
1308     % enable the RUN button
1309             set(gui.push_handles.run_2dlcurve,'String','CALC 2D L-CURVE',...
1310                 'BackgroundColor','g','Enable','on','Callback',@tv_onPush2DLCURVE);
1311             setappdata(figh,'gui',gui);
1312
1313     lamT2 = lc.lambda(lc.index);
1314     lamT1 = data.regu.lambdaFactor*lamT2;
1315
1316     % set the optimal lambdas in the GUI
1317     set(gui.edit_handles.lambdaT1,'String',num2str(lamT1));
1318     set(gui.edit_handles.lambdaT2,'String',num2str(lamT2));
1319     data.inv.T1lambda = lamT1;
1320     data.inv.T2lambda = lamT2;
1321
1322     % opening the export figure
1323     expfig = figure('Color',gui.myui.colors.panelBG);
1324     ax1 = subplot(121,'Parent',expfig); ax2 = subplot(122,'Parent',expfig);
1325     hold(ax1,'on'); hold(ax2,'on');
1326
1327     xlims = [min(lc.RN)/2 max(lc.RN)*2];
1328     ylims = [min(lc.XN)/2 max(lc.XN)*2];
1329     loglog(lc.RN,lc.XN,'o-','Parent',ax1);
1330     loglog(lc.RN(lc.index),lc.XN(lc.index),'r+','Parent',ax1);
1331     set(ax1,'XScale','log','YScale','log','XLim',xlims,'YLim',ylims);
1332     set(get(ax1,'XLabel'),'String','residual norm |Gm-d|_{2}');
1333     set(get(ax1,'YLabel'),'String','model norm |Lm|_{2}');
1334     set(get(ax1,'Title'),'String','L-curve');
1335
1336     xlims = [min(lc.lambda)/2 max(lc.lambda)*2];
1337     ylims = [0 max(lc.RMS)*1.1];
1338     semilogx(lc.lambda,lc.RMS,'o-','Parent',ax2);
1339     semilogx(lc.lambda(lc.index),lc.RMS(lc.index),'r+','Parent',ax2);
1340     plot(xlims,[1 1],'k--','Parent',ax2);
1341     set(ax2,'XScale','log','XLim',xlims,'YLim',ylims);
1342     set(get(ax2,'XLabel'),'String','regularization parameter \lambda');
1343     set(get(ax2,'YLabel'),'String','noise weighted error \chi^2');
1344     set(get(ax2,'Title'),'String',['\lambda_{T1} = ',...
1345         sprintf('%3.2f',data.regu.lambdaFactor),'\lambda_{T2}']);
1346
1347 else
1348
1349     T1lam_range = logspace(log10(data.regu.lambdaT1min),...
1350         log10(data.regu.lambdaT1max),data.regu.lambdaT1N);
1351     T2lam_range = logspace(log10(data.regu.lambdaT2min),...
1352         log10(data.regu.lambdaT2max),data.regu.lambdaT2N);
1353     [tmp.LL1,tmp.LL2] = meshgrid(T1lam_range,T2lam_range);
1354
1355     tic;
1356     % call 2D inversions
1357     tmp.rnorm_2d = zeros(numel(T1lam_range),numel(T2lam_range));
1358     tmp.mnorm_2d = zeros(numel(T1lam_range),numel(T2lam_range));
1359     for l1 = 1:numel(T1lam_range)
1360         for l2 = 1:numel(T2lam_range)
1361             disp(['NUCLEUSinv 2D L-curve - lambda T1: ',num2str(l1),'/',num2str(numel(T1lam_range)),...
1362                 ' lambda T2: ',num2str(l2),'/',num2str(numel(T2lam_range))]);
1363             % call inversion
1364             param.lamT1 = T1lam_range(l1);
1365             param.lamT2 = T2lam_range(l2);
1366             inv2D_tmp = fitData2D(dat,param);
1367             % save norms
1368             tmp.rnorm_2d(l1,l2) = inv2D_tmp.rn;
1369             tmp.mnorm_2d(l1,l2) = inv2D_tmp.xn;
1370             % plot update
1371             tv_plotLCurveUpdate(figh,tmp,'update');
1372             pause(0.001);
1373         end
1374     end
1375     runtime = toc;
1376     tv_plotLCurveUpdate(figh,tmp,'final');
1377
1378     % output to command line
1379     displayStatusText(1,[infostring,'done | calculation took ',...
1380         sprintf('%5.2f',runtime),' s']);
1381
1382     % enable the RUN button
1383     set(gui.push_handles.run_2dlcurve,'String','CALC 2D L-CURVE',...
1384         'BackgroundColor','g','Enable','on','Callback',@tv_onPush2DLCURVE);
1385     setappdata(figh,'gui',gui);
1386
1387     % get the "optimal" lambda combination - brute force
1388     dd = tmp.rnorm_2d - min(tmp.rnorm_2d(:));
1389     mm = tmp.mnorm_2d - min(tmp.mnorm_2d(:));
1390     dd = dd./max(dd(:));
1391     mm = mm./max(mm(:));
1392     ss1 = dd + mm;
1393     ss2 = abs(dd - mm);
1394     mask1 = ss1 == min(ss1(:)); mask2 = ss2 == min(ss2(:));
1395     lamT1(1) = tmp.LL1(mask1'); lamT2(1) = tmp.LL2(mask1');
1396     lamT1(2) = tmp.LL1(mask2'); lamT2(2) = tmp.LL2(mask2');
1397
1398     % index = getLambdaFromLCurve(diag(tmp.rnorm_2d),diag(tmp.mnorm_2d),1);
1399     % index = getLambdaFromLCurve(diag(rr),diag(mm),1);
1400     % lamT1 = T2lam_range(index);
1401     % lamT2 = T2lam_range(index);
1402
1403     % extent matrices for plotting
1404     SS1 = [ss1(1,:);ss1];
1405     SS1 = [SS1(:,1) SS1];
1406     SS2 = [ss2(1,:);ss2];
1407     SS2 = [SS2(:,1) SS2];
1408
1409     % opening the export figure
1410     expfig = figure('Color',gui.myui.colors.panelBG);
1411     ax1 = subplot(221,'Parent',expfig); ax2 = subplot(222,'Parent',expfig);
1412     ax3 = subplot(223,'Parent',expfig); ax4 = subplot(224,'Parent',expfig);
1413     pos1 = get(ax1,'Position'); pos2 = get(ax2,'Position');
1414     pos3 = get(ax3,'Position'); pos4 = get(ax4,'Position');
1415     delete(ax1); delete(ax2);
1416     delete(ax3); delete(ax4);
1417     ax1 = copyobj(gui.axes13,expfig); ax2 = copyobj(gui.axes14,expfig);
1418     set(ax1,'Position',pos1); hold(ax1,'on'); colorbar(ax1);
1419     set(ax2,'Position',pos2); hold(ax2,'on'); colorbar(ax2);
1420     ax3 = copyobj(gui.axes13,expfig); set(ax3,'Position',pos3);
1421     ax4 = copyobj(gui.axes14,expfig); set(ax4,'Position',pos4);
1422     set(get(ax3,'Children'),'CData',SS1'); hold(ax3,'on');
1423     set(get(ax4,'Children'),'CData',SS2'); hold(ax4,'on');
1424
1425     plot(lamT1(1),lamT2(1),'rx','MarkerSize',8,'Parent',ax3);
1426     plot(lamT1(2),lamT2(2),'rx','MarkerSize',8,'Parent',ax4);
1427     axis([ax1 ax2 ax3 ax4],'square');
1428     set(get(ax3,'Title'),'String','d + m');
1429     set(get(ax4,'Title'),'String','abs(d - m)');
1430     colorbar(ax3); colorbar(ax4);
1431
1432     % save results
1433     data.results.lcurve.T1lam_range = T1lam_range;
1434     data.results.lcurve.T2lam_range = T2lam_range;
1435     data.results.lcurve.rnorm = tmp.rnorm_2d;
1436     data.results.lcurve.mnorm = tmp.mnorm_2d;
1437     data.results.lcurve.lamT1 = lamT1;
1438     data.results.lcurve.lamT2 = lamT2;
1439
1440     % set the optimal lambdas in the GUI
1441     set(gui.edit_handles.lambdaT1,'String',num2str(min(lamT1)));
1442     set(gui.edit_handles.lambdaT2,'String',num2str(min(lamT2)));
1443     data.inv.T1lambda = min(lamT1);
1444     data.inv.T2lambda = min(lamT2);
1445 end
1446
1447 % update data
1448 setappdata(figh,'data',data);
1449 setappdata(figh,'gui',gui);
1450
1451 % call final inverion with optimal lambda
1452 tv_onPushRun(gui.push_handles.run_inv);
1453 end
1454
1455 %% subfuntion to prepare inversion data
1456 function [dat,param] = tv_prepareInvData(figh)
1457 gui = getappdata(figh,'gui');
1458 data = getappdata(figh,'data');
1459 % NUCLEUSinv data
1460 dataN = getappdata(gui.figh_nucleus,'data');
1461 % local T1T2 data
1462 T1T2map = data.results.T1T2map;
1463
1464 % prepare inversion parameter struct
1465 param.T1T2 = 'T1T2'; % T1-T2 2D inv
1466
1467 % get system properties
1468 param.D = data.prop.D;
1469 param.G0 = data.prop.G0;
1470 param.te = data.prop.te;
1471
1472 % IR/SR factor
1473 param.T1IRfac = data.inv.T1IRfac;
1474 param.IRtype = data.inv.IRtype;
1475
1476 % get T1/T2 RTDs values
1477 param.T1min = data.inv.T1min;
1478 param.T1max = data.inv.T1max;
1479 param.T1N = data.inv.T1N;
1480 param.T2min = data.inv.T2min;
1481 param.T2max = data.inv.T2max;
1482 param.T2N = data.inv.T2N;
1483
1484 % inversion/regularization settings
1485 param.regMethod = data.inv.regtype;
1486 param.lamT1 = data.inv.T1lambda;
1487 param.lamT2 = data.inv.T2lambda;
1488 param.orderT1 = data.inv.T1order;
1489 param.orderT2 = data.inv.T2order;
1490
1491 % prepare data
1492 dat = struct;
1493 for n = 1:numel(T1T2map.t_recov)
1494     if data.prop.useLogGates
1495         dat(n).t = T1T2map.t2_gate;
1496     else
1497         dat(n).t = T1T2map.t2;
1498     end
1499     dat(n).s = real(T1T2map.dcube(n,:))';
1500     dat(n).e = T1T2map.ecube(n,:)';
1501     dat(n).noise = T1T2map.noise(n);%std(T1T2map.ecube(n,:));
1502     dat(n).T1 = T1T2map.t_recov(n);
1503 end
1504 % global noise
1505 param.noise = mean(T1T2map.noise);
1506 param.useLogGates = data.prop.useLogGates;
1507
1508 % take solver from main NUCLEUS GUI
1509 param.solver = dataN.info.solver;
1510 switch dataN.info.InvInfo
1511     case 'on'
1512         param.info = 'final';
1513     case 'off'
1514         param.info = 'off';
1515 end
1516
1517 end
1518
1519 %% subfunction to export the 2D inversion data
1520 function tv_onPushSave(src,~)
1521 figh = ancestor(src,'figure','toplevel');
1522 % local GUI data
1523 uvgui = getappdata(figh,'gui');
1524 uvdata = getappdata(figh,'data');
1525 % NUCLEUSinv data
1526 data = getappdata(uvgui.figh_nucleus,'data');
1527
1528 % get data path to save inversion results
1529 [sfile,spath] = uiputfile('*.mat','Select File for Save',...
1530     fullfile(data.import.path,'2Dinvdata.mat'));
1531 % if user did not cancel, procceed
1532 if sfile > 0
1533     invdata = uvdata;
1534     save(fullfile(spath,sfile),'invdata');
1535     disp('2D Inverions data saved to: ');
1536     disp(fullfile(spath,sfile));
1537 else
1538     disp('Save cancelled.');
1539 end
1540
1541 end
1542
1543 %% subfunction to export the current view to a figure
1544 function tv_onPushView(src,~)
1545 figh = ancestor(src,'figure','toplevel');
1546 % local GUI data
1547 gui = getappdata(figh,'gui');
1548
1549 % opening the export figure
1550 expfig = figure('Color',gui.myui.colors.panelBG);
1551
1552 % create axes layout depending on view
1553 switch get(gui.rightPanel,'Selection')
1554     case 1
1555         % create layout
1556         ax1 = subplot(2,2,1,'Parent',expfig);
1557         ax2 = subplot(2,2,2,'Parent',expfig);
1558         ax3 = subplot(2,2,3,'Parent',expfig);
1559         ax4 = subplot(2,2,4,'Parent',expfig);
1560         % get positions
1561         pos1 = get(ax1,'Position');
1562         pos2 = get(ax2,'Position');
1563         pos3 = get(ax3,'Position');
1564         pos4 = get(ax4,'Position');
1565         % delete axes
1566         delete(ax1);delete(ax2);delete(ax3);delete(ax4);
1567         % copy GUI axes
1568         ax1 = copyobj(gui.axes11,expfig);
1569         ax2 = copyobj(gui.axes12,expfig);
1570         ax3 = copyobj(gui.axes13,expfig);
1571         ax4 = copyobj(gui.axes14,expfig);
1572         % adjust positions
1573         set(ax1,'Position',pos1);
1574         set(ax2,'Position',pos2);
1575         set(ax3,'Position',pos3);
1576         set(ax4,'Position',pos4);
1577         % set colorbars
1578         colorbar(ax1,'Location','EastOutside');
1579         colorbar(ax2,'Location','EastOutside');
1580         colorbar(ax3,'Location','EastOutside');
1581         colorbar(ax4,'Location','EastOutside');
1582     case 2
1583         % create layout
1584         ax1 = subplot(5,5,[1 2 3 4],'Parent',expfig);
1585         ax2 = subplot(5,5,[6:9 11:14 16:19 21:24],'Parent',expfig);
1586         ax3 = subplot(5,5,[10 15 20 25],'Parent',expfig);
1587         % get positions
1588         pos1 = get(ax1,'Position');
1589         pos2 = get(ax2,'Position');
1590         pos3 = get(ax3,'Position');
1591         % delete axes
1592         delete(ax1);delete(ax2);delete(ax3);
1593         % copy GUI axes
1594         ax1 = copyobj(gui.axes21,expfig);
1595         ax2 = copyobj(gui.axes2,expfig);
1596         ax3 = copyobj(gui.axes24,expfig);
1597         % adjust positions
1598         set(ax1,'Position',pos1);
1599         set(ax2,'Position',pos2);
1600         set(ax3,'Position',pos3);
1601     case 3
1602         % create layout
1603         ax1 = subplot(7,1,[1 2],'Parent',expfig);
1604         ax2 = subplot(7,1,[4 5 6 7],'Parent',expfig);
1605         % get positions
1606         pos1 = get(ax1,'Position');
1607         pos2 = get(ax2,'Position');
1608         % delete axes
1609         delete(ax1);delete(ax2);
1610         % copy GUI axes
1611         ax1 = copyobj(gui.axes31,expfig);
1612         ax2 = copyobj(gui.axes32,expfig);
1613         % adjust positions
1614         set(ax1,'Position',pos1);
1615         set(ax2,'Position',pos2);
1616 end
1617
1618 end
1619
1620 %% subfunction to update the main NUCLEUSinv GUI
1621 function tv_onPushUpdate(src,~)
1622 figh = ancestor(src,'figure','toplevel');
1623 % local GUI data
1624 uvgui = getappdata(figh,'gui');
1625 uvdata = getappdata(figh,'data');
1626 % NUCLEUSinv data
1627 gui = getappdata(uvgui.figh_nucleus,'gui');
1628 INVdata = getappdata(uvgui.figh_nucleus,'INVdata');
1629 data = getappdata(uvgui.figh_nucleus,'data');
1630
1631 % loop over all signals
1632 E_inv = zeros(size(uvdata.results.T1T2map.t_recov));
1633 firstT1 = uvdata.prop.firstT1;
1634 lastT1 = uvdata.prop.lastT1;
1635 idT1 = firstT1:lastT1;
1636 for id = 1:numel(INVdata)
1637     % the standard INVdata struct
1638     INVdata{id} = [];
1639     local_id = find(id==idT1);
1640
1641     if any(id==idT1) % for all T2 signals not cut out
1642         first = uvdata.prop.firstT2;
1643         last = uvdata.prop.lastT2;
1644         data.process.start = first;
1645         data.process.end = last;
1646
1647         if uvdata.prop.useLogGates
1648             data.process.gatetype = 'log';
1649             data.process.isgated = true;
1650         else
1651             data.process.gatetype = 'raw';
1652             data.process.isgated = false;
1653         end
1654
1655         % update 2Dinv GUI settings
1656         data.inv2D.prop = uvdata.prop;
1657         data.inv2D.inv = uvdata.inv;
1658         data.inv2D.info = uvdata.info;
1659
1660         % create raw data struct
1661         data.results.nmrraw.t = uvdata.results.T1T2map.import{id}.time(first:last);
1662         data.results.nmrraw.s = uvdata.results.T1T2map.import{id}.signal(first:last);
1663         data.results.nmrraw.phase = uvdata.results.T1T2map.import{id}.phase;
1664         data.results.nmrproc.T1T2 = 'T2';
1665         data.results.nmrproc.T1IRfac = 1;
1666
1667         % create proc data struct
1668         data.results.nmrproc.start = first;
1669         data.results.nmrproc.end = last;
1670
1671         if uvdata.prop.useLogGates
1672             data.results.nmrproc.gatetype = 'log';
1673             data.results.nmrproc.isgated = true;
1674             data.results.nmrproc.t = uvdata.results.T1T2map.t2_gate(:);
1675             data.results.nmrproc.s = real(uvdata.results.T1T2map.dcube(local_id,:))';
1676             data.results.nmrproc.N = uvdata.results.T1T2map.t2_gateN(:);
1677
1678             data.results.nmrproc.noise = uvdata.results.T1T2map.noise(local_id);
1679             data.results.nmrproc.e = uvdata.results.inv2D.data(local_id).e;
1680             data.results.nmrproc.W = diag(data.results.nmrproc.e);
1681             ErrWimag = imag(uvdata.results.T1T2map.dcube(local_id,:))./uvdata.results.inv2D.data(local_id).e;
1682             chi2 = sqrt(sum(sum(ErrWimag.^2)))/sqrt(numel(ErrWimag));
1683             data.results.nmrproc.imag_chi2 = chi2;
1684         else
1685             data.results.nmrproc.gatetype = 'raw';
1686             data.results.nmrproc.isgated = false;
1687             data.results.nmrproc.t = uvdata.results.T1T2map.import{id}.time(first:last);
1688             data.results.nmrproc.s = real(uvdata.results.T1T2map.import{id}.signal(first:last));
1689             data.results.nmrproc.N = ones(size(data.results.nmrproc.s));
1690
1691             if isfield(uvdata.results.T1T2map.import{id},'noise')
1692                 data.results.nmrproc.noise = uvdata.results.T1T2map.import{id}.noise;
1693             else
1694                 range = floor(numel(data.results.nmrproc.s)/2):numel(data.results.nmrproc.s);
1695                 data.results.nmrproc.noise = std(imag(uvdata.results.T1T2map.import{id}.signal(range)));
1696             end
1697             data.results.nmrproc.e = data.results.nmrproc.noise*ones(size(data.results.nmrproc.s));
1698             if isfield(data.results.nmrproc,'W')
1699                 data.results.nmrproc = rmfield(data.results.nmrproc,'W');
1700             end
1701             ErrWimag = imag(uvdata.results.T1T2map.import{id}.signal(first:last))./data.results.nmrproc.noise;
1702             chi2 = sqrt(sum(sum(ErrWimag.^2)))/sqrt(numel(ErrWimag));
1703             data.results.nmrproc.imag_chi2 = chi2;
1704         end
1705
1706         INVdata{id} = data;
1707         INVdata{id} = rmfield(INVdata{id},'import');
1708         INVdata{id} = rmfield(INVdata{id},'info');
1709         INVdata{id} = rmfield(INVdata{id},'calib');
1710         INVdata{id} = rmfield(INVdata{id},'pressure');
1711
1712         % now add a dummy "invstd" field
1713         INVdata{id}.results.invstd.fit_t = uvdata.results.inv2D.data(local_id).t;
1714         INVdata{id}.results.invstd.fit_s = uvdata.results.inv2D.data(local_id).s_fit;
1715         E_inv(id,1) = uvdata.results.inv2D.data(local_id).s_fit(1);
1716         INVdata{id}.results.invstd.E0 = uvdata.results.inv2D.data(local_id).s_fit(1);
1717         INVdata{id}.results.invstd.ciE0 = NaN;
1718         INVdata{id}.results.invstd.resnorm = uvdata.results.inv2D.data(local_id).resnorm;
1719         INVdata{id}.results.invstd.residual = uvdata.results.inv2D.data(local_id).residual;
1720         INVdata{id}.results.invstd.chi2 = uvdata.results.inv2D.data(local_id).chi2;
1721         INVdata{id}.results.invstd.rms = uvdata.results.inv2D.data(local_id).rms;
1722
1723         INVdata{id}.results.invstd.lambda_out = 1;
1724         INVdata{id}.results.invstd.xn = 0;
1725         INVdata{id}.results.invstd.rn = 0;
1726         INVdata{id}.results.invstd.invtype = data.invstd.invtype;
1727         INVdata{id}.results.invstd.invparams = NaN;
1728
1729         INVdata{id}.results.inv2D = true;
1730
1731         % color the corresponding list entries in the main GUI
1732         strL = get(gui.listbox_handles.signal,'String');
1733         str1 = strL{id};
1734         str2 = ['<HTML><BODY bgcolor="rgb(',...
1735             sprintf('%d,%d,%d',gui.myui.colors.listINV.*255),')">',str1,'</BODY></HTML>'];
1736         strL{id} = str2;
1737         set(gui.listbox_handles.signal,'String',strL);
1738     end
1739
1740     if id == numel(INVdata) % for the merged T1 curve
1741         % data.process.start = 1;
1742         % data.process.end = numel(uvdata.results.T1T2map.import{id}.time);
1743         data.process.start = firstT1;
1744         data.process.end = lastT1;
1745
1746         data.process.gatetype = 'raw';
1747         data.process.isgated = false;
1748
1749         % update 2Dinv GUI settings
1750         data.inv2D.prop = uvdata.prop;
1751         data.inv2D.inv = uvdata.inv;
1752         data.inv2D.info = uvdata.info;
1753
1754         % create raw data struct
1755         data.results.nmrraw.t = uvdata.results.T1T2map.import{id}.time(firstT1:lastT1);
1756         data.results.nmrraw.s = uvdata.results.T1T2map.import{id}.signal(firstT1:lastT1);
1757         data.results.nmrraw.noise = uvdata.results.T1T2map.import{id}.noise;
1758         data.results.nmrproc.T1T2 = 'T1';
1759         data.results.nmrproc.T1IRfac = 2;
1760
1761         % create proc data struct
1762         data.results.nmrproc.start = firstT1;
1763         data.results.nmrproc.end = lastT1;
1764
1765         data.results.nmrproc.gatetype = 'raw';
1766         data.results.nmrproc.isgated = false;
1767         data.results.nmrproc.t = uvdata.results.T1T2map.import{id}.time(data.results.nmrproc.start:data.results.nmrproc.end);
1768         data.results.nmrproc.s = real(uvdata.results.T1T2map.import{id}.signal(data.results.nmrproc.start:data.results.nmrproc.end));
1769         data.results.nmrproc.N = ones(size(data.results.nmrproc.s));
1770
1771         if isfield(uvdata.results.T1T2map.import{id},'noise')
1772             data.results.nmrproc.noise = uvdata.results.T1T2map.import{id}.noise;
1773         else
1774             range = floor(numel(data.results.nmrproc.s)/2):numel(data.results.nmrproc.s);
1775             data.results.nmrproc.noise = std(imag(uvdata.results.T1T2map.import{id}.signal(range)));
1776         end
1777         data.results.nmrproc.e = data.results.nmrproc.noise*ones(size(data.results.nmrproc.s));
1778         if isfield(data.results.nmrproc,'W')
1779             data.results.nmrproc = rmfield(data.results.nmrproc,'W');
1780         end
1781
1782         INVdata{id} = data;
1783         INVdata{id} = rmfield(INVdata{id},'import');
1784         INVdata{id} = rmfield(INVdata{id},'info');
1785         INVdata{id} = rmfield(INVdata{id},'calib');
1786         INVdata{id} = rmfield(INVdata{id},'pressure');
1787
1788         % now add a dummy "invstd" field
1789         E_inv = E_inv(firstT1:lastT1);
1790         INVdata{id}.results.invstd.fit_t = uvdata.results.T1T2map.t_recov;
1791         INVdata{id}.results.invstd.fit_s = E_inv;
1792         INVdata{id}.results.invstd.E0 = uvdata.results.inv2D.E0;
1793         INVdata{id}.results.invstd.ciE0 = NaN;
1794         out = getFitErrors(uvdata.results.T1T2map.E_raw(:,1),E_inv,data.results.nmrproc.noise);
1795         INVdata{id}.results.invstd.resnorm = out.resnorm;
1796         INVdata{id}.results.invstd.residual = out.residual;
1797         INVdata{id}.results.invstd.chi2 = out.chi2;
1798         INVdata{id}.results.invstd.rms = out.rms;
1799
1800         INVdata{id}.results.invstd.lambda_out = 1;
1801         INVdata{id}.results.invstd.xn = 0;
1802         INVdata{id}.results.invstd.rn = 0;
1803         INVdata{id}.results.invstd.invtype = data.invstd.invtype;
1804         INVdata{id}.results.invstd.invparams = NaN;
1805
1806         INVdata{id}.results.inv2D = uvdata.results.inv2D;
1807
1808         % color the corresponding list entries in the main GUI
1809         strL = get(gui.listbox_handles.signal,'String');
1810         str1 = strL{id};
1811         str2 = ['<HTML><BODY bgcolor="rgb(',...
1812             sprintf('%d,%d,%d',gui.myui.colors.listINV.*255),')">',str1,'</BODY></HTML>'];
1813         strL{id} = str2;
1814         set(gui.listbox_handles.signal,'String',strL);
1815     end
1816 end
1817
1818 % update GUI INVdata
1819 setappdata(uvgui.figh_nucleus,'INVdata',INVdata);
1820
1821 % set focus on first signal
1822 set(gui.listbox_handles.signal,'Value',1);
1823 onListboxData(gui.listbox_handles.signal);
1824 end
1825
1826 %% subfunction to switch x-axis scaling
1827 function tv_onRadioLogLin(src,~)
1828 figh = ancestor(src,'figure','toplevel');
1829 gui = getappdata(figh,'gui');
1830 % get tag of the radio menu
1831 tag = get(src,'Tag');
1832 val = get(src,'Value');
1833
1834 switch tag
1835     case 'log'
1836         switch val
1837             case 1 % log should be used
1838                 set(gui.radio_handles.lin,'Value',0);
1839             case 0 % lin should be used
1840                 set(gui.radio_handles.lin,'Value',1);
1841         end
1842     case 'lin'
1843         switch val
1844             case 1 % lin should be used
1845                 set(gui.radio_handles.log,'Value',0);
1846             case 0 % log should be used
1847                 set(gui.radio_handles.log,'Value',1);
1848         end
1849 end
1850 % update GUI data
1851 setappdata(figh,'gui',gui);
1852
1853 % call function to adapt the axes scaling
1854 tv_setAxesScaling(figh);
1855 end
1856
1857 %% subfunction to activate data tips on 2D plot
1858 function tv_onCheckDCM(src,~)
1859 figh = ancestor(src,'figure','toplevel');
1860 gui = getappdata(figh,'gui');
1861 % get tag of the radio menu
1862 val = get(src,'Value');
1863
1864 switch val
1865     case 1 % DCM on
1866         gui.dcm.Enable = 'on';
1867     case 0 % DCM off
1868         gui.dcm.Enable = 'off';
1869 end
1870
1871 % update GUI data
1872 setappdata(figh,'gui',gui);
1873
1874 end
1875
1876 %% subfunction to export the 2D inversion data
1877 function tv_onPopupCbar(src,~)
1878 figh = ancestor(src,'figure','toplevel');
1879 tv_plotResults(figh)
1880 end
1881
1882 %% subfunction to switch x-axis scaling log<->lin
1883 function tv_setAxesScaling(figh)
1884 gui = getappdata(figh,'gui');
1885
1886 uselog = get(gui.radio_handles.log,'Value');
1887 switch uselog
1888     case 1
1889         set(gui.axes11,'XScale','log');
1890         set(gui.axes12,'XScale','log');
1891         set(gui.axes13,'XScale','log');
1892         set(gui.axes14,'XScale','log');
1893         log_t_ticks = logspace(-5,2,8);
1894         set(gui.axes32,'XScale','log','XTick',log_t_ticks);
1895     case 0
1896         set(gui.axes11,'XScale','lin');
1897         set(gui.axes12,'XScale','lin');
1898         set(gui.axes13,'XScale','lin');
1899         set(gui.axes14,'XScale','lin');
1900         set(gui.axes32,'XScale','lin','XTickMode','auto');
1901 end
1902
1903 end
1904
1905 %% subfunction to update the plots during the 2D L-curve calculation
1906 function tv_plotLCurveUpdate(figh,tmp_norm,method)
1907 gui = getappdata(figh,'gui');
1908 % data = getappdata(figh,'data');
1909
1910 % clear the temporay axis
1911 clearSingleAxis(gui.axes13);
1912
1913 L1 = tmp_norm.LL1;
1914 L2 = tmp_norm.LL2;
1915
1916 % extent matrices for plotting
1917 LL1 = [min(L1(:))/1.5.*ones(size(L1,1),1) L1];
1918 LL1 = [LL1(1,:); LL1];
1919 LL2 = [min(L2(:))/1.5.*ones(1,size(L2,2)); L2];
1920 LL2 = [LL2(:,1) LL2];
1921
1922 % get the normdata
1923 % shift to zero
1924 dd = tmp_norm.rnorm_2d - min(tmp_norm.rnorm_2d(:));
1925 mm = tmp_norm.mnorm_2d - min(tmp_norm.mnorm_2d(:));
1926 % scale to one
1927 dd = dd./max(dd(:));
1928 mm = mm./max(mm(:));
1929 % add both norms
1930 % ss = dd + mm;
1931 % ss = abs(dd - mm);
1932 % ss(ss==0) = NaN;
1933 switch method
1934     case 'update'
1935         dd(dd==0) = NaN;
1936         mm(mm==0) = NaN;
1937     otherwise
1938         % nada
1939 end
1940 % extent matrices for plotting
1941 dd1 = [dd(1,:);dd];
1942 dd1 = [dd1(:,1) dd1];
1943 mm1 = [mm(1,:);mm];
1944 mm1 = [mm1(:,1) mm1];
1945 % imagescnan(tmp_norm.LL1,tmp_norm.LL2,ss','Parent',gui.axes13);
1946 imagescnan(LL1,LL2,dd1','Parent',gui.axes13);
1947 imagescnan(LL1,LL2,mm1','Parent',gui.axes14);
1948 colormap(gui.axes14,'parula');
1949 set(get(gui.axes13,'Title'),'String','data norm');
1950 set(get(gui.axes13,'XLabel'),'String','\lambda T1');
1951 set(get(gui.axes13,'YLabel'),'String','\lambda T2');
1952 set(gui.axes13,'XScale','log','YScale','log','YDir','normal');
1953 set(gui.axes13,'XLim',[min(LL1(:)) max(LL1(:))],'YLim',[min(LL2(:)) max(LL2(:))]);
1954 cb = colorbar(gui.axes13);
1955 set(cb,'Location','EastOutside');
1956 set(get(gui.axes14,'Title'),'String','model norm');
1957 set(get(gui.axes14,'XLabel'),'String','\lambda T1');
1958 set(get(gui.axes14,'YLabel'),'String','\lambda T2');
1959 set(gui.axes14,'XScale','log','YScale','log','YDir','normal');
1960 set(gui.axes14,'XLim',[min(LL1(:)) max(LL1(:))],'YLim',[min(LL2(:)) max(LL2(:))]);
1961 cb = colorbar(gui.axes14);
1962 set(cb,'Location','EastOutside');
1963
1964 end
1965
1966 %% subfunction to update all plots
1967 function tv_plotResults(figh)
1968 gui = getappdata(figh,'gui');
1969 data = getappdata(figh,'data');
1970 T1T2map = data.results.T1T2map;
1971 inv2D = data.results.inv2D;
1972 col = gui.myui.colors;
1973
1974 % clear axes
1975 clearSingleAxis(gui.axes13);
1976 clearSingleAxis(gui.axes14);
1977 clearSingleAxis(gui.axes2);
1978 clearSingleAxis(gui.axes21);
1979 clearSingleAxis(gui.axes24);
1980 clearSingleAxis(gui.axes31);
1981 clearSingleAxis(gui.axes32);
1982 hold(gui.axes13,'on');
1983 hold(gui.axes14,'on');
1984 hold(gui.axes2,'on');
1985 hold(gui.axes21,'on');
1986 hold(gui.axes24,'on');
1987 hold(gui.axes31,'on');
1988 hold(gui.axes32,'on');
1989
1990 % get T1/T2 info range from GUI
1991 T1_irange(1) = str2double(get(gui.edit_handles.T1min,'String'));
1992 T1_irange(2) = str2double(get(gui.edit_handles.T1max,'String'));
1993 T2_irange(1) = str2double(get(gui.edit_handles.T2min,'String'));
1994 T2_irange(2) = str2double(get(gui.edit_handles.T2max,'String'));
1995
1996 % create masks for plotting
1997 [TX,TY] = meshgrid(data.results.inv2D.T2vec,data.results.inv2D.T1vec);
1998 mask1 = TY >= T1_irange(1) & TY <= T1_irange(2);
1999 mask2 = TX >= T2_irange(1) & TX <= T2_irange(2);
2000
2001 % define some axes settings
2002 log_t_ticks = logspace(-5,2,8);
2003 t_recov_lims = [min(T1T2map.t_recov)/2 max(T1T2map.t_recov)*2];
2004 p_alpha = 0.8;
2005
2006 if data.prop.useLogGates
2007     t2 = T1T2map.t2_gate;
2008 else
2009     t2 = T1T2map.t2;
2010 end
2011
2012 z_max = max(inv2D.f_2Dmap(:));
2013 % tab 2 - 2D inversion model
2014 [X,Y] = meshgrid(inv2D.T2vec,inv2D.T1vec);
2015 % imagescnan(X,Y,inv2D.f_2Dmap,'Parent',gui.axes2);
2016 sh = surf(X,Y,inv2D.f_2Dmap,'Parent',gui.axes2);
2017 sh.FaceColor = 'flat';
2018 sh.EdgeColor = 'none';
2019 plot3(inv2D.T2tlgm,inv2D.T1tlgm,z_max+1,'o','Color',col.FIT,'Parent',gui.axes2);
2020 plot3(inv2D.T2tmax,inv2D.T1tmax,z_max+1,'+','Color',col.FIT,'Parent',gui.axes2);
2021 plot3([1e-5 100],[1e-5 100],[z_max z_max],...
2022     '--','Color','w','LineWidth',1,'Parent',gui.axes2);
2023 view(gui.axes2,[0 90]);
2024 set(gui.axes2,'XScale','log','XTick',log_t_ticks,...
2025     'XLim',[min(inv2D.T2vec) max(inv2D.T2vec)]);
2026 set(gui.axes2,'YScale','log','XTick',log_t_ticks,...
2027     'YLim',[min(inv2D.T1vec) max(inv2D.T1vec)],'YDir','normal');
2028 set(get(gui.axes2,'XLabel'),'String','relaxation time T2 [s]');
2029 set(get(gui.axes2,'YLabel'),'String','relaxation time T1 [s]');
2030 set(gui.axes2,'Layer','top','XGrid','off','YGrid','off');
2031 % colorbar
2032 switch get(gui.popup_handles.cbarpos,'Value')
2033     case 1
2034         colorbar(gui.axes2,'Location','East','Color','w');
2035     case 2
2036         colorbar(gui.axes2,'Location','EastOutSide','Color','k');
2037     otherwise
2038         % none
2039 end
2040
2041 % sum along each dimension to get both RTDs
2042 mapcol = parula;
2043 Tmap = inv2D.f_2Dmap;
2044 Tmap(~mask1) = 0;
2045 Tmap(~mask2) = 0;
2046 T1rtd = sum(Tmap,2);
2047 T2rtd = sum(Tmap,1);
2048 % find common maximum for y-axis setting
2049 ymax = max([max(T1rtd) max(T2rtd)])*1.1;
2050 % T1 RTD
2051 plot(T1rtd,inv2D.T1vec,'Color',col.FIT,'Parent',gui.axes24);
2052 amp = findApproxTlgmAmplitude(inv2D.T1vec,T1rtd,inv2D.T1tlgm);
2053 plot([0 amp],[inv2D.T1tlgm inv2D.T1tlgm],'Color',col.FIT,'LineStyle','--',...
2054     'LineWidth',1,'DisplayName','Tlgm','Tag','TLGM','Parent',gui.axes24);
2055 plot(amp,inv2D.T1tlgm,'o','Color',col.FIT,'LineWidth',2,'DisplayName','Tlgm',...
2056     'Tag','TLGM','HandleVisibility','on','Parent',gui.axes24);
2057 set(gui.axes24,'XScale','lin','XLim',[0 ymax]);
2058 set(gui.axes24,'YScale','log','YTickLabel','');
2059 if T1_irange(1)>inv2D.T1vec(1)
2060     xlims = get(gui.axes24,'XLim');
2061     % draw a transparent patch
2062     v = [xlims(1) inv2D.T1vec(1); xlims(2) inv2D.T1vec(1);
2063         xlims(2) T1_irange(1); xlims(1) T1_irange(1)];
2064     f = [1 2 3 4 1];
2065     patch('Vertices',v,'Faces',f,'FaceColor','w','FaceAlpha',p_alpha,...
2066         'HandleVisibility','off','Tag','infolines','Parent', gui.axes24);
2067     v2 = [inv2D.T2vec(1) inv2D.T1vec(1) z_max+1; inv2D.T2vec(end) inv2D.T1vec(1) z_max+1;
2068         inv2D.T2vec(end) T1_irange(1) z_max+1; inv2D.T2vec(1) T1_irange(1) z_max+1];
2069     patch('Vertices',v2,'Faces',f,'FaceColor',mapcol(1,:),'FaceAlpha',1,...
2070         'HandleVisibility','off','Tag','infolines','Parent', gui.axes2);
2071 end
2072 if T1_irange(2)<inv2D.T1vec(end)
2073     xlims = get(gui.axes24,'XLim');
2074     % draw a transparent patch
2075     v = [xlims(1) inv2D.T1vec(end); xlims(2) inv2D.T1vec(end);
2076         xlims(2) T1_irange(2); xlims(1) T1_irange(2)];
2077     f = [1 2 3 4 1];
2078     patch('Vertices',v,'Faces',f,'FaceColor','w','FaceAlpha',p_alpha,...
2079         'HandleVisibility','off','Tag','infolines','Parent', gui.axes24);
2080     v2 = [inv2D.T2vec(1) inv2D.T1vec(end) z_max+1; inv2D.T2vec(end) inv2D.T1vec(end) z_max+1;
2081         inv2D.T2vec(end) T1_irange(2) z_max+1; inv2D.T2vec(1) T1_irange(2) z_max+1];
2082     patch('Vertices',v2,'Faces',f,'FaceColor',mapcol(1,:),'FaceAlpha',1,...
2083         'HandleVisibility','off','Tag','infolines','Parent', gui.axes2);
2084 end
2085
2086 % T2 RTD
2087 plot(inv2D.T2vec,T2rtd,'Color',col.FIT,'DisplayName','RTD','Parent',gui.axes21);
2088 amp = findApproxTlgmAmplitude(inv2D.T2vec,T2rtd,inv2D.T2tlgm);
2089 plot([inv2D.T2tlgm inv2D.T2tlgm],[0 amp],'Color',col.FIT,'LineStyle','--',...
2090     'LineWidth',1,'DisplayName','Tlgm','Tag','TLGM','Parent',gui.axes21);
2091 plot(inv2D.T2tlgm,amp,'o','Color',col.FIT,'LineWidth',2,'DisplayName','Tlgm',...
2092     'Tag','TLGM','HandleVisibility','on','Parent',gui.axes21);
2093 set(gui.axes21,'YScale','lin','YLim',[0 ymax]);
2094 set(gui.axes21,'XScale','log','XTickLabel','');
2095 if T2_irange(1)>inv2D.T2vec(1)
2096     ylims = get(gui.axes21,'YLim');
2097     % draw a transparent patch
2098     v = [inv2D.T2vec(1) ylims(1);inv2D.T2vec(1) ylims(2);
2099         T2_irange(1) ylims(2);T2_irange(1) ylims(1)];
2100     f = [1 2 3 4 1];
2101     patch('Vertices',v,'Faces',f,'FaceColor','w','FaceAlpha',p_alpha,...
2102         'HandleVisibility','off','Tag','infolines','Parent', gui.axes21);
2103     v2 = [inv2D.T2vec(1) inv2D.T1vec(1) z_max+1; inv2D.T2vec(1) inv2D.T1vec(end) z_max+1;
2104         T2_irange(1) inv2D.T1vec(end) z_max+1; T2_irange(1) inv2D.T1vec(1) z_max+1];
2105     patch('Vertices',v2,'Faces',f,'FaceColor',mapcol(1,:),'FaceAlpha',1,...
2106         'HandleVisibility','off','Tag','infolines','Parent', gui.axes2);
2107 end
2108 if T2_irange(2)<inv2D.T2vec(end)
2109     ylims = get(gui.axes21,'YLim');
2110     % draw a transparent patch
2111     v = [inv2D.T2vec(end) ylims(1);inv2D.T2vec(end) ylims(2);
2112         T2_irange(2) ylims(2);T2_irange(2) ylims(1)];
2113     f = [1 2 3 4 1];
2114     patch('Vertices',v,'Faces',f,'FaceColor','w','FaceAlpha',p_alpha,...
2115         'HandleVisibility','off','Tag','infolines','Parent', gui.axes21);
2116     v2 = [inv2D.T2vec(end) inv2D.T1vec(1) z_max+1; inv2D.T2vec(end) inv2D.T1vec(end) z_max+1;
2117         T2_irange(2) inv2D.T1vec(end) z_max+1; T2_irange(2) inv2D.T1vec(1) z_max+1];
2118     patch('Vertices',v2,'Faces',f,'FaceColor',mapcol(1,:),'FaceAlpha',1,...
2119         'HandleVisibility','off','Tag','infolines','Parent', gui.axes2);
2120 end
2121
2122 % tab 1 - model response
2123 data_inv = inv2D.data;
2124 E_fit_surf = zeros(numel(data_inv),numel(inv2D.data(1).t));
2125 Residual_surf = E_fit_surf;
2126 for nn = 1:numel(data_inv)
2127     E_fit_surf(nn,:) = data_inv(nn).s_fit;
2128     Residual_surf(nn,:) = data_inv(nn).residual;
2129 end
2130 [tx,ty] = meshgrid(t2,T1T2map.t_recov);
2131 % data
2132 imagescnan(tx,ty,E_fit_surf,'Parent',gui.axes13);
2133 view(gui.axes13,[0 90]);
2134 set(gui.axes13,'XScale','log');
2135 set(gui.axes13,'YScale','log','YDir','normal');
2136 set(get(gui.axes13,'XLabel'),'String','time [s]');
2137 set(get(gui.axes13,'YLabel'),'String','recovery time t_{rec} [s]');
2138 set(get(gui.axes13,'Title'),'String','data pred','Color',gui.myui.colors.axisFG);
2139 set(gui.axes13,'CLim',get(gui.axes11,'CLim'));
2140 set(gui.axes13,'Layer','top','XGrid','off','YGrid','off');
2141 cb = colorbar(gui.axes13);
2142 set(cb,'Location','EastOutside');
2143 % residual
2144 if sum(T1T2map.ecube) == 0
2145     % data without noise (probably from modelling)
2146     resW = Residual_surf;
2147 else
2148     resW = Residual_surf./T1T2map.ecube;
2149 end
2150 chi2 = sqrt(sum(sum(resW.^2)))/sqrt(numel(resW));
2151 imagescnan(tx,ty,resW,'Parent',gui.axes14);
2152 view(gui.axes14,[0 90]);
2153 set(gui.axes14,'XScale','log');
2154 set(gui.axes14,'YScale','log','YDir','normal');
2155 set(get(gui.axes14,'XLabel'),'String','time [s]');
2156 set(get(gui.axes14,'YLabel'),'String','recovery time t_{rec} [s]');
2157 set(get(gui.axes14,'Title'),'String',{'noise weighted residual',['(RMS=',sprintf('%4.3f',inv2D.error_global.rms),...
2158     ' | X^2=',sprintf('%3.2f',chi2),')']},'Color',gui.myui.colors.axisFG);
2159 if sum(T1T2map.ecube) == 0
2160      set(gui.axes14,'CLim',[mean(resW(:))-3*std(resW(:)) mean(resW(:))+3*std(resW(:))]);
2161 else
2162     set(gui.axes14,'CLim',get(gui.axes12,'CLim'));
2163 end
2164 set(gui.axes14,'Layer','top','XGrid','off','YGrid','off');
2165 colormap(gui.axes14,gui.myui.cmap_rwb);
2166 cb = colorbar(gui.axes14);
2167 set(cb,'Location','EastOutside');
2168
2169 % prepare the data for the combined T1 curve
2170 E_inv = zeros(size(T1T2map.t_recov));
2171 for nn = 1:numel(data_inv)
2172     E_inv(nn) = data_inv(nn).s_fit(1);
2173     % E_inv(nn,2) = std(T1T2map.data(nn).s);
2174     % plot individual T2 signals and fits
2175     plot3(inv2D.data(nn).t,inv2D.data(nn).T1*ones(size(inv2D.data(nn).s)),...
2176         inv2D.data(nn).s,'Color',col.RE,'DisplayName','T2 signals',...
2177         'LineWidth',1,'Parent',gui.axes32);
2178     plot3(data_inv(nn).t,data_inv(nn).T1*ones(size(data_inv(nn).s_fit)),data_inv(nn).s_fit,...
2179         'Color',col.FIT,'DisplayName','fits','Parent',gui.axes32);
2180 end
2181 view(gui.axes32,[30 20]);
2182 set(gui.axes32,'XScale','log','XTick',log_t_ticks);
2183 set(gui.axes32,'YScale','log','YDir','normal','YTick',log_t_ticks,'YLim',t_recov_lims);
2184 set(get(gui.axes32,'XLabel'),'String','time [s]');
2185 set(get(gui.axes32,'YLabel'),'String','recovery time t_{rec} [s]');
2186 set(get(gui.axes32,'ZLabel'),'String','amplitude [a.u.]');
2187
2188 % tab 3 - combined T1 curve and fit
2189 plot(T1T2map.t_recov,T1T2map.E_raw(:,1),'o-','Color',col.RE,...
2190     'LineWidth',1,'DisplayName','T1 curve','Parent',gui.axes31);
2191 plot(T1T2map.t_recov,E_inv,'Color',col.FIT,'DisplayName','fit','Parent',gui.axes31);
2192 set(gui.axes31,'XScale','log','XLim',t_recov_lims);
2193 set(gui.axes31,'YScale','lin');
2194 set(get(gui.axes31,'XLabel'),'String','recovery time t_{rec} [s]');
2195 set(get(gui.axes31,'YLabel'),'String','mean(E(1:x)) [a.u.]');
2196 lgh = legend(gui.axes31,'Location','SouthEast');
2197 set(lgh,'EdgeColor',gui.myui.colors.axisFG,'TextColor',gui.myui.colors.axisFG);
2198
2199 % hold off all axes
2200 hold(gui.axes13,'off');
2201 hold(gui.axes14,'off');
2202 hold(gui.axes2,'off');
2203 hold(gui.axes21,'off');
2204 hold(gui.axes24,'off');
2205 hold(gui.axes31,'off');
2206 hold(gui.axes32,'off');
2207
2208 % call function to adapt the axes scaling
2209 tv_setAxesScaling(figh);
2210 end
2211
2212 %%  subfunction to plot the raw data
2213 function tv_plotRawData(figh)
2214 gui = getappdata(figh,'gui');
2215 data = getappdata(figh,'data');
2216 T1T2map = data.results.T1T2map;
2217 col = gui.myui.colors;
2218 hold(gui.axes31,'on');
2219 hold(gui.axes32,'on');
2220
2221 % ticks and limits
2222 log_t_ticks = logspace(-5,2,8);
2223 t_recov_lims = [min(T1T2map.t_recov)/2 max(T1T2map.t_recov)*2];
2224
2225 if data.prop.useLogGates
2226     t2 = T1T2map.t2_gate;
2227 else
2228     t2 = T1T2map.t2;
2229 end
2230
2231 % plot the raw signals in the 3D axis
2232 for i = 1:numel(T1T2map.t_recov)
2233     % plot the individual T2 signals into the 3D data cube
2234     plot3(t2,T1T2map.t_recov(i)*ones(size(t2)),real(T1T2map.dcube(i,:)),...
2235         'Color',col.RE,'DisplayName','T2 signals','LineWidth',1,'Parent',gui.axes32);
2236 end
2237
2238 % tab 1 - surface plots
2239 [tx,ty] = meshgrid(t2,T1T2map.t_recov);
2240 % signal
2241 imagescnan(tx,ty,real(T1T2map.dcube),'Parent',gui.axes11);
2242 view(gui.axes11,[0 90]);
2243 set(gui.axes11,'XScale','log');
2244 set(gui.axes11,'YScale','log','YDir','normal');
2245 set(get(gui.axes11,'XLabel'),'String','time [s]');
2246 set(get(gui.axes11,'YLabel'),'String','recovery time t_{rec} [s]');
2247 set(get(gui.axes11,'Title'),'String','real(data obs)','Color',gui.myui.colors.axisFG);
2248 set(gui.axes11,'Layer','top','XGrid','off','YGrid','off');
2249 cb = colorbar(gui.axes11);
2250 set(cb,'Location','EastOutside');
2251
2252 % noise
2253 ErrWimag = imag(T1T2map.dcube)./T1T2map.ecube;
2254 chi2 = sqrt(sum(sum(ErrWimag.^2)))/sqrt(numel(ErrWimag));
2255 rms = mean(T1T2map.noise);
2256 imagescnan(tx,ty,ErrWimag,'Parent',gui.axes12);
2257 maxv = max(abs(ErrWimag(:)));
2258 view(gui.axes12,[0 90]);
2259 % limits & ticks
2260 set(gui.axes12,'XScale','log');
2261 set(gui.axes12,'YScale','log','YDir','normal');
2262 set(get(gui.axes12,'XLabel'),'String','time [s]');
2263 set(get(gui.axes12,'YLabel'),'String','recovery time t_{rec} [s]');
2264 set(get(gui.axes12,'Title'),'String',{'noise weighted imag(data obs)',['(STD=',sprintf('%4.3f',rms),' | ',...
2265     'X^2=',sprintf('%3.2f',chi2),')']},'Color',gui.myui.colors.axisFG);
2266 set(gui.axes12,'Layer','top','XGrid','off','YGrid','off');
2267 colormap(gui.axes12,gui.myui.cmap_rwb);
2268 if isnan(maxv)
2269     maxv = 1;
2270 end
2271 set(gui.axes12,'CLim',[-maxv maxv]);
2272 cb = colorbar(gui.axes12);
2273 set(cb,'Location','EastOutside');
2274
2275 % tab 3 - combined T1 curve
2276 plot(T1T2map.t_recov,T1T2map.E_raw(:,1),'o-','Color',col.RE,...
2277     'LineWidth',1,'DisplayName','T1 curve','Parent',gui.axes31);
2278 set(gui.axes31,'XScale','log','XLim',t_recov_lims);
2279 set(gui.axes31,'YScale','lin');
2280 set(get(gui.axes31,'XLabel'),'String','recovery time t_{rec} [s]');
2281 set(get(gui.axes31,'YLabel'),'String','mean(E(1:x)) [a.u.]');
2282 lgh = legend(gui.axes31,'Location','SouthEast');
2283 set(lgh,'EdgeColor',gui.myui.colors.axisFG,'TextColor',gui.myui.colors.axisFG);
2284
2285 % tab 3  - 2D data cube
2286 view(gui.axes32,[30 20]);
2287 set(gui.axes32,'XScale','log','XTick',log_t_ticks);
2288 set(gui.axes32,'YScale','log','YDir','normal','YTick',log_t_ticks,'YLim',t_recov_lims);
2289 set(get(gui.axes32,'XLabel'),'String','time [s]');
2290 set(get(gui.axes32,'YLabel'),'String','recovery time t_{rec} [s]');
2291 set(get(gui.axes32,'ZLabel'),'String','amplitude [a.u.]');
2292 hold(gui.axes32,'off');
2293
2294 % call function to adapt the axes scaling
2295 tv_setAxesScaling(figh);
2296 end
2297
2298 %% subfunction to check the LSE
2299 function tv_checkLSEparams(data)
2300
2301 if ~contains(data.inv.regtype,'manual')
2302     % sN = number of T2 signals
2303     % gN = number of gates/echoes
2304     [sN,gN] = size(data.results.T1T2map.dcube);
2305     % size of modelspace
2306     T1N = data.inv.T1N;
2307     T2N = data.inv.T2N;
2308     % check
2309     if sN*gN < T1N*T2N
2310         helpdlg({'System is underdetermined:',...
2311             'Increase number of gates or decrease model space.'},...
2312             'SVD warning');
2313     end
2314 end
2315
2316 end
2317
2318 %% subfunction to update all plots
2319 function tv_getTLGM(figh)
2320 % local GUI data
2321 gui = getappdata(figh,'gui');
2322 data = getappdata(figh,'data');
2323 % get 2D inversion data
2324 inv2D = data.results.inv2D;
2325
2326 % get T1/T2 range from GUI
2327 T1range(1) = data.info.T1min;
2328 T1range(2) = data.info.T1max;
2329 T2range(1) = data.info.T2min;
2330 T2range(2) = data.info.T2max;
2331
2332 % get TLGM and TMAX accounting for T1 and T2 ranges
2333 [TLGM,TMAX] = getTLogMean2D(inv2D.T1vec,inv2D.T2vec,inv2D.f_2Dmap,T1range,T2range);
2334
2335 % update results in data struct
2336 inv2D.T1tlgm = TLGM(1);
2337 inv2D.T2tlgm = TLGM(2);
2338 inv2D.T1tmax = TMAX(1);
2339 inv2D.T2tmax = TMAX(2);
2340
2341 % update GUI data struct
2342 data.info.E0 = inv2D.E0;
2343 data.info.T1tlgm = inv2D.T1tlgm;
2344 data.info.T2tlgm = inv2D.T2tlgm;
2345 data.info.T1tmax = inv2D.T1tmax;
2346 data.info.T2tmax = inv2D.T2tmax;
2347
2348 % update GUI elements
2349 set(gui.edit_handles.E0,'String',sprintf('%4.3f',inv2D.E0));
2350 set(gui.edit_handles.T1tlgm,'String',sprintf('%4.3f',inv2D.T1tlgm));
2351 set(gui.edit_handles.T2tlgm,'String',sprintf('%4.3f',inv2D.T2tlgm));
2352 set(gui.edit_handles.Tlgm_ratio,'String',sprintf('%4.3f',inv2D.T1tlgm/inv2D.T2tlgm));
2353 set(gui.edit_handles.T1tmax,'String',sprintf('%4.3f',inv2D.T1tmax));
2354 set(gui.edit_handles.T2tmax,'String',sprintf('%4.3f',inv2D.T2tmax));
2355 set(gui.edit_handles.Tmax_ratio,'String',sprintf('%4.3f',inv2D.T1tmax/inv2D.T2tmax));
2356
2357 % update data
2358 data.results.inv2D = inv2D;
2359 setappdata(figh,'data',data);
2360 end
2361
2362 %% subfunction to find RTD amplitude
2363 function amp = findApproxTlgmAmplitude(t,f,TLGM)
2364
2365 if isnan(TLGM)
2366     amp = NaN;
2367 else
2368     index = find(abs(t-TLGM)==min(abs(t-TLGM)));
2369     if index == 1 || index == numel(t)
2370         amp = f(index);
2371     else
2372         amp = interp1(t(index-1:index+1),f(index-1:index+1),TLGM);
2373     end
2374 end
2375
2376 end
2377
2378 %%  subfunction to prepare the raw data
2379 function tv_prepareRawData(figh)
2380 data = getappdata(figh,'data');
2381 T1T2map = data.results.T1T2map;
2382
2383 % select first and last T1 recov times
2384 firstT1 = data.prop.firstT1;
2385 lastT1 = data.prop.lastT1;
2386 T1T2map.t_recov = T1T2map.import{end}.time(firstT1:lastT1);
2387 id_recov = firstT1:lastT1;
2388
2389 % select first and last T2 echo
2390 firstN = data.prop.firstT2;
2391 lastN = data.prop.lastT2;
2392 T1T2map.t2 = T1T2map.import{1}.time(firstN:lastN);
2393
2394 % prepare the raw data
2395 if ~data.prop.useLogGates
2396     T1T2map.dcube = zeros(numel(T1T2map.t_recov),lastN-firstN+1);
2397     T1T2map.ecube = zeros(numel(T1T2map.t_recov),lastN-firstN+1);
2398 end
2399
2400 for i = 1:numel(T1T2map.t_recov)
2401     id = id_recov(i);
2402     if data.prop.useLogGates
2403         t_tmp = T1T2map.t2;
2404         s_tmp = real(T1T2map.import{id}.signal(firstN:lastN));
2405         si_tmp = imag(T1T2map.import{id}.signal(firstN:lastN));
2406         range = floor(numel(s_tmp)/2):numel(s_tmp);
2407         noise_tmp = std(si_tmp(range));
2408         tmp = applyGatesToSignal(t_tmp,s_tmp,'type','logv2','Ng',data.prop.Ngates);
2409         tmpi = applyGatesToSignal(t_tmp,si_tmp,'type','logv2','Ng',data.prop.Ngates);
2410         if i == 1
2411             Ngates_tmp = size(tmp,1);
2412             T1T2map.dcube = zeros(numel(T1T2map.t_recov),Ngates_tmp);
2413             T1T2map.ecube = zeros(numel(T1T2map.t_recov),Ngates_tmp);
2414             T1T2map.t2_gate = tmp(:,1);
2415             T1T2map.t2_gateN = tmp(:,3);
2416         end
2417         s_gate = complex(tmp(:,2),tmpi(:,2));
2418         N = tmp(:,3);
2419         e = noise_tmp ./ sqrt(N);
2420
2421         T1T2map.dcube(i,:) = s_gate';
2422         T1T2map.ecube(i,:) = e';
2423         T1T2map.noise(i,1) = noise_tmp;
2424
2425     else
2426         T1T2map.dcube(i,:) = complex(real(T1T2map.import{id}.signal(firstN:lastN)),...
2427             imag(T1T2map.import{id}.signal(firstN:lastN)));
2428         T1T2map.ecube(i,:) = std(imag(T1T2map.import{id}.signal(firstN:lastN))) .*...
2429             ones(size(imag(T1T2map.import{id}.signal(firstN:lastN))));
2430         T1T2map.noise(i,1) = std(imag(T1T2map.dcube(i,:)));
2431     end
2432 end
2433 %data.prop.Ngates = sNgates_tmp;
2434
2435 % get merged T1 curve
2436 T1T2map.E_raw = T1T2map.import{end}.signal(firstT1:lastT1);
2437
2438 % update the data
2439 data.results.T1T2map = T1T2map;
2440 % update GUI data
2441 setappdata(figh,'data',data);
2442 end
2443
2444 %% estimate IR type
2445 function tv_estimateIRtype(figh)
2446 data = getappdata(figh,'data');
2447 gui = getappdata(figh,'gui');
2448 T1T2map = data.results.T1T2map;
2449
2450 % the T1 curve
2451 E = T1T2map.E_raw;
2452
2453 if E(1) > 0
2454     % possibly SR
2455     data.inv.IRtype = 1;
2456     data.inv.T1IRfac = 1;
2457     set(gui.popup_handles.T1type,'Value',1);
2458     set(gui.popup_handles.IRtype,'Enable','off');
2459 else
2460     if E(end) < abs(E(1))*0.5
2461         % possibly IR with kernel type 2 => -exp(t/T1)
2462         data.inv.IRtype = 2;
2463         set(gui.popup_handles.T1type,'Value',2);
2464         set(gui.popup_handles.IRtype,'Value',2);
2465     else
2466         % possibly IR with kernel type 1 => 1-2exp(t/T1)
2467         data.inv.IRtype = 1;
2468         data.inv.T1IRfac = 2;
2469         set(gui.popup_handles.T1type,'Value',2);
2470         set(gui.popup_handles.IRtype,'Value',1);
2471     end
2472 end
2473
2474 % update GUI data
2475 setappdata(figh,'data',data);
2476 setappdata(figh,'gui',gui);
2477 end
2478
2479 %% adjust the data tip on the 2D axes
2480 function txt = localDcmFcn(~,event,ax)
2481
2482 if strcmp(get(ax,'Tag'),'2D')
2483     % find indices to closest x and y data values. This requires the
2484     % number of values in XData and YData to agree with CData size.
2485     [~, xidx] = min(abs(event.Target.XData - event.Position(1)),[],2);
2486     [~, yidx] = min(abs(event.Target.YData - event.Position(2)),[],1);
2487     colorbarValue = event.Target.CData(yidx(1), xidx(1));
2488     % colormapIdx = round((colorbarValue - ax.CLim(1))/(ax.CLim(2)-ax.CLim(1)) * (size(ax.Colormap,1)-1) +1);
2489     txt = sprintf('[T2,T1]: [%.2g, %.2g]\nValue: %.2g', ...
2490         event.Position(1:2), colorbarValue);
2491 end
2492
2493 end
2494
2495 %% close function
2496 function tv_closeme(src,~)
2497 figh = ancestor(src,'figure','toplevel');
2498 % try to close the sub GUI in a clean manner
2499 try
2500     % NOTE: maybe needed at some later point
2501     %     gui = getappdata(figh,'gui');
2502     %     data = getappdata(gui.figh_nucleus,'data');
2503     %     % update NUCLEUSinv
2504     %     setappdata(gui.figh_nucleus,'data',data);
2505     delete(figh);
2506 catch
2507     % if this is not working: just close it
2508     delete(figh);
2509 end
2510
2511 end
2512
2513 %------------- END OF CODE --------------
2514
2515 %% License:
2516 % MIT License
2517 %
2518 % Copyright (c) 2024 Thomas Hiller
2519 %
2520 % Permission is hereby granted, free of charge, to any person obtaining a copy
2521 % of this software and associated documentation files (the "Software"), to deal
2522 % in the Software without restriction, including without limitation the rights
2523 % to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
2524 % copies of the Software, and to permit persons to whom the Software is
2525 % furnished to do so, subject to the following conditions:
2526 %
2527 % The above copyright notice and this permission notice shall be included in all
2528 % copies or substantial portions of the Software.
2529 %
2530 % THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
2531 % IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
2532 % FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
2533 % AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
2534 % LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
2535 % OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
2536 % SOFTWARE.