Description of UncertView
UncertView
PURPOSE
is an extra subGUI to show results of the uncertainty
SYNOPSIS
function UncertView(src,~)
DESCRIPTION
UncertView is an extra subGUI to show results of the uncertainty
calculation
 Syntax:
       UncertView
 Inputs:
       src - handle of the calling object
 Outputs:
       none
 Example:
       UncertView(src,~)
 Other m-files required:
       beautifyAxes
       clearAllAxes
       estimateUncertainty
       createKernelMatrix
       updatePlotsSignal
       updatePlotsDistribution
       updateInfo
 Subfunctions:
       uv_closeme
       uv_onEditValue
       uv_updateMASK
       uv_onPushRun
       uv_onPushUpdate
       uv_onPushReset
       uv_updateInformation
       uv_updatePlots
 MAT-files required:
       none
 See also: NUCLEUSinv
 Author: see AUTHORS.md
 email: see AUTHORS.md
 License: MIT License (at end)
CROSS-REFERENCE INFORMATION
This function calls:
onMenuView handles the view menu entries
beautifyAxes can be used to globally change the general appearance of axes
changeColorTheme changes the color theme of the calling figure
clearAllAxes clears all axes of a given figure
displayStatusText shows status information either in the GUI or on the
fixVerticalTextAlignment fixes the vertical positioning of all text
getKernelDensityEstimate computes the one dimensional kernel density estimate
minimizePanel handles the minimization/maximization of all box-panels for
updateInfo updates the information shown in all information list boxes
updatePlotsDistribution plots the RTD and PSD curves into NUCLEUSinv
updatePlotsSignal plots the raw and processed NMR signals in NUCLEUSinv
createKernelMatrix creates a Kernel matrix from signal time vector "t"
estimateUncertainty calculates pseudo uncertainty estimates for multi
getAAD gets the average absolute deviation from the values in x
getUncertaintyStatistics
This function is called by:
onListboxData handles the calls from the context menu of the data
onMenuSubGUIs handles the extra menu entries to open NUCLEUS sub GUIs
runUncertaintyCalculation caluclates inverison statistics in some kind of
SUBFUNCTIONS
function uv_onEditValue(src,~)
function uv_onPushSend(src,~)
function uv_onContextPlotsColor(src,~)
function uv_onContextPlotsRTD(src,~)
function data = uv_updateMASK(data)
function uv_onPopupMethod(src,~)
function uv_onPushRun(src,~)
function uv_onPushView(src,~)
function uv_onPushUpdate(src,~)
function uv_onPushReset(src,~)
function uv_updateInformation(figh)
function uv_updatePlots(figh)
function uv_closeme(src,~)
SOURCE CODE
function UncertView(src,~)
%UncertView is an extra subGUI to show results of the uncertainty
%calculation
%
% Syntax:
%       UncertView
%
% Inputs:
%       src - handle of the calling object
%
% Outputs:
%       none
%
% Example:
%       UncertView(src,~)
%
% Other m-files required:
%       beautifyAxes
%       clearAllAxes
%       estimateUncertainty
%       createKernelMatrix
%       updatePlotsSignal
%       updatePlotsDistribution
%       updateInfo
%
% Subfunctions:
%       uv_closeme
%       uv_onEditValue
%       uv_updateMASK
%       uv_onPushRun
%       uv_onPushUpdate
%       uv_onPushReset
%       uv_updateInformation
%       uv_updatePlots
%
% MAT-files required:
%       none
%
% See also: NUCLEUSinv
% Author: see AUTHORS.md
% email: see AUTHORS.md
% License: MIT License (at end)
%------------- BEGIN CODE --------------
%% get GUI handle and data
figh_nucleus = ancestor(src,'figure','toplevel');
nucleus.data = getappdata(figh_nucleus,'data');
nucleus.gui = getappdata(figh_nucleus,'gui');
myui = nucleus.gui.myui;
colors = myui.colors;
hasUncert = false;
if isfield(nucleus.data.results,'invstd')
    if isfield(nucleus.data.results.invstd,'uncert')
        hasUncert = true;
    end
end
%% proceed only if there is already uncertainty data
if hasUncert
    nucleus_data = nucleus.data;
    % check if the figure is already open
    fig_uncert = findobj('Tag','UNCERTVIEW');
    % if not, create it
    if isempty(fig_uncert)
        % draw the figure on top of NUCLEUSinv
        fig_uncert = figure('Name','NUCLEUSinv - RTD Uncertainty',...
            'NumberTitle','off','Resize','on','ToolBar','none',...
            'CloseRequestFcn',@uv_closeme,...
            'MenuBar','none','Tag','UNCERTVIEW');
        pos0 = get(figh_nucleus,'Position');
        cent(1) = (pos0(1)+pos0(3)/2);
        cent(2) = (pos0(2)+pos0(4)/2);
        % posf = [cent(1)-pos0(3)/3 pos0(2)+22 pos0(3)/1.5 pos0(4)-22];
        posf = [cent(1)-pos0(3)/2.5 pos0(2)+22 pos0(3)/1.25 pos0(4)-22];
        set(fig_uncert,'Position',posf);
        gui.menu.view = uimenu(fig_uncert,'Label','View');
        gui.menu.view_toolbar = uimenu(gui.menu.view,'Label','Figure Toolbar',...
            'Callback',@onMenuView);
        cpanel_w = 175;
        % create the main layout
        gui.main = uix.HBox('Parent',fig_uncert,'BackGroundColor',colors.panelBG,...
            'Spacing',5,'Padding',5,'Visible','off');
        gui.left = uix.VBox('Parent',gui.main,'BackGroundColor',colors.panelBG,...
            'Spacing',5,'Padding',0); % controls
        gui.right = uix.VBox('Parent',gui.main,'BackGroundColor',colors.panelBG,...
            'Spacing',5,'Padding',0); % plots
        set(gui.main,'Widths',[350 -1 ]);
        % waitbar indicating the loading of the GUI
        steps = 5;
        hwb = waitbar(0,'loading ...','Name','UncertView initialization','Visible','off');
        set(hwb,'Units','Pixel')
        posw = get(hwb,'Position');
        set(hwb,'Position',[posf(1)+posf(3)/2-posw(3)/2 posf(2)+posf(4)/2-posw(4)/2 posw(3:4)]);
        set(hwb,'Visible','on');
        % --- control panel ---
        waitbar(1/steps,hwb,'loading GUI elements - control');
        gui.panels.control.main = uix.BoxPanel('Parent',gui.left,...
            'Title','Recalculate RTD Uncertainty','MinimizeFcn',@minimizePanel,...
            'TitleColor',colors.BoxINV,'ForegroundColor',colors.BoxTitle);
        gui.panels.control.VBox = uix.VBox('Parent',gui.panels.control.main,...
            'Spacing',3,'Padding',3);
        % uncertainty method
        gui.panels.control.HBox1 = uix.HBox('Parent',gui.panels.control.VBox,...
            'Spacing',3);
        gui.text_handles.uncertMethod = uicontrol('Parent',gui.panels.control.HBox1,...
            'Style','text','FontSize',myui.fontsize,'HorizontalAlignment','center',...
            'String','Method');
        tstr = ['<HTML>Choose the uncertainty calculation method.<br><br>',...
            '<u>Available options:</u><br>',...
            '<font color="red">Multi exp. (LSQ) | Multi exp. (LU decomp.):<br>',...
            '<font color="black">',...
            '<b>RMS - unbounded</b> Keep all uncert models.<br>',...
            '<b>RMS - bounded</b> Only keep models within Lm and chi2 bounds.<br>',...
            '<font color="red">Multi modal:<br>',...
            '<font color="black">',...
            '<b>RMS - unbounded</b> Keep all uncert models.<br>',...
            '<b>RMS - bounded</b> Only keep models within Lm and chi2 bounds.<br>',...
            '<b>Threshold</b> Vary fit parameter by threshold.<br>',...
            '<b>Conf. Interval</b> Vary fit parameter randomly within confidence interval.<br><br>',...
            '<u>Default value:</u><br>',...
            '<b>RMS - bounded</b><br>'];
        gui.popup_handles.uncertMethod = uicontrol('Parent',gui.panels.control.HBox1,...
            'Style','popup','String',{'RMS - unbounded','RMS - bounded'},...
            'ToolTipString',tstr,'UserData',struct('Tooltipstr',tstr),...
            'FontSize',myui.fontsize,'Tag','control','Callback',@uv_onPopupMethod);
        set(gui.panels.control.HBox1,'Widths',[cpanel_w -1]);
        % number of uncertainty models
        gui.panels.control.HBox2 = uix.HBox('Parent',gui.panels.control.VBox,...
            'Spacing',3);
        gui.text_handles.uncertN = uicontrol('Parent',gui.panels.control.HBox2,...
            'Style','text','FontSize',myui.fontsize,'HorizontalAlignment','center',...
            'String','#models');
        uix.Empty('Parent',gui.panels.control.HBox2);
        tstr = 'Number of uncertainty models to calculate.';
        gui.edit_handles.uncertN = uicontrol('Parent',gui.panels.control.HBox2,...
            'Style','edit','String','0','FontSize',myui.fontsize,'Tag','uncertN',...
            'ToolTipString',tstr,'UserData',struct('Tooltipstr',tstr),...
            'Callback',@uv_onEditValue);
        set(gui.panels.control.HBox2,'Widths',[cpanel_w -1 -1]);
        % bound1: chi2 range
        gui.panels.control.HBox3 = uix.HBox('Parent',gui.panels.control.VBox,...
            'Spacing',3);
        gui.text_handles.uncertchi2 = uicontrol('Parent',gui.panels.control.HBox3,...
            'Style','text','FontSize',myui.fontsize,'HorizontalAlignment','center',...
            'String',[char(hex2dec('03A7')),char(hex2dec('00B2')),...
            ' range          min | max']);
        tstr = 'Lower bound of chi2 range.';
        gui.edit_handles.uncertchi2_min = uicontrol('Parent',gui.panels.control.HBox3,...
            'Style','edit','String','0','FontSize',myui.fontsize,'Tag','control',...
            'ToolTipString',tstr,'UserData',struct('Tooltipstr',tstr),...
            'Enable','off','Callback',@uv_onEditValue);
        tstr = 'Upper bound of chi2 range.';
        gui.edit_handles.uncertchi2_max = uicontrol('Parent',gui.panels.control.HBox3,...
            'Style','edit','String','0','FontSize',myui.fontsize,'Tag','control',...
            'ToolTipString',tstr,'UserData',struct('Tooltipstr',tstr),...
            'Enable','off','Callback',@uv_onEditValue);
        set(gui.panels.control.HBox3,'Widths',[cpanel_w -1 -1]);
        % bound2: model norm range
        gui.panels.control.HBox4 = uix.HBox('Parent',gui.panels.control.VBox,...
            'Spacing',3);
        gui.text_handles.uncertmnorm = uicontrol('Parent',gui.panels.control.HBox4,...
            'Style','text','FontSize',myui.fontsize,'HorizontalAlignment','center',...
            'String',['|Lm|',char(hex2dec('2082')),' range      min | max']);
        tstr = 'Lower bound of model norm range.';
        gui.edit_handles.uncertmnorm_min = uicontrol('Parent',gui.panels.control.HBox4,...
            'Style','edit','String','0','FontSize',myui.fontsize,'Tag','control',...
            'ToolTipString',tstr,'UserData',struct('Tooltipstr',tstr),...
            'Enable','off','Callback',@uv_onEditValue);
        tstr = 'Upper bound of model norm range.';
        gui.edit_handles.uncertmnorm_max = uicontrol('Parent',gui.panels.control.HBox4,...
            'Style','edit','String','0','FontSize',myui.fontsize,'Tag','control',...
            'ToolTipString',tstr,'UserData',struct('Tooltipstr',tstr),...
            'Enable','off','Callback',@uv_onEditValue);
        set(gui.panels.control.HBox4,'Widths',[cpanel_w -1 -1]);
        % bound3: threshold
        gui.panels.control.HBox5 = uix.HBox('Parent',gui.panels.control.VBox,...
            'Spacing',3);
        gui.text_handles.uncertThresh = uicontrol('Parent',gui.panels.control.HBox5,...
            'Style','text','FontSize',myui.fontsize,'HorizontalAlignment','center',...
            'String','Threshold   |   Max. #tries');
        % uix.Empty('Parent',gui.panels.control.HBox5);
        tstr = 'Threshold value (0.05 = 5%).';
        gui.edit_handles.uncertThresh = uicontrol('Parent',gui.panels.control.HBox5,...
            'Style','edit','String','0','FontSize',myui.fontsize,'Tag','uncertThresh',...
            'ToolTipString',tstr,'UserData',struct('Tooltipstr',tstr),...
            'Enable','off','Callback',@uv_onEditValue);
        % set(gui.panels.control.HBox5,'Widths',[cpanel_w -1 -1]);
        % max tries
        % gui.panels.control.HBox6 = uix.HBox('Parent',gui.panels.control.VBox,...
        %     'Spacing',3);
        % gui.text_handles.uncertMax = uicontrol('Parent',gui.panels.control.HBox6,...
        %     'Style','text','FontSize',myui.fontsize,'HorizontalAlignment','center',...
        %     'String','Max. #tries');
        % uix.Empty('Parent',gui.panels.control.HBox6);
        tstr = 'Maximum number of unsuccesful tries.';
        gui.edit_handles.uncertMax = uicontrol('Parent',gui.panels.control.HBox5,...
            'Style','edit','String','0','FontSize',myui.fontsize,'Tag','uncertMax',...
            'ToolTipString',tstr,'UserData',struct('Tooltipstr',tstr),...
            'Enable','off','Callback',@uv_onEditValue);
        set(gui.panels.control.HBox5,'Widths',[cpanel_w -1 -1]);
        % RUN button
        gui.panels.control.HBox7 = uix.HBox('Parent',gui.panels.control.VBox,...
            'Spacing',3);
        uix.Empty('Parent',gui.panels.control.HBox7);
        tstr = ['<HTML>RUN uncertainty calculation.<br>',...
            'Regularization is the same as in main NUCLEUSinv GUI.'];
        gui.push_handles.run = uicontrol('Parent',gui.panels.control.HBox7,...
            'String','RUN UNCERT','FontSize',myui.fontsize,'Tag','process',...
            'ToolTipString',tstr,'UserData',struct('Tooltipstr',tstr),...
            'BackGroundColor','g','Callback',@uv_onPushRun);
        set(gui.panels.control.HBox7,'Widths',[cpanel_w -1]);
        % --- process panel ---
        waitbar(2/steps,hwb,'loading GUI elements - process');
        gui.panels.process.main = uix.BoxPanel('Parent',gui.left,...
            'Title','Process Uncertainty Runs','MinimizeFcn',@minimizePanel,...
            'TitleColor',colors.BoxINV,'ForegroundColor',colors.BoxTitle);
        gui.panels.process.VBox = uix.VBox('Parent',gui.panels.process.main,...
            'Spacing',3,'Padding',3);
        % chi2 range
        gui.panels.process.HBox1 = uix.HBox('Parent',gui.panels.process.VBox,...
            'Spacing',3);
        gui.text_handles.chi2 = uicontrol('Parent',gui.panels.process.HBox1,...
            'Style','text','FontSize',myui.fontsize,'HorizontalAlignment','center',...
            'String',[char(hex2dec('03A7')),char(hex2dec('00B2')),...
            ' range          min | max']);
        tstr = 'Lower bound of chi2 range.';
        gui.edit_handles.chi2_min = uicontrol('Parent',gui.panels.process.HBox1,...
            'Style','edit','String','0','FontSize',myui.fontsize,'Tag','process',...
            'ToolTipString',tstr,'UserData',struct('Tooltipstr',tstr),...
            'Callback',@uv_onEditValue);
        tstr = 'Upper bound of chi2 range.';
        gui.edit_handles.chi2_max = uicontrol('Parent',gui.panels.process.HBox1,...
            'Style','edit','String','2','FontSize',myui.fontsize,'Tag','process',...
            'ToolTipString',tstr,'UserData',struct('Tooltipstr',tstr),...
            'Callback',@uv_onEditValue);
        set(gui.panels.process.HBox1,'Widths',[cpanel_w -1 -1]);
        % model norm range
        gui.panels.process.HBox2 = uix.HBox('Parent',gui.panels.process.VBox,...
            'Spacing',3);
        gui.text_handles.mnorm = uicontrol('Parent',gui.panels.process.HBox2,...
            'Style','text','FontSize',myui.fontsize,'HorizontalAlignment','center',...
            'String',['|Lm|',char(hex2dec('2082')),' range      min | max']);
        tstr = 'Lower bound of model norm range.';
        gui.edit_handles.mnorm_min = uicontrol('Parent',gui.panels.process.HBox2,...
            'Style','edit','String','0','FontSize',myui.fontsize,'Tag','process',...
            'ToolTipString',tstr,'UserData',struct('Tooltipstr',tstr),...
            'Callback',@uv_onEditValue);
        tstr = 'Upper bound of model norm range.';
        gui.edit_handles.mnorm_max = uicontrol('Parent',gui.panels.process.HBox2,...
            'Style','edit','String','2','FontSize',myui.fontsize,'Tag','process',...
            'ToolTipString',tstr,'UserData',struct('Tooltipstr',tstr),...
            'Callback',@uv_onEditValue);
        set(gui.panels.process.HBox2,'Widths',[cpanel_w -1 -1]);
        % RESET button
        gui.panels.process.HBox3 = uix.HBox('Parent',gui.panels.process.VBox,...
            'Spacing',3);
        uix.Empty('Parent',gui.panels.process.HBox3);
        tstr = 'SEND bounds to recaluclation panel above.';
        gui.push_handles.send = uicontrol('Parent',gui.panels.process.HBox3,...
            'String','USE','FontSize',myui.fontsize,'Tag','process',...
            'ToolTipString',tstr,'UserData',struct('Tooltipstr',tstr),...
            'Callback',@uv_onPushSend);
        tstr = 'RESET processing bounds and plots.';
        gui.push_handles.reset = uicontrol('Parent',gui.panels.process.HBox3,...
            'String','RESET','FontSize',myui.fontsize,'Tag','process',...
            'ToolTipString',tstr,'UserData',struct('Tooltipstr',tstr),...
            'Callback',@uv_onPushReset);
        set(gui.panels.process.HBox3,'Widths',[cpanel_w -1 -1]);
        % --- RTD panel ---
        waitbar(3/steps,hwb,'loading GUI elements - RTD bounds');
        gui.panels.rtd.main = uix.BoxPanel('Parent',gui.left,...
            'Title','RTD Calculation Bounds','MinimizeFcn',@minimizePanel,...
            'TitleColor',colors.BoxINV,'ForegroundColor',colors.BoxTitle);
        gui.panels.rtd.VBox = uix.VBox('Parent',gui.panels.rtd.main,...
            'Spacing',3,'Padding',3);
        % RTD range
        gui.panels.rtd.HBox1 = uix.HBox('Parent',gui.panels.rtd.VBox,...
            'Spacing',3);
        gui.text_handles.rtd = uicontrol('Parent',gui.panels.rtd.HBox1,...
            'Style','text','FontSize',myui.fontsize,'HorizontalAlignment','center',...
            'String','RTD range       min | max');
        tstr = ['<HTML>Minimum relaxation time in RTDs used<br>',...
            'for calculating statistics on E0 & TLGM.'];
        gui.edit_handles.rtd_min = uicontrol('Parent',gui.panels.rtd.HBox1,...
            'Style','edit','String','0','FontSize',myui.fontsize,'Tag','rtd',...
            'ToolTipString',tstr,'UserData',struct('Tooltipstr',tstr),...
            'Callback',@uv_onEditValue);
        tstr = ['<HTML>Maximum relaxation time in RTDs used<br>',...
            'for calculating statistics on E0 & TLGM.'];
        gui.edit_handles.rtd_max = uicontrol('Parent',gui.panels.rtd.HBox1,...
            'Style','edit','String','2','FontSize',myui.fontsize,'Tag','rtd',...
            'ToolTipString',tstr,'UserData',struct('Tooltipstr',tstr),...
            'Callback',@uv_onEditValue);
        set(gui.panels.rtd.HBox1,'Widths',[cpanel_w -1 -1]);
        % RESET button
        gui.panels.rtd.HBox3 = uix.HBox('Parent',gui.panels.rtd.VBox,...
            'Spacing',3);
        uix.Empty('Parent',gui.panels.rtd.HBox3);
        uix.Empty('Parent',gui.panels.rtd.HBox3);
        tstr = 'RESET RTDs calculation bounds.';
        gui.push_handles.reset_rtd = uicontrol('Parent',gui.panels.rtd.HBox3,...
            'String','RESET','FontSize',myui.fontsize,'Tag','rtd',...
            'ToolTipString',tstr,'UserData',struct('Tooltipstr',tstr),...
            'Callback',@uv_onPushReset);
        set(gui.panels.rtd.HBox3,'Widths',[cpanel_w -1 -1]);
        % --- Statistics panel ---
        waitbar(4/steps,hwb,'loading GUI elements - statistics');
        gui.panels.info.main = uix.BoxPanel('Parent',gui.left,...
            'Title','Uncertainty Statistics','MinimizeFcn',@minimizePanel,...
            'TitleColor',colors.BoxINV,'ForegroundColor',colors.BoxTitle);
        gui.panels.info.VBox = uix.VBox('Parent',gui.panels.info.main,...
            'Spacing',3,'Padding',3);
        % mean TLGM
        gui.panels.info.HBox1 = uix.HBox('Parent',gui.panels.info.VBox,...
            'Spacing',3);
        gui.text_handles.TLGM = uicontrol('Parent',gui.panels.info.HBox1,...
            'Style','text','FontSize',myui.fontsize,'HorizontalAlignment','center',...
            'String','TLGM          mean | 2*std');
        tstr = 'MEAN of all TLGM values.';
        gui.edit_handles.TLGM_mean = uicontrol('Parent',gui.panels.info.HBox1,...
            'Style','edit','String','0','FontSize',myui.fontsize,...
            'ToolTipString',tstr,'UserData',struct('Tooltipstr',tstr),...
            'BackgroundColor',colors.BoxPRC);
        tstr = 'STD of all TLGM values.';
        gui.edit_handles.TLGM_std = uicontrol('Parent',gui.panels.info.HBox1,...
            'Style','edit','String','2','FontSize',myui.fontsize,...
            'ToolTipString',tstr,'UserData',struct('Tooltipstr',tstr),...
            'BackgroundColor',colors.BoxPRC);
        set(gui.panels.info.HBox1,'Widths',[cpanel_w -1 -1]);
        % aad TLGM
        gui.panels.info.HBox2 = uix.HBox('Parent',gui.panels.info.VBox,...
            'Spacing',3);
        gui.text_handles.TLGM_aad = uicontrol('Parent',gui.panels.info.HBox2,...
            'Style','text','FontSize',myui.fontsize,'HorizontalAlignment','center',...
            'String','TLGM          2*aad(mean)');
        uix.Empty('Parent',gui.panels.info.HBox2);
        tstr = 'AAD (average absolute deviation from mean) of all TLGM values.';
        gui.edit_handles.TLGM_aad = uicontrol('Parent',gui.panels.info.HBox2,...
            'ToolTipString',tstr,'UserData',struct('Tooltipstr',tstr),...
            'Style','edit','String','2','FontSize',myui.fontsize);
        set(gui.panels.info.HBox2,'Widths',[cpanel_w -1 -1]);
        % median TLGM
        gui.panels.info.HBox3 = uix.HBox('Parent',gui.panels.info.VBox,...
            'Spacing',3);
        gui.text_handles.TLGM_med = uicontrol('Parent',gui.panels.info.HBox3,...
            'Style','text','FontSize',myui.fontsize,'HorizontalAlignment','center',...
            'String','TLGM median | 2*aad(med)');
        tstr = 'MEDIAN of all TLGM values.';
        gui.edit_handles.TLGM_med = uicontrol('Parent',gui.panels.info.HBox3,...
            'Style','edit','String','0','FontSize',myui.fontsize,...
            'ToolTipString',tstr,'UserData',struct('Tooltipstr',tstr),...
            'BackgroundColor',colors.BoxCPS);
        tstr = 'AAD (average absolute deviation from median) of all TLGM values.';
        gui.edit_handles.TLGM_aadmed = uicontrol('Parent',gui.panels.info.HBox3,...
            'Style','edit','String','2','FontSize',myui.fontsize,...
            'ToolTipString',tstr,'UserData',struct('Tooltipstr',tstr),...
            'BackgroundColor',colors.BoxCPS);
        set(gui.panels.info.HBox3,'Widths',[cpanel_w -1 -1]);
        % mean E0
        gui.panels.info.HBox4 = uix.HBox('Parent',gui.panels.info.VBox,...
            'Spacing',3);
        gui.text_handles.E0 = uicontrol('Parent',gui.panels.info.HBox4,...
            'Style','text','FontSize',myui.fontsize,'HorizontalAlignment','center',...
            'String','E0              mean | 2*std');
        tstr = 'MEAN of all E0 values.';
        gui.edit_handles.E0_mean = uicontrol('Parent',gui.panels.info.HBox4,...
            'Style','edit','String','0','FontSize',myui.fontsize,...
            'ToolTipString',tstr,'UserData',struct('Tooltipstr',tstr),...
            'BackgroundColor',colors.BoxPRC);
        tstr = 'STD of all E0 values.';
        gui.edit_handles.E0_std = uicontrol('Parent',gui.panels.info.HBox4,...
            'Style','edit','String','2','FontSize',myui.fontsize,...
            'ToolTipString',tstr,'UserData',struct('Tooltipstr',tstr),...
            'BackgroundColor',colors.BoxPRC);
        set(gui.panels.info.HBox4,'Widths',[cpanel_w -1 -1]);
        % aad E0
        gui.panels.info.HBox5 = uix.HBox('Parent',gui.panels.info.VBox,...
            'Spacing',3);
        gui.text_handles.E0_aad = uicontrol('Parent',gui.panels.info.HBox5,...
            'Style','text','FontSize',myui.fontsize,'HorizontalAlignment','center',...
            'String','E0              2*aad(mean)');
        uix.Empty('Parent',gui.panels.info.HBox5);
        tstr = 'AAD (average absolute deviation from mean) of all E0 values.';
        gui.edit_handles.E0_aad = uicontrol('Parent',gui.panels.info.HBox5,...
            'ToolTipString',tstr,'UserData',struct('Tooltipstr',tstr),...
            'Style','edit','String','2','FontSize',myui.fontsize);
        set(gui.panels.info.HBox5,'Widths',[cpanel_w -1 -1]);
        % median E0
        gui.panels.info.HBox6 = uix.HBox('Parent',gui.panels.info.VBox,...
            'Spacing',3);
        gui.text_handles.E0_med = uicontrol('Parent',gui.panels.info.HBox6,...
            'Style','text','FontSize',myui.fontsize,'HorizontalAlignment','center',...
            'String','E0   median | 2*aad(med)');
        tstr = 'MEDIAN of all E0 values.';
        gui.edit_handles.E0_med = uicontrol('Parent',gui.panels.info.HBox6,...
            'Style','edit','String','0','FontSize',myui.fontsize,...
            'ToolTipString',tstr,'UserData',struct('Tooltipstr',tstr),...
            'BackgroundColor',colors.BoxCPS);
        tstr = 'AAD (average absolute deviation from median) of all E0 values.';
        gui.edit_handles.E0_aadmed = uicontrol('Parent',gui.panels.info.HBox6,...
            'Style','edit','String','2','FontSize',myui.fontsize,...
            'ToolTipString',tstr,'UserData',struct('Tooltipstr',tstr),...
            'BackgroundColor',colors.BoxCPS);
        set(gui.panels.info.HBox6,'Widths',[cpanel_w -1 -1]);
        % --- update MAIN GUI button ---
        gui.panels.save.VBox1 = uix.VBox('Parent',gui.left,...
            'Spacing',3);
        tstr = 'UPDATE uncertainty data in main NUCLEUSinv GUI.';
        gui.push_handles.update = uicontrol('Parent',gui.panels.save.VBox1,...
            'String','UPDATE MAIN GUI','FontSize',myui.fontsize,'Tag','update',...
            'ToolTipString',tstr,'UserData',struct('Tooltipstr',tstr),...
            'Callback',@uv_onPushUpdate);
        tstr = 'APPLY RTD bounds to all signals with uncertainty data in main NUCLEUSinv GUI.';
        gui.push_handles.apply2all = uicontrol('Parent',gui.panels.save.VBox1,...
            'String','APPLY RTD bounds 2 all','FontSize',myui.fontsize,'Tag','apply2all',...
            'ToolTipString',tstr,'UserData',struct('Tooltipstr',tstr),...
            'Callback',@uv_onPushUpdate);
        tstr = 'Export current graphics view to Figure.';
        gui.push_handles.view = uicontrol('Parent',gui.panels.save.VBox1,...
            'String','VIEW2FIG','FontSize',myui.fontsize,'Tag','view',...
            'ToolTipString',tstr,'UserData',struct('Tooltipstr',tstr),...
            'Callback',@uv_onPushView);
        % empty space at bottom of left side
        uix.Empty('Parent',gui.left);
        % adjust the heights of all left-column-panels
        heights = [22 22 22 22 28 -1; 22+6*24+8*3 22+3*24+5*3 22+2*24+4*4 22+6*24+8*3 28*3 -1];
        % panel header is always 22 high
        set(gui.left,'Heights',heights(2,:),...
            'MinimumHeights',[22 22 22 22 28 0]);
        % --- plot boxes ---
        waitbar(5/steps,hwb,'loading GUI elements - graphics');
        gui.rightPanel = uix.TabPanel('Parent',gui.right,...
            'BackGroundColor',colors.panelBG);
        % -- tab1
        gui.righttop1 = uix.HBox('Parent',gui.rightPanel,...
            'BackGroundColor',colors.panelBG,'Spacing',5);
        gui.pbox11 = uicontainer('Parent',gui.righttop1,...
            'BackGroundColor',colors.panelBG);
        gui.pbox12 = uicontainer('Parent',gui.righttop1,...
            'BackGroundColor',colors.panelBG);
        set(gui.righttop1,'Widths',[-1 -1 ]);
        gui.rightbot = uix.HBox('Parent',gui.right,...
            'BackGroundColor',colors.panelBG,'Spacing',5);
        gui.pbox2 = uicontainer('Parent',gui.rightbot,...
            'BackGroundColor',colors.panelBG);
        % -- tab2
        gui.righttop2 = uix.HBox('Parent',gui.rightPanel,...
            'BackGroundColor',colors.panelBG,'Spacing',5);
        gui.pbox21 = uicontainer('Parent',gui.righttop2,...
            'BackGroundColor',colors.panelBG);
        gui.pbox22 = uicontainer('Parent',gui.righttop2,...
            'BackGroundColor',colors.panelBG);
        set(gui.righttop2,'Widths',[-1 -1 ]);
        gui.rightPanel.TabTitles = {'STATISTICS','KDEs'};
        gui.rightPanel.TabWidth = 75;
        gui.rightPanel.TabEnables = {'on','on'};
        % -- plot axes --
        gui.axes11 = axes('Parent',gui.pbox12,'Box','on');
        gui.axes12 = axes('Parent',gui.pbox11,'Box','on');
        gui.axes2 = axes('Parent',gui.pbox2,'Box','on');
        gui.axes21 = axes('Parent',gui.pbox21,'Box','on');
        gui.axes22 = axes('Parent',gui.pbox22,'Box','on');
        % the chi2 vs. xn plot has a context menu
        gui.cm_handles.axes_chi2 = uicontextmenu(fig_uncert);
        gui.cm_handles.axes_color = uimenu(gui.cm_handles.axes_chi2,...
            'Label','color by');
        gui.cm_handles.axes_color_none = uimenu(gui.cm_handles.axes_color,...
            'Label','none','Tag','none','Checked','on',...
            'Callback',@uv_onContextPlotsColor);
        gui.cm_handles.axes_color_chi2 = uimenu(gui.cm_handles.axes_color,...
            'Label','X','Tag','chi2','Callback',@uv_onContextPlotsColor);
        gui.cm_handles.axes_color_mnorm = uimenu(gui.cm_handles.axes_color,...
            'Label',['|Lm|',char(hex2dec('2082'))],'Tag','xn','Callback',@uv_onContextPlotsColor);
        set(gui.axes12,'UIContextMenu',gui.cm_handles.axes_chi2);
        % the RTD plot has a context menu
        gui.cm_handles.axes_rtd = uicontextmenu(fig_uncert);
        gui.cm_handles.axes_rtd_lines = uimenu(gui.cm_handles.axes_rtd,...
            'Label','lines','Tag','lines','Checked','on',...
            'Callback',@uv_onContextPlotsRTD);
        gui.cm_handles.axes_rtd_patch = uimenu(gui.cm_handles.axes_rtd,...
            'Label','patch');
        gui.cm_handles.axes_rtd_patch_mean = uimenu(gui.cm_handles.axes_rtd_patch,...
            'Label','mean / std','Tag','patchmean',...
            'Callback',@uv_onContextPlotsRTD);
        gui.cm_handles.axes_rtd_patch_median = uimenu(gui.cm_handles.axes_rtd_patch,...
            'Label','median / aad','Tag','patchmedian',...
            'Callback',@uv_onContextPlotsRTD);
        set(gui.axes2,'UIContextMenu',gui.cm_handles.axes_rtd);
        % --- store main GUI settings ---
        gui.myui = nucleus.gui.myui;
        gui.myui.heights = heights;
        gui.figh_nucleus = figh_nucleus;
        % --- save gui data to GUI ---
        setappdata(fig_uncert,'gui',gui);
        fixVerticalTextAlignment(fig_uncert);
        changeColorTheme('UNCERTVIEW',myui.colors.theme);
        % make GUI visible
        delete(hwb);
        set(gui.main,'Visible','on');
        % initialize color style
        uv.colorstyle = 'none';
        % initialize RTD plot style
        uv.rtd_plotstyle = 'lines';
        % save the initial id
        uv.id0 = nucleus_data.results.invstd.uncert.params.id;
    else
        data = getappdata(fig_uncert,'data');
        uv = data.uv;
    end
    % if the figure is already open load the GUI data
    gui = getappdata(fig_uncert,'gui');
    % update new NUCLEUSinv data
    setappdata(fig_uncert,'data',nucleus_data);
    data = getappdata(fig_uncert,'data');
    % clear axes
    clearAllAxes(fig_uncert);
    % round all chi2 and xn values to 6 digits
    chi2_all = data.results.invstd.uncert.chi2_all;
    chi2_all = round(1e6.*chi2_all)./1e6;
    data.results.invstd.uncert.chi2_all = chi2_all;
    mnorm_all = data.results.invstd.uncert.mnorm_all;
    mnorm_all = round(1e6.*mnorm_all)./1e6;
    data.results.invstd.uncert.mnorm_all = mnorm_all;
    % create logical mask
    uv.touse = ones(nucleus_data.uncert.N,1);
    % --- fill the edit fields ---
    invstd = data.results.invstd;
    uncert = invstd.uncert;
    % 1.) control
    uv.uncertMethod = uncert.params.uncert.Method;
    uv.uncertN = uncert.params.uncert.N;
    set(gui.edit_handles.uncertN,'String',num2str(uv.uncertN));
    uv.uncertThresh = uncert.params.uncert.Thresh;
    set(gui.edit_handles.uncertThresh,'String',num2str(uv.uncertThresh));
    uv.uncertMax = uncert.params.uncert.Max;
    set(gui.edit_handles.uncertMax,'String',num2str(uv.uncertMax));
    uv.chi2_range_calc  = [min(uncert.chi2_all) max(uncert.chi2_all)];
    uv.mnorm_range_calc = [min(uncert.mnorm_all) max(uncert.mnorm_all)];
    % set popup menu
    switch invstd.invtype
        case {'LU','NNLS'}
            set(gui.popup_handles.uncertMethod,...
                'String',{'RMS - unbounded','RMS - bounded'})
            switch uncert.params.uncert.Method
                case 'RMS_free'
                    set(gui.popup_handles.uncertMethod,'Value',1);
                case 'RMS_bound'
                    set(gui.popup_handles.uncertMethod,'Value',2);
            end
        case 'MUMO'
            set(gui.popup_handles.uncertMethod,...
                'String',{'RMS - unbounded','RMS - bounded','Threshold','Conf. Interval'})
            switch uncert.params.uncert.Method
                case 'RMS_free'
                    set(gui.popup_handles.uncertMethod,'Value',1);
                case 'RMS_bound'
                    set(gui.popup_handles.uncertMethod,'Value',2);
                case 'thresh'
                    set(gui.popup_handles.uncertMethod,'Value',3);
                case 'ci'
                    set(gui.popup_handles.uncertMethod,'Value',4);
            end
    end
    set(gui.edit_handles.uncertN,'String',num2str(uncert.params.uncert.N));
    % 2.) process
    chi2_range  = uv.chi2_range_calc;
    mnorm_range = uv.mnorm_range_calc;
    set(gui.edit_handles.chi2_min,'String',sprintf('%7.6f',chi2_range(1,1)));
    set(gui.edit_handles.chi2_max,'String',sprintf('%7.6f',chi2_range(1,2)));
    set(gui.edit_handles.mnorm_min,'String',sprintf('%7.6f',mnorm_range(1,1)));
    set(gui.edit_handles.mnorm_max,'String',sprintf('%7.6f',mnorm_range(1,2)));
    % 3.) RTD range
    rtd_range = uncert.statistics.RTD_bounds;
    set(gui.edit_handles.rtd_min,'String',num2str(rtd_range(1,1)));
    set(gui.edit_handles.rtd_max,'String',num2str(rtd_range(1,2)));
    uv.chi2_range = chi2_range;
    uv.mnorm_range = mnorm_range;
    uv.rtd_range = rtd_range;
    % update data
    data.uv = uv;
    setappdata(fig_uncert,'data',data);
    uv_onPopupMethod(gui.popup_handles.uncertMethod);
    % plot all uncertainty data
    uv_updateInformation(fig_uncert);
    beautifyAxes(fig_uncert);
end
end
%% subfunction to update the edit fields
function uv_onEditValue(src,~)
figh = ancestor(src,'figure','toplevel');
gui = getappdata(figh,'gui');
data = getappdata(figh,'data');
uv = data.uv;
% get the edit field value
val = str2double(get(src,'String'));
switch get(src,'Tag')
    case 'uncertN'
        if val < 10
            uncertN = 10;
        else
            uncertN = round(val);
        end
        set(src,'String',num2str(uncertN));
        uv.uncertN = uncertN;
        data.uv = uv;
    case 'uncertThresh'
    case 'uncertMax'
    case 'control'
        % set the value with the desired layout
        set(src,'String',sprintf('%7.6f',val));
        chi2_range_calc(1,1) = str2double(get(gui.edit_handles.uncertchi2_min,'String'));
        chi2_range_calc(1,2) = str2double(get(gui.edit_handles.uncertchi2_max,'String'));
        mnorm_range_calc(1,1) = str2double(get(gui.edit_handles.uncertmnorm_min,'String'));
        mnorm_range_calc(1,2) = str2double(get(gui.edit_handles.uncertmnorm_max,'String'));
        % update data
        uv.chi2_range_calc = chi2_range_calc;
        uv.mnorm_range_calc = mnorm_range_calc;
        data.uv = uv;
    case 'process'
        % set the value with the desired layout
        set(src,'String',sprintf('%7.6f',val));
        % get all range values
        chi2_range(1,1) = str2double(get(gui.edit_handles.chi2_min,'String'));
        chi2_range(1,2) = str2double(get(gui.edit_handles.chi2_max,'String'));
        mnorm_range(1,1) = str2double(get(gui.edit_handles.mnorm_min,'String'));
        mnorm_range(1,2) = str2double(get(gui.edit_handles.mnorm_max,'String'));
        % fix wrong user input
        if chi2_range(2) <= chi2_range(1)
            warndlg({'function: UNCERTVIEW',...
                'Lower bound is larger than upper bound!'},...
                'Resetting.');
            chi2_range(1) = min(data.results.invstd.uncert.chi2_all);
            chi2_range(2) = max(data.results.invstd.uncert.chi2_all);
            set(gui.edit_handles.chi2_min,'String',sprintf('%7.6f',chi2_range(1)));
            set(gui.edit_handles.chi2_max,'String',sprintf('%7.6f',chi2_range(2)));
        end
        if mnorm_range(2) <= mnorm_range(1)
            warndlg({'function: UNCERTVIEW',...
                'Lower bound is larger than upper bound!'},...
                'Resetting.');
            mnorm_range(1) = min(data.results.invstd.uncert.mnorm_all);
            mnorm_range(2) = max(data.results.invstd.uncert.mnorm_all);
            set(gui.edit_handles.mnorm_min,'String',sprintf('%7.6f',mnorm_range(1)));
            set(gui.edit_handles.mnorm_max,'String',sprintf('%7.6f',mnorm_range(2)));
        end
        % update data
        uv.chi2_range = chi2_range;
        uv.mnorm_range = mnorm_range;
        data.uv = uv;
        % update logical mask for plotting
        data = uv_updateMASK(data);
    case 'rtd'
        % set the value with the desired layout
        set(src,'String',num2str(val));
        % get all range values
        rtd_range(1,1) = str2double(get(gui.edit_handles.rtd_min,'String'));
        rtd_range(1,2) = str2double(get(gui.edit_handles.rtd_max,'String'));
        % update data
        uv.rtd_range = rtd_range;
        data.uv = uv;
end
% in case of error reactivate the run button
set(gui.push_handles.run,'String','RUN UNCERT',...
    'BackgroundColor','g','Enable','on','Callback',@uv_onPushRun);
setappdata(figh,'gui',gui);
% update GUI data
setappdata(figh,'data',data);
% update information
uv_updateInformation(figh);
end
%% subfunction to copy the chi2 and xn range to the control panel
function uv_onPushSend(src,~)
figh = ancestor(src,'figure','toplevel');
gui = getappdata(figh,'gui');
data = getappdata(figh,'data');
uv = data.uv;
% get all data
chi2_range(1,1) = str2double(get(gui.edit_handles.chi2_min,'String'));
chi2_range(1,2) = str2double(get(gui.edit_handles.chi2_max,'String'));
mnorm_range(1,1) = str2double(get(gui.edit_handles.mnorm_min,'String'));
mnorm_range(1,2) = str2double(get(gui.edit_handles.mnorm_max,'String'));
% copy data to calc
uv.chi2_range_calc = chi2_range;
uv.mnorm_range_calc = mnorm_range;
data.uv = uv;
% write values to edit field
set(gui.edit_handles.uncertchi2_min,...
    'String',sprintf('%7.6f',uv.chi2_range_calc(1)));
set(gui.edit_handles.uncertchi2_max,...
    'String',sprintf('%7.6f',uv.chi2_range_calc(2)));
set(gui.edit_handles.uncertmnorm_min,...
    'String',sprintf('%7.6f',uv.mnorm_range_calc(1)));
set(gui.edit_handles.uncertmnorm_max,...
    'String',sprintf('%7.6f',uv.mnorm_range_calc(2)));
% update GUI data
setappdata(figh,'data',data);
end
%% subfunction to control the line color
function uv_onContextPlotsColor(src,~)
figh = ancestor(src,'figure','toplevel');
gui = getappdata(figh,'gui');
data = getappdata(figh,'data');
uv = data.uv;
% switch through different plot options
switch get(src,'Tag')
    case 'none'
        set(gui.cm_handles.axes_color_none,'Checked','on');
        set(gui.cm_handles.axes_color_chi2,'Checked','off');
        set(gui.cm_handles.axes_color_mnorm,'Checked','off');
    case 'chi2'
        set(gui.cm_handles.axes_color_none,'Checked','off');
        set(gui.cm_handles.axes_color_chi2,'Checked','on');
        set(gui.cm_handles.axes_color_mnorm,'Checked','off');
    case 'xn'
        set(gui.cm_handles.axes_color_none,'Checked','off');
        set(gui.cm_handles.axes_color_chi2,'Checked','off');
        set(gui.cm_handles.axes_color_mnorm,'Checked','on');
end
uv.colorstyle = get(src,'Tag');
% update GUI data
data.uv = uv;
setappdata(figh,'data',data);
% update information and plots
uv_updateInformation(figh);
end
%% subfunction to control RTD axes context menu
function uv_onContextPlotsRTD(src,~)
figh = ancestor(src,'figure','toplevel');
gui = getappdata(figh,'gui');
data = getappdata(figh,'data');
uv = data.uv;
% switch through different plot options
switch get(src,'Tag')
    case 'lines'
        set(gui.cm_handles.axes_rtd_lines,'Checked','on');
        set(gui.cm_handles.axes_rtd_patch_mean,'Checked','off');
        set(gui.cm_handles.axes_rtd_patch_median,'Checked','off');
    case 'patchmean'
        set(gui.cm_handles.axes_rtd_lines,'Checked','off');
        set(gui.cm_handles.axes_rtd_patch_mean,'Checked','on');
        set(gui.cm_handles.axes_rtd_patch_median,'Checked','off');
    case 'patchmedian'
        set(gui.cm_handles.axes_rtd_lines,'Checked','off');
        set(gui.cm_handles.axes_rtd_patch_mean,'Checked','off');
        set(gui.cm_handles.axes_rtd_patch_median,'Checked','on');
end
uv.rtd_plotstyle = get(src,'Tag');
% update GUI data
data.uv = uv;
setappdata(figh,'data',data);
% update information and plots
uv_updateInformation(figh);
end
%% subfunction to update the logical mask
function data = uv_updateMASK(data)
uncert = data.results.invstd.uncert;
uv = data.uv;
mask1 = uncert.chi2_all >= uv.chi2_range(1) & uncert.chi2_all <= uv.chi2_range(2);
mask2 = uncert.mnorm_all >= uv.mnorm_range(1) & uncert.mnorm_all <= uv.mnorm_range(2);
uv.touse = mask1 & mask2;
data.uv = uv;
end
%% subfunction to update control panel based on uncertainty method
function uv_onPopupMethod(src,~)
figh = ancestor(src,'figure','toplevel');
gui = getappdata(figh,'gui');
data = getappdata(figh,'data');
uv = data.uv;
invstd = data.results.invstd;
val = get(gui.popup_handles.uncertMethod,'Value');
switch invstd.invtype
    case {'LU','NNLS'}
        switch val
            case 1 % RMS_free
                uv.uncertMethod = 'RMS_free';
                set(gui.edit_handles.uncertchi2_min,'Enable','off');
                set(gui.edit_handles.uncertchi2_max,'Enable','off');
                set(gui.edit_handles.uncertmnorm_min,'Enable','off');
                set(gui.edit_handles.uncertmnorm_max,'Enable','off');
                set(gui.edit_handles.uncertThresh,'Enable','off');
                set(gui.edit_handles.uncertMax,'Enable','off');
            case 2 % RMS_bound
                uv.uncertMethod = 'RMS_bound';
                set(gui.edit_handles.uncertchi2_min,'Enable','on',...
                    'String',sprintf('%7.6f',uv.chi2_range_calc(1)));
                set(gui.edit_handles.uncertchi2_max,'Enable','on',...
                    'String',sprintf('%7.6f',uv.chi2_range_calc(2)));
                set(gui.edit_handles.uncertmnorm_min,'Enable','on',...
                    'String',sprintf('%7.6f',uv.mnorm_range_calc(1)));
                set(gui.edit_handles.uncertmnorm_max,'Enable','on',...
                    'String',sprintf('%7.6f',uv.mnorm_range_calc(2)));
                set(gui.edit_handles.uncertThresh,'Enable','off');
                set(gui.edit_handles.uncertMax,'Enable','on',...
                    'String',num2str(uv.uncertMax));
        end
    case 'MUMO'
        switch val
            case 1 % RMS_free
                uv.uncertMethod = 'RMS_free';
                set(gui.edit_handles.uncertchi2_min,'Enable','off');
                set(gui.edit_handles.uncertchi2_max,'Enable','off');
                set(gui.edit_handles.uncertmnorm_min,'Enable','off');
                set(gui.edit_handles.uncertmnorm_max,'Enable','off');
                set(gui.edit_handles.uncertThresh,'Enable','off');
                set(gui.edit_handles.uncertMax,'Enable','off');
            case 2 % RMS_bound
                uv.uncertMethod = 'RMS_bound';
                set(gui.edit_handles.uncertchi2_min,'Enable','on',...
                    'String',sprintf('%7.6f',uv.chi2_range_calc(1)));
                set(gui.edit_handles.uncertchi2_max,'Enable','on',...
                    'String',sprintf('%7.6f',uv.chi2_range_calc(2)));
                set(gui.edit_handles.uncertmnorm_min,'Enable','on',...
                    'String',sprintf('%7.6f',uv.mnorm_range_calc(1)));
                set(gui.edit_handles.uncertmnorm_max,'Enable','on',...
                    'String',sprintf('%7.6f',uv.mnorm_range_calc(2)));
                set(gui.edit_handles.uncertThresh,'Enable','off');
                set(gui.edit_handles.uncertMax,'Enable','on',...
                    'String',num2str(uv.uncertMax));
            case 3 % threshold
                uv.uncertMethod = 'thresh';
                uv.chi2_range_calc = [0 10];
                uv.mnorm_range_calc = [0 10];
                set(gui.edit_handles.uncertchi2_min,'Enable','on',...
                    'String',sprintf('%7.6f',uv.chi2_range_calc(1)));
                set(gui.edit_handles.uncertchi2_max,'Enable','on',...
                    'String',sprintf('%7.6f',uv.chi2_range_calc(2)));
                set(gui.edit_handles.uncertmnorm_min,'Enable','on',...
                    'String',sprintf('%7.6f',uv.mnorm_range_calc(1)));
                set(gui.edit_handles.uncertmnorm_max,'Enable','on',...
                    'String',sprintf('%7.6f',uv.mnorm_range_calc(2)));
                set(gui.edit_handles.uncertThresh,'Enable','on');
                set(gui.edit_handles.uncertMax,'Enable','on',...
                    'String',num2str(uv.uncertMax));
            case 4 % ci - confidence intrval
                uv.uncertMethod = 'ci';
                uv.chi2_range_calc = [0 10];
                uv.mnorm_range_calc = [0 10];
                set(gui.edit_handles.uncertchi2_min,'Enable','on',...
                    'String',sprintf('%7.6f',uv.chi2_range_calc(1)));
                set(gui.edit_handles.uncertchi2_max,'Enable','on',...
                    'String',sprintf('%7.6f',uv.chi2_range_calc(2)));
                set(gui.edit_handles.uncertmnorm_min,'Enable','on',...
                    'String',sprintf('%7.6f',uv.mnorm_range_calc(1)));
                set(gui.edit_handles.uncertmnorm_max,'Enable','on',...
                    'String',sprintf('%7.6f',uv.mnorm_range_calc(2)));
                set(gui.edit_handles.uncertThresh,'Enable','off');
                set(gui.edit_handles.uncertMax,'Enable','on',...
                    'String',num2str(uv.uncertMax));
        end
end
% update GUI data
data.uv = uv;
setappdata(figh,'data',data);
end
%% subfunction to start a new uncertainty calculation
function uv_onPushRun(src,~)
figh = ancestor(src,'figure','toplevel');
gui = getappdata(figh,'gui');
data = getappdata(figh,'data');
uv = data.uv;
invstd = data.results.invstd;
uncert = invstd.uncert;
% disable the CALC: button to indicate a running calculation
set(gui.push_handles.run,'String','RUNNING ...','Enable','off');
pause(0.01);
% original fit parameter
iparam = invstd.invparams;
% original uncertainty parameter
uparam = uncert.params;
% new uncertainty parameter from GUI
uparam.uncert.Method = uv.uncertMethod;
uparam.uncert.Thresh = uv.uncertThresh;
uparam.uncert.chi2_range = uv.chi2_range_calc;
uparam.uncert.mnorm_range = uv.mnorm_range_calc;
uparam.uncert.N = uv.uncertN;
uparam.uncert.Max = uv.uncertMax;
invstd = estimateUncertainty(invstd.invtype,invstd,iparam,uparam);
% enable the CALC. button
set(gui.push_handles.run,'String','RUN UNCERT',...
    'BackgroundColor','g','Enable','on','Callback',@uv_onPushRun);
setappdata(figh,'gui',gui);
% save updated inversion results
invstd.uncert.params = uparam;
data.results.invstd = invstd;
% update GUI data
% round all chi2 and xn values to 6 digits
chi2_all = data.results.invstd.uncert.chi2_all;
chi2_all = round(1e6.*chi2_all)./1e6;
data.results.invstd.uncert.chi2_all = chi2_all;
mnorm_all = data.results.invstd.uncert.mnorm_all;
mnorm_all = round(1e6.*mnorm_all)./1e6;
data.results.invstd.uncert.mnorm_all = mnorm_all;
% create logical mask
uv.touse = ones(uv.uncertN,1);
% 1.) control
uv.chi2_range_calc = [min(chi2_all) max(chi2_all)];
uv.mnorm_range_calc = [min(mnorm_all) max(mnorm_all)];
% 2.) process
uv.chi2_range = uv.chi2_range_calc;
uv.mnorm_range = uv.mnorm_range_calc;
set(gui.edit_handles.chi2_min,'String',sprintf('%7.6f',uv.chi2_range(1,1)));
set(gui.edit_handles.chi2_max,'String',sprintf('%7.6f',uv.chi2_range(1,2)));
set(gui.edit_handles.mnorm_min,'String',sprintf('%7.6f',uv.mnorm_range(1,1)));
set(gui.edit_handles.mnorm_max,'String',sprintf('%7.6f',uv.mnorm_range(1,2)));
% update data
data.uv = uv;
setappdata(figh,'data',data);
% plot all uncertainty data
uv_updateInformation(figh);
beautifyAxes(figh);
end
%% subfunction to export the current view to a figure
function uv_onPushView(src,~)
figh = ancestor(src,'figure','toplevel');
% local GUI data
gui = getappdata(figh,'gui');
% opening the export figure
expfig = figure('Color',gui.myui.colors.panelBG);
% create axes layout depending on view
switch get(gui.rightPanel,'Selection')
    case 1
        % create layout
        ax1 = subplot(2,2,1,'Parent',expfig);
        ax2 = subplot(2,2,2,'Parent',expfig);
        ax3 = subplot(2,2,[3 4],'Parent',expfig);
        % get positions
        pos1 = get(ax1,'Position');
        pos2 = get(ax2,'Position');
        pos3 = get(ax3,'Position');
        % delete axes
        delete(ax1);delete(ax2);delete(ax3);
        % copy GUI axes
        ax1 = copyobj(gui.axes12,expfig);
1000         ax2 = copyobj(gui.axes11,expfig);
1001         ax3 = copyobj(gui.axes2,expfig);
1002         % adjust positions
1003         set(ax1,'Position',pos1);
1004         set(ax2,'Position',pos2);
1005         set(ax3,'Position',pos3);
1006         % legend
1007         lgh1 = legend(ax2,'Location','best');
1008         set(lgh1,'EdgeColor',gui.myui.colors.axisFG,...
1009             'TextColor',gui.myui.colors.axisFG);
1010     case 2
1011         % create layout
1012         ax1 = subplot(2,2,1,'Parent',expfig);
1013         ax2 = subplot(2,2,2,'Parent',expfig);
1014         ax3 = subplot(2,2,[3 4],'Parent',expfig);
1015         % get positions
1016         pos1 = get(ax1,'Position');
1017         pos2 = get(ax2,'Position');
1018         pos3 = get(ax3,'Position');
1019         % delete axes
1020         delete(ax1);delete(ax2);delete(ax3);
1021         % copy GUI axes
1022         ax1 = copyobj(gui.axes21,expfig);
1023         ax2 = copyobj(gui.axes22,expfig);
1024         ax3 = copyobj(gui.axes2,expfig);
1025         % adjust positions
1026         set(ax1,'Position',pos1);
1027         set(ax2,'Position',pos2);
1028         set(ax3,'Position',pos3);
1029         % legend
1030         lgh2 = legend(ax2,'Location','best');
1031         set(lgh2,'EdgeColor',gui.myui.colors.axisFG,...
1032             'TextColor',gui.myui.colors.axisFG);
1033 end
1034
1035 end
1036
1037 %% subfunction to update the main NUCLEUSinv GUI
1038 function uv_onPushUpdate(src,~)
1039 figh = ancestor(src,'figure','toplevel');
1040 % local GUI data
1041 uvgui = getappdata(figh,'gui');
1042 uvdata = getappdata(figh,'data');
1043 % NUCLEUSinv data
1044 gui = getappdata(uvgui.figh_nucleus,'gui');
1045 data = getappdata(uvgui.figh_nucleus,'data');
1046 INVdata = getappdata(uvgui.figh_nucleus,'INVdata');
1047
1048 switch get(src,'Tag')
1049     case 'update'
1050         % update single data
1051
1052         % get signal id
1053         id = uvdata.uv.id0;
1054         % get data
1055         INVdata0 = INVdata{id};
1056
1057         % --- update data ---
1058         % -- general settings --
1059         data.uncert.N = uvdata.uv.uncertN;
1060         data.uncert.Method = uvdata.uv.uncertMethod;
1061         data.uncert.Thresh = uvdata.uv.uncertThresh;
1062         data.uncert.Max = uvdata.uv.uncertMax;
1063
1064         % -- check if data was excluded --
1065         if sum(uvdata.uv.touse == 0) > 0
1066             % if yes, proceed
1067             in = uvdata.uv.touse == 1;
1068             data.uncert.N = sum(in);
1069             uvdata.results.invstd.uncert.params.uncert.N = sum(in);
1070             uvdata.results.invstd.uncert.chi2_all = uvdata.results.invstd.uncert.chi2_all(in);
1071             uvdata.results.invstd.uncert.mnorm_all = uvdata.results.invstd.uncert.mnorm_all(in);
1072             uvdata.results.invstd.uncert.rnorm_all = uvdata.results.invstd.uncert.rnorm_all(in);
1073             uvdata.results.invstd.uncert.interp_f = uvdata.results.invstd.uncert.interp_f(in,:);
1074             uvdata.results.invstd.uncert.interp_s = uvdata.results.invstd.uncert.interp_s(:,in');
1075             uvdata.results.invstd.uncert.interp_E0 = uvdata.results.invstd.uncert.interp_E0(in);
1076             uvdata.results.invstd.uncert.E0 = [mean(uvdata.results.invstd.uncert.interp_E0) std(uvdata.results.invstd.uncert.interp_E0)];
1077             uvdata.results.invstd.uncert.interp_Tlgm = uvdata.results.invstd.uncert.interp_Tlgm(in);
1078             uvdata.results.invstd.uncert.Tlgm = [mean(uvdata.results.invstd.uncert.interp_Tlgm) std(uvdata.results.invstd.uncert.interp_Tlgm)];
1079         end
1080
1081         % add statisitics
1082         uvdata.results.invstd.uncert.statistics = uvdata.uv.stats;
1083
1084         % update data structs
1085         data.results.invstd.uncert = uvdata.results.invstd.uncert;
1086         INVdata0.uncert = data.uncert;
1087         INVdata0.results.invstd = uvdata.results.invstd;
1088
1089         % update INVdata
1090         INVdata{id} = INVdata0;
1091         % update GUI data
1092         setappdata(uvgui.figh_nucleus,'data',data);
1093         % update GUI INVdata
1094         setappdata(uvgui.figh_nucleus,'INVdata',INVdata);
1095
1096         % update relevant GUI elements
1097         set(gui.edit_handles.uncert_N,'String',num2str(data.results.invstd.uncert.params.uncert.N))
1098
1099         % update plots and INFO fields in main NUCLEUS GUI
1100         updatePlotsSignal;
1101         updatePlotsDistribution;
1102         updateInfo(gui.plots.SignalPanel);
1103
1104     case 'apply2all'
1105
1106         % calculate statistics for all signals in main GUI using the
1107         % current RTD bounds
1108         infostring = 'Apply UncertView RTD bounds 2 all ... ';
1109         displayStatusText(gui,infostring);
1110         % loop over all signals
1111         for id = 1:numel(INVdata)
1112             % only if there is Inversion data
1113             if isstruct(INVdata{id})
1114                 INVdataT = INVdata{id};
1115                 invstdT = INVdataT.results.invstd;
1116                 % only if there is already uncertainty data
1117                 if isfield(invstdT,'uncert')
1118                     uncertT = invstdT.uncert;
1119                     uvT = uvdata.uv;
1120
1121                     % RTD time vector
1122                     T = INVdataT.results.invstd.T1T2me;
1123                     % kernel matrices for pure (single) E0 estimation
1124                     iparam = invstdT.invparams;
1125                     switch iparam.T1T2
1126                         case 'T1'
1127                             K0 = createKernelMatrix(10*INVdataT.results.nmrproc.t(end),T',...
1128                                 iparam.Tb,iparam.Td,'T1',iparam.T1IRfac);
1129                         case 'T2'
1130                             K0 = createKernelMatrix(0,T',iparam.Tb,...
1131                                 iparam.Td,'T2',iparam.T1IRfac);
1132                     end
1133                     % get statistics
1134                     stats = getUncertaintyStatistics(T,uncertT.interp_f,uvT.rtd_range,K0);
1135
1136                     % TLGM
1137                     uvT.Tlgm = [stats.Tlgm(1) stats.Tlgm(2)];
1138                     % aad - mean
1139                     uvT.Tlgm_aad = stats.Tlgm(3);
1140                     % aad - median
1141                     uvT.Tlgm_aadmed = [stats.Tlgm_med(1) stats.Tlgm_med(2)];
1142                     % E0
1143                     uvT.E0 = [stats.E0(1) stats.E0(2)];
1144                     % aad - mean
1145                     uvT.E0_aad = stats.E0(3);
1146                     % aad - median
1147                     uvT.E0_aadmed = [stats.E0_med(1) stats.E0_med(2)];
1148
1149                     uvT.stats = stats;
1150
1151                     % add statisitics
1152                     INVdataT.results.invstd.uncert.statistics = stats;
1153                     % update data structs
1154                     INVdata{id} = INVdataT;
1155                 end
1156             end
1157         end
1158         % update GUI INVdata
1159         setappdata(uvgui.figh_nucleus,'INVdata',INVdata);
1160         infostring = 'Apply UncertView RTD bounds 2 all ... done';
1161         displayStatusText(gui,infostring);
1162 end
1163
1164 end
1165
1166 %% subfunction to reset chi2 and model norm bounds
1167 function uv_onPushReset(src,~)
1168 figh = ancestor(src,'figure','toplevel');
1169 gui = getappdata(figh,'gui');
1170 data = getappdata(figh,'data');
1171 uv = data.uv;
1172 invstd = data.results.invstd;
1173 uncert = invstd.uncert;
1174
1175 switch get(src,'Tag')
1176     case 'process'
1177         % reset to original values
1178         chi2_range  = [min(uncert.chi2_all) max(uncert.chi2_all)];
1179         mnorm_range = [min(uncert.mnorm_all) max(uncert.mnorm_all)];
1180         % update edit fields
1181         set(gui.edit_handles.chi2_min,'String',sprintf('%7.6f',chi2_range(1,1)));
1182         set(gui.edit_handles.chi2_max,'String',sprintf('%7.6f',chi2_range(1,2)));
1183         set(gui.edit_handles.mnorm_min,'String',sprintf('%7.6f',mnorm_range(1,1)));
1184         set(gui.edit_handles.mnorm_max,'String',sprintf('%7.6f',mnorm_range(1,2)));
1185         % update data
1186         uv.chi2_range = chi2_range;
1187         uv.mnorm_range = mnorm_range;
1188         data.uv = uv;
1189         % update logical mask for plotting
1190         data = uv_updateMASK(data);
1191     case 'rtd'
1192         % reset to original values
1193         rtd_range = data.invstd.time;
1194         % update edit fields
1195         set(gui.edit_handles.rtd_min,'String',num2str(rtd_range(1,1)));
1196         set(gui.edit_handles.rtd_max,'String',num2str(rtd_range(1,2)));
1197         % update data
1198         uv.rtd_range = rtd_range;
1199         data.uv = uv;
1200 end
1201
1202 setappdata(figh,'data',data);
1203 % update information
1204 uv_updateInformation(figh);
1205 end
1206
1207 %% subfunction to update the information output
1208 function uv_updateInformation(figh)
1209 gui = getappdata(figh,'gui');
1210 data = getappdata(figh,'data');
1211 invstd = data.results.invstd;
1212 uncert = invstd.uncert;
1213 uv = data.uv;
1214
1215 % which models to use
1216 in = data.uv.touse == 1;
1217 % RTD time vector
1218 T = data.results.invstd.T1T2me;
1219 % kernel matrices for pure (single) E0 estimation
1220 iparam = invstd.invparams;
1221 switch iparam.T1T2
1222     case 'T1'
1223         K0 = createKernelMatrix(10*data.results.nmrproc.t(end),T',...
1224             iparam.Tb,iparam.Td,'T1',iparam.T1IRfac);
1225     case 'T2'
1226         K0 = createKernelMatrix(0,T',iparam.Tb,...
1227             iparam.Td,'T2',iparam.T1IRfac);
1228 end
1229 % get statistics
1230 stats = getUncertaintyStatistics(T,uncert.interp_f(in,:),uv.rtd_range,K0);
1231
1232 % assign to GUI fields
1233 % TLGM
1234 uv.Tlgm = [stats.Tlgm(1) stats.Tlgm(2)];
1235 set(gui.edit_handles.TLGM_mean,'String',sprintf('%5.4f',uv.Tlgm(1)));
1236 set(gui.edit_handles.TLGM_std,'String',sprintf('%5.4f',2*uv.Tlgm(2)));
1237 % aad - mean
1238 uv.Tlgm_aad = stats.Tlgm(3);
1239 set(gui.edit_handles.TLGM_aad,'String',sprintf('%5.4f',2*uv.Tlgm_aad));
1240 % aad - median
1241 uv.Tlgm_aadmed = [stats.Tlgm_med(1) stats.Tlgm_med(2)];
1242 set(gui.edit_handles.TLGM_med,'String',sprintf('%5.4f',uv.Tlgm_aadmed(1)));
1243 set(gui.edit_handles.TLGM_aadmed,'String',sprintf('%5.4f',2*uv.Tlgm_aadmed(2)));
1244 % E0
1245 uv.E0 = [stats.E0(1) stats.E0(2)];
1246 set(gui.edit_handles.E0_mean,'String',sprintf('%5.4f',uv.E0(1)));
1247 set(gui.edit_handles.E0_std,'String',sprintf('%5.4f',2*uv.E0(2)));
1248 % aad - mean
1249 uv.E0_aad = stats.E0(3);
1250 set(gui.edit_handles.E0_aad,'String',sprintf('%5.4f',2*uv.E0_aad));
1251 % aad - median
1252 uv.E0_aadmed = [stats.E0_med(1) stats.E0_med(2)];
1253 set(gui.edit_handles.E0_med,'String',sprintf('%5.4f',uv.E0_aadmed(1)));
1254 set(gui.edit_handles.E0_aadmed,'String',sprintf('%5.4f',2*uv.E0_aadmed(2)));
1255
1256 % update GUI data
1257 uv.stats = stats;
1258 data.uv = uv;
1259 setappdata(figh,'data',data);
1260 % update plots
1261 uv_updatePlots(figh);
1262 end
1263
1264 %% subfunction to update all plots
1265 function uv_updatePlots(figh)
1266 gui = getappdata(figh,'gui');
1267 data = getappdata(figh,'data');
1268
1269 % clear axes
1270 clearAllAxes(figh);
1271 hold(gui.axes11,'on');
1272 hold(gui.axes12,'on');
1273 hold(gui.axes2,'on');
1274 hold(gui.axes21,'on');
1275 hold(gui.axes22,'on');
1276
1277 % get relevant data
1278 uv = data.uv;
1279 invstd = data.results.invstd;
1280 uncert = invstd.uncert;
1281 col = gui.myui.colors;
1282
1283 % get indices for models to use and not to use
1284 in = data.uv.touse == 1;
1285 out = data.uv.touse == 0;
1286
1287 switch uv.colorstyle
1288     case 'none'
1289         % default gray
1290         lcolors = [0.5 0.5 0.5];
1291         tmpchi2 = uncert.chi2_all(in);
1292         tmpmnorm = uncert.mnorm_all(in);
1293         % tmpE0 = uncert.interp_E0(in);
1294         % tmpTlgm = uncert.interp_Tlgm(in);
1295         tmpE0 = uv.stats.E0_all;
1296         tmpTlgm = uv.stats.Tlgm_all;
1297         clims = [0 1];
1298     case 'chi2'
1299         tmp = uncert.chi2_all(in);
1300         [tmpchi2,idx] = sort(tmp);
1301         lcolors = tmpchi2;
1302         tmpmnorm = uncert.mnorm_all(in);
1303         tmpmnorm = tmpmnorm(idx);
1304         % tmpE0 = uncert.interp_E0(in);
1305         tmpE0 = uv.stats.E0_all;
1306         tmpE0 = tmpE0(idx);
1307         % tmpTlgm = uncert.interp_Tlgm(in);
1308         tmpTlgm = uv.stats.Tlgm_all;
1309         tmpTlgm = tmpTlgm(idx);
1310         % clims = [min(uncert.chi2_all) max(uncert.chi2_all)];
1311         clims = [min(uncert.chi2_all(in)) max(uncert.chi2_all(in))];
1312     case 'xn'
1313         tmp = uncert.mnorm_all(in);
1314         [tmpmnorm,idx] = sort(tmp);
1315         lcolors = tmpmnorm;
1316         tmpchi2 = uncert.chi2_all(in);
1317         tmpchi2 = tmpchi2(idx);
1318         % tmpE0 = uncert.interp_E0(in);
1319         tmpE0 = uv.stats.E0_all;
1320         tmpE0 = tmpE0(idx);
1321         % tmpTlgm = uncert.interp_Tlgm(in);
1322         tmpTlgm = uv.stats.Tlgm_all;
1323         tmpTlgm = tmpTlgm(idx);
1324         % clims = [min(uncert.mnorm_all) max(uncert.mnorm_all)];
1325         clims = [min(uncert.mnorm_all(in)) max(uncert.mnorm_all(in))];
1326 end
1327
1328 % --- chi2 vs model norm ---
1329 scatter(uncert.chi2_all(out),uncert.mnorm_all(out),[],'red',...
1330     'LineWidth',1,'Parent',gui.axes12);
1331 scatter(gui.axes12,tmpchi2,tmpmnorm,[],lcolors,...
1332     'LineWidth',1);
1333 plot(invstd.chi2,invstd.xn,'+','MarkerSize',10,'Color',col.FIT,'Parent',gui.axes12);
1334 % axis limits
1335 xlims = [min([uncert.chi2_all(in); invstd.chi2]) max([uncert.chi2_all(in); invstd.chi2])];
1336 dx = xlims(2)-xlims(1);
1337 xlims = [xlims(1)-dx/5 xlims(2)+dx/5];
1338 ylims = [min([uncert.mnorm_all(in); invstd.xn]) max([uncert.mnorm_all(in); invstd.xn])];
1339 dy = ylims(2)-ylims(1);
1340 ylims = [ylims(1)-dy/5 ylims(2)+dy/5];
1341 % -- lines indicating TLGM and E0 bounds --
1342 line([min(uncert.chi2_all(in)) min(uncert.chi2_all(in))],[ylims(1) ylims(2)],'Color',[0.25 0.25 0.25],...
1343     'LineStyle',':','LineWidth',0.75,'Parent',gui.axes12,'Tag','infolines');
1344 line([max(uncert.chi2_all(in)) max(uncert.chi2_all(in))],[ylims(1) ylims(2)],'Color',[0.25 0.25 0.25],...
1345     'LineStyle',':','LineWidth',0.75,'Parent',gui.axes12,'Tag','infolines');
1346 line([xlims(1) xlims(2)],[min(uncert.mnorm_all(in)) min(uncert.mnorm_all(in))],'Color',[0.25 0.25 0.25],...
1347     'LineStyle',':','LineWidth',0.75,'Parent',gui.axes12,'Tag','infolines');
1348 line([xlims(1) xlims(2)],[max(uncert.mnorm_all(in)) max(uncert.mnorm_all(in))],'Color',[0.25 0.25 0.25],...
1349     'LineStyle',':','LineWidth',0.75,'Parent',gui.axes12,'Tag','infolines');
1350 % axis setings
1351 set(gui.axes12,'XScale','lin','XLim',xlims);
1352 set(gui.axes12,'YScale','log','YLim',ylims);
1353 set(gui.axes12,'CLim',clims);
1354 set(get(gui.axes12,'XLabel'),'String','X (error weighted residuals)');
1355 set(get(gui.axes12,'YLabel'),'String','model norm |Lm|_{2}');
1356
1357 % --- TLGM vs E0 ---
1358 scatter(uncert.interp_Tlgm(out),uncert.interp_E0(out),[],'red',...
1359     'LineWidth',1,'DisplayName','runs (out)','Parent',gui.axes11);
1360 scatter(tmpTlgm,tmpE0,[],lcolors,...
1361     'LineWidth',1,'DisplayName','runs (in)','Parent',gui.axes11);
1362 plot(invstd.Tlgm,invstd.E0,'+','MarkerSize',10,'Color',col.FIT,...
1363     'DisplayName','init','Parent',gui.axes11);
1364 errorbar(uv.Tlgm(1),uv.E0(1),2*uv.E0(2),2*uv.E0(2),2*uv.Tlgm(2),2*uv.Tlgm(2),...
1365     'Color',col.BoxPRC,'LineWidth',2,'DisplayName','mean (2*std)','Parent',gui.axes11);
1366 errorbar(uv.Tlgm_aadmed(1),uv.E0_aadmed(1),2*uv.E0_aadmed(2),2*uv.E0_aadmed(2),2*uv.Tlgm_aadmed(2),2*uv.Tlgm_aadmed(2),...
1367     'Color',col.BoxCPS,'LineWidth',2,'DisplayName','median (2*aad)','Parent',gui.axes11);
1368 % axis limits
1369 % xlims = [min([uncert.interp_Tlgm; invstd.Tlgm; uv.Tlgm(1)])*0.95 ...
1370 %     max([uncert.interp_Tlgm; invstd.Tlgm; uv.Tlgm(1)])*1.05];
1371 % ylims = [min([uncert.interp_E0; invstd.E0; uv.E0(1)])*0.95 ...
1372 %     max([uncert.interp_E0; invstd.E0; uv.E0(1)])*1.05];
1373 % xlims = [min([uncert.interp_Tlgm(in); invstd.Tlgm; uv.Tlgm(1)])*0.975 ...
1374 %     max([uncert.interp_Tlgm(in); invstd.Tlgm; uv.Tlgm(1)])*1.025];
1375 % ylims = [min([uncert.interp_E0(in); invstd.E0; uv.E0(1)])*0.975 ...
1376 %     max([uncert.interp_E0(in); invstd.E0; uv.E0(1)])*1.025];
1377 xlims = [min([tmpTlgm; invstd.Tlgm; uv.Tlgm(1)])*0.975 ...
1378     max([tmpTlgm; invstd.Tlgm; uv.Tlgm(1)])*1.025];
1379 ylims = [min([tmpE0; invstd.E0; uv.E0(1)])*0.975 ...
1380     max([tmpE0; invstd.E0; uv.E0(1)])*1.025];
1381 % -- lines indicating TLGM and E0 bounds --
1382 line([min(uncert.interp_Tlgm(in)) min(uncert.interp_Tlgm(in))],[ylims(1) ylims(2)],'Color',[0.25 0.25 0.25],...
1383     'LineStyle',':','LineWidth',0.75,'HandleVisibility','off','Parent',gui.axes11,'Tag','infolines');
1384 line([max(uncert.interp_Tlgm(in)) max(uncert.interp_Tlgm(in))],[ylims(1) ylims(2)],'Color',[0.25 0.25 0.25],...
1385     'LineStyle',':','LineWidth',0.75,'HandleVisibility','off','Parent',gui.axes11,'Tag','infolines');
1386 line([xlims(1) xlims(2)],[min(uncert.interp_E0(in)) min(uncert.interp_E0(in))],'Color',[0.25 0.25 0.25],...
1387     'LineStyle',':','LineWidth',0.75,'HandleVisibility','off','Parent',gui.axes11,'Tag','infolines');
1388 line([xlims(1) xlims(2)],[max(uncert.interp_E0(in)) max(uncert.interp_E0(in))],'Color',[0.25 0.25 0.25],...
1389     'LineStyle',':','LineWidth',0.75,'HandleVisibility','off','Parent',gui.axes11,'Tag','infolines');
1390 lgh = legend(gui.axes11,'Location','NorthEast');
1391 set(lgh,'EdgeColor',gui.myui.colors.axisFG,'TextColor',gui.myui.colors.axisFG);
1392 % axis settings
1393 set(gui.axes11,'XScale','lin','XLim',xlims);
1394 set(gui.axes11,'YScale','lin','YLim',ylims);
1395 set(gui.axes11,'CLim',clims);
1396 set(get(gui.axes11,'XLabel'),'String','TLGM');
1397 set(get(gui.axes11,'YLabel'),'String','initial amplitude E0');
1398
1399 % --- RTDs ---
1400 plotmethod = 1;
1401 switch uv.rtd_plotstyle
1402     case 'patchmean'
1403         plotmethod = 2;
1404     case 'patchmedian'
1405         plotmethod = 3;
1406     otherwise
1407         % nothing to do because 'lines' is default
1408 end
1409
1410 % the 'init' RTD
1411 F0 = invstd.T1T2f;
1412 % normalize all curves to the median of all E0 values
1413 E0norm = uv.E0_aadmed(1);
1414 if sum(F0)>0
1415     F = (data.invstd.porosity*100).*F0./E0norm;
1416     ylims = [0 max(F)*1.05];
1417 else
1418     ylims = [-1 1];
1419 end
1420 % the uncertainty runs
1421 % only the selected ones within the chi2 and xn bounds
1422 FDIST = uncert.interp_f(in,:);
1423 % scaling
1424 FDIST = (data.invstd.porosity*100).*FDIST./E0norm;
1425
1426 % if selected plot lines
1427 if plotmethod == 1
1428     % find maximum for axis limts
1429     f_max = max([ylims(2) max(FDIST(:))]);
1430     switch uv.colorstyle
1431         case {'chi2','xn'}
1432             % get colormap from chi2 vs xn axis
1433             cmap = get(gui.axes12,'Colormap');
1434             % make vector of values to sort
1435             idc = linspace(clims(1),clims(2),size(cmap,1));
1436             for i1 = 1:sum(in)
1437                 % find closest value (need for coloring)
1438                 idc1 = find(abs(idc-tmp(idx(i1)))==min(abs(idc-tmp(idx(i1)))));
1439                 % idc1 = abs(idc-tmp(idx(i1)))==min(abs(idc-tmp(idx(i1))));
1440                 % plot line with correct color
1441                 plot(invstd.T1T2me,FDIST(idx(i1),:),'-','Color',cmap(idc1(1),:),...
1442                     'LineWidth',1,'Displayname',num2str(tmp(idx(i1))),'Parent',gui.axes2);
1443             end
1444             % adjust color limits
1445             set(gui.axes2,'CLim',clims);
1446         otherwise
1447             % need to plot transpose of FDIST because 'x' is a column vector
1448             % otherwise plot goes bananas if numel(x) = #models
1449             plot(invstd.T1T2me,FDIST','-','Color',[0.5 0.5 0.5],...
1450                 'LineWidth',1,'Parent',gui.axes2);
1451     end
1452 end
1453
1454 % if selected plot patch
1455 if plotmethod > 1
1456     % what kind of patch is created
1457     if plotmethod == 2 % mean +- std
1458         mean_f = mean(FDIST);
1459         std_f = std(FDIST);
1460     else % median +- mad
1461         mean_f = median(FDIST);
1462         std_f = getAAD(FDIST,1);
1463     end
1464
1465     % patch lower and upper bounds
1466     patch_f_std1 = [mean_f+std_f;mean_f-std_f];
1467     patch_f_std2 = [mean_f+2*std_f;mean_f-2*std_f];
1468     patch_f_std3 = [mean_f+3*std_f;mean_f-3*std_f];
1469     patch_f_std1(patch_f_std1<0) = 0;
1470     patch_f_std2(patch_f_std2<0) = 0;
1471     patch_f_std3(patch_f_std3<0) = 0;
1472     f_max = max([ylims(2) max(patch_f_std1) max(patch_f_std2) max(patch_f_std3)]);
1473
1474     % draw all three patches on top of each other
1475     verts = [invstd.T1T2me patch_f_std3(2,:)'; flipud(invstd.T1T2me) flipud(patch_f_std3(1,:)')];
1476     faces = 1:1:size(verts,1);
1477     patch('Faces',faces,'Vertices',verts,'FaceColor',[0.6 0.6 0.6],...
1478         'FaceAlpha',0.75,'EdgeColor','none','Parent',gui.axes2);
1479     verts = [invstd.T1T2me patch_f_std2(2,:)'; flipud(invstd.T1T2me) flipud(patch_f_std2(1,:)')];
1480     faces = 1:1:size(verts,1);
1481     patch('Faces',faces,'Vertices',verts,'FaceColor',[0.4 0.4 0.4],...
1482         'FaceAlpha',0.75,'EdgeColor','none','Parent',gui.axes2);
1483     verts = [invstd.T1T2me patch_f_std1(2,:)'; flipud(invstd.T1T2me) flipud(patch_f_std1(1,:)')];
1484     faces = 1:1:size(verts,1);
1485     patch('Faces',faces,'Vertices',verts,'FaceColor',[0.2 0.2 0.2],...
1486         'FaceAlpha',0.75,'EdgeColor','none','Parent',gui.axes2);
1487 end
1488
1489 % adjust y-limits
1490 ylims(2) = max([ylims(2) max(f_max)*1.05]);
1491
1492 % plot original solution
1493 plot(invstd.T1T2me,F,'-','Color',col.FIT,'Parent',gui.axes2);
1494
1495 % axes properties
1496 ticks = 10.^(round(log10(min(invstd.T1T2me)) :1: log10(max(invstd.T1T2me))));
1497 set(gui.axes2,'XScale','log','XLim',[ticks(1) ticks(end)],'XTick',ticks);
1498 set(gui.axes2,'YScale','lin','YLim',ylims);
1499 set(get(gui.axes2,'XLabel'),'String','relaxation time');
1500 set(get(gui.axes2,'YLabel'),'String','amplitude');
1501 grid(gui.axes2,'on');
1502
1503 % -- RTD bounds --
1504 uv = data.uv;
1505 % line([uv.rtd_range(1) uv.rtd_range(1)],[0 ylims(2)],'Color',[0.25 0.25 0.25],...
1506 %     'LineStyle','-.','LineWidth',2,'Parent',gui.axes2,'Tag','infolines');
1507 % line([uv.rtd_range(2) uv.rtd_range(2)],[0 ylims(2)],'Color',[0.25 0.25 0.25],...
1508 %     'LineStyle','-.','LineWidth',2,'Parent',gui.axes2,'Tag','infolines');
1509 p_alpha = 0.8;
1510 if uv.rtd_range(1)>ticks(1)
1511     % draw a transparent patch
1512     v = [ticks(1) ylims(1); ticks(1) ylims(2);
1513         uv.rtd_range(1) ylims(2); uv.rtd_range(1) ylims(1)];
1514     f = [1 2 3 4 1];
1515     patch('Vertices',v,'Faces',f,'FaceColor','w','FaceAlpha',p_alpha,...
1516         'HandleVisibility','off','Tag','infolines','Parent', gui.axes2);
1517 end
1518 if uv.rtd_range(2)<ticks(end)
1519     % draw a transparent patch
1520     v = [ticks(end) ylims(1); ticks(end) ylims(2);
1521         uv.rtd_range(2) ylims(2); uv.rtd_range(2) ylims(1)];
1522     f = [1 2 3 4 1];
1523     patch('Vertices',v,'Faces',f,'FaceColor','w','FaceAlpha',p_alpha,...
1524         'HandleVisibility','off','Tag','infolines','Parent', gui.axes2);
1525 end
1526
1527 % --- Histograms ---
1528 % [f1,xi1] = getKernelDensityEstimate(uncert.interp_E0(in));
1529 % [f2,xi2] = getKernelDensityEstimate(uncert.interp_Tlgm(in));
1530 [f1,xi1] = getKernelDensityEstimate(uv.stats.E0_all);
1531 [f2,xi2] = getKernelDensityEstimate(uv.stats.Tlgm_all);
1532
1533 % plot the KDEs
1534 plot(xi1,f1,'Color',[0.5 0.5 0.5],'DisplayName','KDE','Parent',gui.axes21);
1535 plot(xi2,f2,'Color',[0.5 0.5 0.5],'DisplayName','KDE','Parent',gui.axes22);
1536
1537 % "init" E0
1538 line([invstd.E0 invstd.E0],[0 max(f1)],'Color',col.FIT,...
1539     'LineStyle',':','LineWidth',2,'Parent',gui.axes21,'DisplayName','init',...
1540     'Tag','infolines');
1541 % "init" TLGM
1542 line([invstd.Tlgm invstd.Tlgm],[0 max(f2)],'Color',col.FIT,...
1543     'LineStyle',':','LineWidth',2,'Parent',gui.axes22,'DisplayName','init',...
1544     'Tag','infolines');
1545
1546 % mean E0
1547 line([uv.E0(1) uv.E0(1)],[0 max(f1)],'Color',col.BoxPRC,...
1548     'LineStyle','-','LineWidth',2,'Parent',gui.axes21,'DisplayName','mean');
1549 line([uv.E0(1)+2*uv.E0(2) uv.E0(1)+2*uv.E0(2)],[0 max(f1)],'Color',col.BoxPRC,...
1550     'LineStyle','--','LineWidth',1,'Parent',gui.axes21,'DisplayName','2*std');
1551 line([uv.E0(1)-2*uv.E0(2) uv.E0(1)-2*uv.E0(2)],[0 max(f1)],'Color',col.BoxPRC,...
1552     'LineStyle','--','LineWidth',1,'Parent',gui.axes21,'DisplayName','2*std',...
1553     'HandleVisibility','off','Tag','infolines');
1554
1555 % mean TLGM
1556 line([uv.Tlgm(1) uv.Tlgm(1)],[0 max(f2)],'Color',col.BoxPRC,...
1557     'LineStyle','-','LineWidth',2,'Parent',gui.axes22,'DisplayName','mean');
1558 line([uv.Tlgm(1)+2*uv.Tlgm(2) uv.Tlgm(1)+2*uv.Tlgm(2)],[0 max(f2)],'Color',col.BoxPRC,...
1559     'LineStyle','--','LineWidth',1,'Parent',gui.axes22,'DisplayName','2*std');
1560 line([uv.Tlgm(1)-2*uv.Tlgm(2) uv.Tlgm(1)-2*uv.Tlgm(2)],[0 max(f2)],'Color',col.BoxPRC,...
1561     'LineStyle','--','LineWidth',1,'Parent',gui.axes22,'DisplayName','2*std',...
1562     'HandleVisibility','off','Tag','infolines');
1563
1564 % median E0
1565 line([uv.E0_aadmed(1) uv.E0_aadmed(1)],[0 max(f1)],'Color',col.BoxCPS,...
1566     'LineStyle','-','LineWidth',2,'Parent',gui.axes21,'DisplayName','median');
1567 line([uv.E0_aadmed(1)+2*uv.E0_aadmed(2) uv.E0_aadmed(1)+2*uv.E0_aadmed(2)],...
1568     [0 max(f1)],'Color',col.BoxCPS,'LineStyle','--','LineWidth',1,...
1569     'Parent',gui.axes21,'DisplayName','2*aad');
1570 line([uv.E0_aadmed(1)-2*uv.E0_aadmed(2) uv.E0_aadmed(1)-2*uv.E0_aadmed(2)],...
1571     [0 max(f1)],'Color',col.BoxCPS,'LineStyle','--','LineWidth',1,...
1572     'Parent',gui.axes21,'DisplayName','2*aad','HandleVisibility','off',...
1573     'Tag','infolines');
1574
1575 % median TLGM
1576 line([uv.Tlgm_aadmed(1) uv.Tlgm_aadmed(1)],[0 max(f2)],'Color',col.BoxCPS,...
1577     'LineStyle','-','LineWidth',2,'Parent',gui.axes22,'DisplayName','median');
1578 line([uv.Tlgm_aadmed(1)+2*uv.Tlgm_aadmed(2) uv.Tlgm_aadmed(1)+2*uv.Tlgm_aadmed(2)],...
1579     [0 max(f2)],'Color',col.BoxCPS,'LineStyle','--','LineWidth',1,...
1580     'Parent',gui.axes22,'DisplayName','2*aad');
1581 line([uv.Tlgm_aadmed(1)-2*uv.Tlgm_aadmed(2) uv.Tlgm_aadmed(1)-2*uv.Tlgm_aadmed(2)],...
1582     [0 max(f2)],'Color',col.BoxCPS,'LineStyle','--','LineWidth',1,...
1583     'Parent',gui.axes22,'DisplayName','2*aad','HandleVisibility','off',...
1584     'Tag','infolines');
1585 lgh = legend(gui.axes22,'Location','NorthWest');
1586 set(lgh,'EdgeColor',gui.myui.colors.axisFG,'TextColor',gui.myui.colors.axisFG);
1587
1588 % axes properties
1589 set(get(gui.axes21,'XLabel'),'String','E0');
1590 set(get(gui.axes21,'YLabel'),'String','kernel denisty estimate');
1591 set(get(gui.axes22,'XLabel'),'String','TLGM');
1592 set(get(gui.axes22,'YLabel'),'String','kernel density estimate');
1593
1594 % hold off all axes
1595 hold(gui.axes11,'off');
1596 hold(gui.axes12,'off');
1597 hold(gui.axes2,'off');
1598 hold(gui.axes21,'off');
1599 hold(gui.axes22,'off');
1600 end
1601
1602 %% close function
1603 function uv_closeme(src,~)
1604 figh = ancestor(src,'figure','toplevel');
1605 % try to close the sub GUI in a clean manner
1606 try
1607     % NOTE: maybe needed at some later point
1608     %     gui = getappdata(figh,'gui');
1609     %     data = getappdata(gui.figh_nucleus,'data');
1610     %     % update NUCLEUSinv
1611     %     setappdata(gui.figh_nucleus,'data',data);
1612     delete(figh);
1613 catch
1614     % if this is not working: just close it
1615     delete(figh);
1616 end
1617
1618 end
1619
1620 %------------- END OF CODE --------------
1621
1622 %% License:
1623 % MIT License
1624 %
1625 % Copyright (c) 2024 Thomas Hiller
1626 %
1627 % Permission is hereby granted, free of charge, to any person obtaining a copy
1628 % of this software and associated documentation files (the "Software"), to deal
1629 % in the Software without restriction, including without limitation the rights
1630 % to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
1631 % copies of the Software, and to permit persons to whom the Software is
1632 % furnished to do so, subject to the following conditions:
1633 %
1634 % The above copyright notice and this permission notice shall be included in all
1635 % copies or substantial portions of the Software.
1636 %
1637 % THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
1638 % IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
1639 % FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
1640 % AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
1641 % LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
1642 % OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
1643 % SOFTWARE.