Description of onMenuBatch
onMenuBatch
PURPOSE
handles the calls from the menus that control batch
SYNOPSIS
function onMenuBatch(src,~)
DESCRIPTION
onMenuBatch handles the calls from the menus that control batch
processing
 Syntax:
       onMenuBatch
 Inputs:
       src - handle of the calling object
 Outputs:
       none
 Example:
       onMenuBatch(src,~)
 Other m-files required:
       none
 Subfunctions:
       none
 MAT-files required:
       none
 See also: NUCLEUSinv
 Author: see AUTHORS.md
 email: see AUTHORS.md
 License: MIT License (at end)
CROSS-REFERENCE INFORMATION
This function calls:
clearInversion removes inversion results from the internal data structure
exportData exports data from both GUIs into various formats
runInversionBatch batch processes the inversion using for all NMR signals
This function is called by:
NUCLEUSinv_createMenus creates all GUI menus
SOURCE CODE
function onMenuBatch(src,~)
%onMenuBatch handles the calls from the menus that control batch
%processing
%
% Syntax:
%       onMenuBatch
%
% Inputs:
%       src - handle of the calling object
%
% Outputs:
%       none
%
% Example:
%       onMenuBatch(src,~)
%
% Other m-files required:
%       none
%
% Subfunctions:
%       none
%
% MAT-files required:
%       none
%
% See also: NUCLEUSinv
% Author: see AUTHORS.md
% email: see AUTHORS.md
% License: MIT License (at end)
%------------- BEGIN CODE --------------
% get tag
tag = get(src,'Tag');
switch tag
    case 'run'
        runInversionBatch;
    case 'clear'
        clearInversion('all');
    case 'save'
        exportData('INV','matA');
end
end
%------------- END OF CODE --------------
%% License:
% MIT License
%
% Copyright (c) 2024 Thomas Hiller
%
% Permission is hereby granted, free of charge, to any person obtaining a copy
% of this software and associated documentation files (the "Software"), to deal
% in the Software without restriction, including without limitation the rights
% to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
% copies of the Software, and to permit persons to whom the Software is
% furnished to do so, subject to the following conditions:
%
% The above copyright notice and this permission notice shall be included in all
% copies or substantial portions of the Software.
%
% THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
% IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
% FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
% AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
% LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
% OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
% SOFTWARE.