Description of onMenuViewFigures
onMenuViewFigures
PURPOSE
handles the extra menu entries to show additional
SYNOPSIS
function onMenuViewFigures(src,~)
DESCRIPTION
onMenuViewFigures handles the extra menu entries to show additional
graphical output
 Syntax:
       onMenuViewFigures
 Inputs:
       src - handle of the calling object
 Outputs:
       none
 Example:
       onMenuViewFigures(src)
 Other m-files required:
       showFitStatistics
 Subfunctions:
       none
 MAT-files required:
       none
 See also: NUCLEUSinv
 Author: Thomas Hiller
 email: thomas.hiller[at]leibniz-liag.de
 License: MIT License (at end)
CROSS-REFERENCE INFORMATION
This function calls:
ConductView is an extra subGUI to visualize hydraulic conductivity
showExtraGraphics shows additional figures for long time NMR lab
showFitStatistics shows an extra fit statistics figure (for T2 data)
showParameterInfo shows the parameter file info (if available)
This function is called by:
NUCLEUSinv_createMenus creates all GUI menus
NUCLEUSmod_createMenus creates all GUI menus
SOURCE CODE
function onMenuViewFigures(src,~)
%onMenuViewFigures handles the extra menu entries to show additional
%graphical output
%
% Syntax:
%       onMenuViewFigures
%
% Inputs:
%       src - handle of the calling object
%
% Outputs:
%       none
%
% Example:
%       onMenuViewFigures(src)
%
% Other m-files required:
%       showFitStatistics
%
% Subfunctions:
%       none
%
% MAT-files required:
%       none
%
% See also: NUCLEUSinv
% Author: Thomas Hiller
% email: thomas.hiller[at]leibniz-liag.de
% License: MIT License (at end)
%------------- BEGIN CODE --------------
%% label of the calling menu
label = get(src,'Label');
% chose the corresponding function
switch label
    case 'Parameter Info'
        showParameterInfo;
    case 'Fit statistics'
        showFitStatistics;
    case 'AMP-TLGM-SNR'
        showExtraGraphics('amp');
    case 'AMP vs TLGM'
        showExtraGraphics('ampvst');
    case 'RTD'
        showExtraGraphics('rtd');
    case 'ConductView GUI'
        ConductView(src);
end
end
%------------- END OF CODE --------------
%% License:
% MIT License
%
% Copyright (c) 2018 Thomas Hiller
%
% Permission is hereby granted, free of charge, to any person obtaining a copy
% of this software and associated documentation files (the "Software"), to deal
% in the Software without restriction, including without limitation the rights
% to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
% copies of the Software, and to permit persons to whom the Software is
% furnished to do so, subject to the following conditions:
%
% The above copyright notice and this permission notice shall be included in all
% copies or substantial portions of the Software.
%
% THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
% IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
% FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
% AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
% LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
% OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
% SOFTWARE.